### ISSUE TITLE
Toggle WP_DEBUG

### ISSUE THREAD

**Issue by mgor** [docker-library/wordpress#101]
Hey,

For development and troubleshooting issues it would be good to be able to change WP_DEBUG.

Suggested implementation is pushed in my fork:
https://github.com/docker-library/wordpress/compare/master...mgor:master

**Comment by md5** [comment]
@mgor Just to be clear, is the reason you didn't use `set_config` is that it assumes its argument is a string and you end up with `"true"`?

I think it would be worthwhile to make the `php_escape` function used by `set_config` capable of supporting `bool`/`boolean` as well.

**Comment by mgor** [comment]
@md5, yes that was the reason.

I'll have a look at extending the existing functions then.

**Comment by md5** [comment]
@mgor You may want to see what @tianon thinks, but it seems like making it support different typecasts would be pretty easy by passing a third parameter to `set_config` that indicates the type (defaulting to `string`).

**Comment by mgor** [comment]
@md5 [right now] there are only string or boolean values defined in wp-config.php, wouldn't it be overkill to add support for any other data types now?

**Comment by md5** [comment]
I was thinking of something like this:

```php
	php_escape() {
		php -r 'var_export(('"$2"') $argv[1]);' "$1"
	}
	set_config() {
		key="$1"
		value="$2"
		type="${3:-string}"
		regex="(['\"])$(sed_escape_lhs "$key")\2\s*,"
		if [ "${key:0:1}" = '$' ]; then
			regex="^(\s*)$(sed_escape_lhs "$key")\s*="
		fi
		sed -ri "s/($regex\s*)(['\"]).*\3/\1$(sed_escape_rhs "$(php_escape "$value" "$type")")/" wp-config.php
	}
```

**Comment by md5** [comment]
Then you could do something like this:

```php
set_config 'WP_DEBUG' true boolean
```

**Comment by mgor** [comment]
Yes, this was my starting approach as well. But there are two problems with it, which I ran into;

1. var_export((boolean) false) is returns true:

    root@18128ea47437:/var/www/html# type="boolean"
    root@18128ea47437:/var/www/html# type=${type:-string}
    root@18128ea47437:/var/www/html# php -r 'var_export(('"$type"') $argv[1]);' "true"
    true
    root@18128ea47437:/var/www/html# php -r 'var_export(('"$type"') $argv[1]);' "false"
    true
    root@18128ea47437:/var/www/html# php -r 'var_export(('"$type"') $argv[1]);' false
    true

2. The regular expressions in `set_config` are based on that the end of the value changed, is either ' or ", e.g.:

    $test = 'value';
    define('TEST', 'value');

The regular expression will not work in the cases where the "end of value" is ")" or ";", e.g.:

    $test = false;
    define('TEST', true);

I have pushed another suggested solution that solves these two issues:
https://github.com/docker-library/wordpress/compare/master...mgor:master

**Comment by mgor** [comment]
This was also the main reason that I didn't modify `set_config` in the first commit;
It seemed like modifying the function was a bigger change than what the code would actually contribute with, so I chose to use an inline sed-replace command.

**Comment by md5** [comment]
How about just supporting things like “set_config WP_DEBUG 1 boolean" and “
set_config WP_DEBUG 0 boolean"? i.e. whatever values PHP will actually cast
to true/false?

**Comment by mgor** [comment]
Ok, I came up with a more clean solution,

https://github.com/docker-library/wordpress/compare/master...mgor:master

**Comment by md5** [comment]
That seems like it could be problematic if there's an existing setting value in the file with ";" or ")" in it (e.g. a randomly generated salt).

**Comment by mgor** [comment]
Fair enough, updated solution.

Test results:

    root@12dbb4ed5905:/var/www/html# grep "DB_HOST" wp-config.php                         
    define('DB_HOST', 'my;)sql');
    root@12dbb4ed5905:/var/www/html# set_config 'DB_HOST' "mysql"                         
    root@12dbb4ed5905:/var/www/html# grep "DB_HOST" wp-config.php
    define('DB_HOST', 'mysql');
    root@12dbb4ed5905:/var/www/html# set_config 'DB_HOST' "mysq);l"
    root@12dbb4ed5905:/var/www/html# grep "DB_HOST" wp-config.php  
    define('DB_HOST', 'mysq);l');
    root@12dbb4ed5905:/var/www/html# set_config 'DB_HOST' "mysql"  
    root@12dbb4ed5905:/var/www/html# grep "DB_HOST" wp-config.php
    define('DB_HOST', 'mysql');
    root@12dbb4ed5905:/var/www/html# grep '$table_prefix' wp-config.php
    $table_prefix  = 'wp_';
    root@12dbb4ed5905:/var/www/html# set_config '$table_prefix' "test);_"
    root@12dbb4ed5905:/var/www/html# grep '$table_prefix' wp-config.php  
    $table_prefix  = 'test);_';
    root@12dbb4ed5905:/var/www/html# set_config '$table_prefix' "test_"  
    root@12dbb4ed5905:/var/www/html# grep '$table_prefix' wp-config.php
    $table_prefix  = 'test_';
    root@12dbb4ed5905:/var/www/html# set_config '$table_prefix' "wp_"  
    root@12dbb4ed5905:/var/www/html# grep '$table_prefix' wp-config.php
    $table_prefix  = 'wp_';
    root@12dbb4ed5905:/var/www/html# grep "WP_DEBUG"  wp-config.php                                                                 
    define('WP_DEBUG', true);
    root@12dbb4ed5905:/var/www/html# set_config 'WP_DEBUG' 0 boolean
    root@12dbb4ed5905:/var/www/html# grep "WP_DEBUG" wp-config.php  
    define('WP_DEBUG', false);
    root@12dbb4ed5905:/var/www/html# set_config 'WP_DEBUG' 1 boolean
    root@12dbb4ed5905:/var/www/html# grep "WP_DEBUG" wp-config.php  
    define('WP_DEBUG', true);
    root@12dbb4ed5905:/var/www/html# set_config 'WP_DEBUG' "test"   
    root@12dbb4ed5905:/var/www/html# grep "WP_DEBUG" wp-config.php
    define('WP_DEBUG', 'test');
    root@12dbb4ed5905:/var/www/html# set_config 'WP_DEBUG' 0 boolean
    root@12dbb4ed5905:/var/www/html# grep "WP_DEBUG" wp-config.php  
    define('WP_DEBUG', false);

**Comment by yosifkit** [comment]
Those changes look fine to me and that was some fairly thorough testing :+1:.

Ping @tianon.

**Comment by ahansson89** [comment]
Can we merge this?

**Comment by tianon** [comment]
Yeah, seems like a reasonably sane idea -- wanna make it an actual PR now, @mgor? :smile:

**Comment by ahansson89** [comment]
I just tested it. It works perfectly!

**Comment by mgor** [comment]
Github way of working is a bit backwards for me still, but I hope I managed to do it correctly :-)
