### ISSUE TITLE
Unzipping of plugins fails.

### ISSUE THREAD

**Issue by leon** [docker-library/wordpress#105]
I have this strange problem with extracting my plugins.

I've got an image that is based on wordpress:4-fpm which should take all my checked in plugins and add them to the right dir.

```docker
FROM wordpress:4-fpm

# Install unzip
RUN apt-get update && apt-get install -y unzip

# Add all plugins from /plugins dir
WORKDIR /var/www/html/wp-content/plugins/

# Copy all plugins, zipped or not to /wp-content/plugins
COPY ./plugins/* ./

# Unzip
RUN unzip "*.zip"

# Permissions on everything
RUN chown -R www-data:www-data .

# Remove plugins
RUN find . -name '*.zip' -delete
```

The strange thing is that it doesn't work.
If I change from `FROM wordpress:4-fpm` to `FROM debian:jessie` it works as expected.

I've done a small repo demonstrating the strange behavior.

https://github.com/leon/docker-error-wordpress-plugin-extraction

Does anyone have a clue as to why this isn't working?
Has it got anything to do with how wordpress copies itself to /var/www/html/?

**Comment by md5** [comment]
The problem is that `/var/www/html` is a volume. I'd recommend expanding your plugins into `/usr/src/wordpress/wp-content/plugins` to take advantage of the copying step in the entrypoint that you mentioned.

**Comment by leon** [comment]
Thanks!
now it's working as expected.
