### ISSUE TITLE
Apache mod_expires

### ISSUE THREAD

**Issue by nloewen** [docker-library/wordpress#107]
Is there a reason why mod_expires is not enabled in this image? Could it be added so that browser caching can be used by sites hosted with this image?

**Comment by tianon** [comment]
Seems sane to me -- I think we already explicitly enable "mod_rewrite", so
adding "mod_expires" on that same line should work fine.

**Comment by johanhaleby** [comment]
I don't suppose this fix is included in the latest 4.4-apache release available at dockerhub?

**Comment by tianon** [comment]
It wasn't, but it is now! (as of
https://github.com/docker-library/official-images/pull/1280) :+1:
