### ISSUE TITLE
New stable release is 4.4

### ISSUE THREAD

**Issue by mayeco** [docker-library/wordpress#109]
Please update the tags to the new release 4.4

https://codex.wordpress.org/Version_4.4
https://wordpress.org/news/2015/12/clifford/

**Comment by tianon** [comment]
This repo was updated in https://github.com/docker-library/wordpress/commit/4cae1f357818979b3a493d3cefbe55d69d9c765d, now we just need a PR to the official-images repo (which I'll make later today if nobody beats me to it).

**Comment by tianon** [comment]
Ok, PR is up: https://github.com/docker-library/official-images/pull/1258

I'm going to close this since everything we can possibly do for the update as far as this repo is concerned is done, and we'll track the latest status in that PR now. :+1:
