### ISSUE TITLE
Wordpress gives up retrying to connect to mysql

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker-library/wordpress#110]
I have a mysql+wordpress set up in docker-compose and I use container linking.

However mysql container sometimes takes a long time (>1 minute) to prepare and start listening on the port and in the meanwhile wordpress retries for “10 times” and then gives up, which is okay; but it does stay alive and does not retry again.

In other words, it hangs indefinitely instead of crashing with exit code 1 or something, which is a really bad choice on their side. I have `--restart=always` on wordpress container but it does not help because it does not exit in case of failure.

Any ideas/workarounds you can think of? Or should we take this up to wordpress repo?

**Comment by yosifkit** [comment]
Hmm, not sure why it would stay alive; it has `exit(1)` if it reaches the max tries. :confused:  It is not anything from wordpress upstream, but the entrypoint script that does the retries: https://github.com/docker-library/wordpress/blob/4cae1f357818979b3a493d3cefbe55d69d9c765d/apache/docker-entrypoint.sh#L140-L151

**Comment by ahmetalpbalkan** [comment]
hmm I can't seem to repro now, weird. Thanks!
