### ISSUE TITLE
Google PageSpeed

### ISSUE THREAD

**Issue by ahansson89** [docker-library/wordpress#113]
What are your thoughts about adding PageSpeed to the image?

**Comment by yosifkit** [comment]
Isn't it just a plugin? We'd rather stick to keeping the image as close to upstream WordPress as possible.

**Comment by ahansson89** [comment]
It is an Apache and Nginx module that speed things up

**Comment by ahansson89** [comment]
https://developers.google.com/speed/pagespeed/module/

**Comment by dannycolin89** [comment]
Is it open source?

**Comment by Moghedrin** [comment]
As yosifkit said, we try to stick as close to the upstream Wordpress as possible. Closing this issue for now: if any other maintainer thinks this is a good idea, we can reopen it and have that discussion at that time. :smiley:
