### ISSUE TITLE
docker-entrypoint.sh: set_config broken as of 4.4.1

### ISSUE THREAD

**Issue by hongymagic** [docker-library/wordpress#116]
There has been a change in Wordpress 4.4.1 (WordPress/WordPress@1acedc542fba2482bab88ec70d4bea4b997a92e4) which converts the sample `wp-config-sample.php` file's line endings from LF to CRLF. As a result, none of the configs are set when `docker-entrypoint.sh` script is run the first time.

The problem is in the [last line of `set_config`](https://github.com/docker-library/wordpress/blob/8ed138d4286424e04c87bf8577dd71fd50d0bc48/apache/docker-entrypoint.sh#L98) in all `docker-entrypoint.sh` files.

I have found that removing the last `$` in the pattern section resolves this issue. If indeed this is the proper fix, I can submit a PR otherwise, could you please fix the issue as new wordpress containers based on 4.4.1 won't work!

**Comment by yosifkit** [comment]
Thanks for the report; removing the `$` might work for some of the seds, but I think a better solution is to just fix the file.  I made a PR to always switch to unix line endings, #117.

**Comment by mmontagna** [comment]
+1 hope this gets fixed soon

**Comment by mgor** [comment]
Hey,

I just noticed this as well and I've identified a fix which I'll push soon.

Seems like 4.4.1 wp-config.php has whitespace after define(..); <-- which causes the regexp to stop working.
