### ISSUE TITLE
FPM Version

### ISSUE THREAD

**Issue by caiquecastro** [docker-library/wordpress#122]
Sorry if it is a dummy question (it probably is). How to work with the wordpress:fpm? Should it run with nginx?

**Comment by yosifkit** [comment]
No problem. Yes, you'll need another container like nginx to accept the http requests and the talk the fpm protocol to the `wordpress:fpm` container. There is a pretty good gist to get you started: https://gist.github.com/md5/d9206eacb5a0ff5d6be0.

related to #94

**Comment by tianon** [comment]
See also https://github.com/docker-library/docs/issues/238.
