### ISSUE TITLE
Unable to upload photo to the Media Library with HTTP error

### ISSUE THREAD

**Issue by tnguyen14** [docker-library/wordpress#125]
I am unable to upload a photo to the Media Library on a wordpress docker container.

The upload progress bar was moving, but at the end, I am taken to a screen with an error like so:

```
photo-1447752875215-b2761acb3c5d.png
HTTP error.
```

I have tried deactivating all plugins to see if anything is interfering with it, but that didn't solve the issue.

Has anyone run into this issue before/ know how to solve it? It feels like some sort of file permission or security constraint to me.

**Comment by dawnerd** [comment]
I get that when running behind nginx-proxy. Make sure your upload limits are set high enough.

**Comment by tnguyen14** [comment]
That's a good suggestion @dawnerd. Any idea on how to set the upload limits with nginx?

**Comment by tnguyen14** [comment]
I just tried with `client_max_body_size 1000m;` and that seems to have fixed the issue.
