### ISSUE TITLE
Image not updated for PHP 5.6.18

### ISSUE THREAD

**Issue by fbender** [docker-library/wordpress#126]
I'm using `wordpress:4-apache` and noticed that it still contains PHP 5.6.17 while v5.6.18 has been out for over a week. It thus looks like that the image is not updated when the PHP image is updated.

**Comment by yosifkit** [comment]
Sorry,  dependent images don't usually get rebuilt until the base image gets updated each month.  Since this is a security fix to php, I'll go poke the build server.

**Comment by fbender** [comment]
The base image was updated in docker-library/php@7bd5c38 (https://hub.docker.com/_/php/ advertises v5.6.18 as well). Are you referring to a different base image?

**Comment by yosifkit** [comment]
I was specifically talking about `debian`.  We update it at least once month; more when there are security fixes.

**Comment by fbender** [comment]
Ah ok! Shouldn't it be automatically updated on PHP fixes, too (should be easy since the PHP Images are updated as well)?

**Comment by obierlaire** [comment]
Hi there. When I pull the wordpress:apache 4.5.2-apache, php is not up to date (5.6.21 instead of 5.6.22), whereas php image 5.6 is well up to date. Is it possible to rebuild the wordpress image?

**Comment by tianon** [comment]
This is long since fixed, and the official images program will auto-rebuild the `wordpress` variants every time the underlying `php` images change.
