### ISSUE TITLE
Import an existing wp-content folder

### ISSUE THREAD

**Issue by jdcauley** [docker-library/wordpress#127]
How can I use this docker file and important existing wp-content folder with plugins and themes?

**Comment by booyaa** [comment]
if you've create a data container (called some-wordpress-data) and your backup is a compressed tarball you can this:

```
docker run -it --rm --name temp_wordpress_file_restore \
  --volumes-from some-wordpress-data  \
  -v $(pwd):/backup \
  ubuntu:14.04 tar xvfz /backup/wordpress.tar.gz -C /var/www/html
```

If you don't have a data container, I think you can still use docker scp to transfer the files into your wordpress container. Alternatively you can create a new Dockerfile and use ADD or COPY to transfer those files to /var/www/html

**Comment by tianon** [comment]
You can also just bind-mount directly into /var/www/html (which is how I
personally manage my own deployments).

For pre-baking an image to include plugins and themes, you can add them to
the appropriate locations within /usr/src/wordpress and they'll be included
in the resulting instance.

**Comment by booyaa** [comment]
@jdcauley have you had a chance to try either methods suggested by me or @tianon ?

**Comment by jdcauley** [comment]
Just went looking through issues I could close, I just need an Add with the folder in the Repo

```
ADD ./wp-content /usr/share/nginx/www/wp-content/
```

Didn't realize it was a thing when I wrote this.
