### ISSUE TITLE
Can't change wordpress url

### ISSUE THREAD

**Issue by rougeth** [docker-library/wordpress#131]
Hello people, I'm running wordpress (using the docker-compose.yaml below) and when I try to change *siteurl* and *home* to *.../blog/* everything breaks:
```
/ - 200 OK but all static files are 404
/blog/?p=1 -(post with id=1 that exists) 404
/?p=1 - (post with id=1 that exists) 200
/blog/?author=1 - 404
/?author=1 - 200
```
```
# docker-compose.yaml
wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8001:80
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
```
any help on this?

**Comment by lazyfrosch** [comment]
And how are you "redirecting" the wordpress code to a /blog subdir?

**Comment by rougeth** [comment]
@lazyfrosch I'm doing it directly from the admin interface

**Comment by lazyfrosch** [comment]
That is merely a setting, you need to actually move Wordpress's code to put it in a sub-directory.

This option is meant for the interface to understand where it is as a full qualified URL.

**Comment by rougeth** [comment]
oh! sorry about the ignorance :/ there isn't an option to change it automatically, is there?

**Comment by lazyfrosch** [comment]
Maybe with a few tricks, but that is up to experimentation, maybe you will have to modify the image for your purpose.

Question is also where you homepage would be hosted?

Currently I'd say its unsupported, until someone tests, documents and approves it.

**Comment by lazyfrosch** [comment]
PRs are welcome! if that wasn't clear :wink:

**Comment by rougeth** [comment]
perfect! :) thank you @lazyfrosch
