### ISSUE TITLE
Container fails to start when NFS-backed volume is mounted at /var/www/html

### ISSUE THREAD

**Issue by lmsurpre** [docker-library/wordpress#137]
I am trying to run this image on the IBM Containers service, but unfortunately when I map a volume to /var/www/html, it fails to start with the following errors:

```
WordPress not found in /var/www/html - copying now...
tar: ./wp-content/index.php: Cannot change ownership to uid 33, gid 33: Permission denied
tar: ./wp-content/plugins/akismet/readme.txt: Cannot change ownership to uid 33, gid 33: Permission denied
tar: ./wp-content/plugins/akismet/LICENSE.txt: Cannot change ownership to uid 33, gid 33: Permission denied
tar: ./wp-content/plugins/akismet/index.php: Cannot change ownership to uid 33, gid 33: Permission denied
tar: ./wp-content/plugins/akismet/wrapper.php: Cannot change ownership to uid 33, gid 33: Permission denied
...
```

After poking around, it looks like there is currently a limitation with the use of NFS-backed volumes which prevents the changing of file owners:  https://console.ng.bluemix.net/docs/containers/container_troubleshoot.html#ts_vol_owner

As a workaround, I have wrapped this image with my own dockerfile that
1. adds the www-data user to the root group; and
2. grants group write access to /var/www/html

Happy to receive feedback on that approach, as well as any other ideas for working around this limitation.
Are there simple changes that could be made to the official image to make it work in this type of environment?

**Comment by shankiesan** [comment]
@lmsurpre did you get anywhere further with this? I'm having exactly the same problem.

**Comment by lmsurpre** [comment]
No, I havn't looked at this in a long while.  You can check our hacked up entrypoint at https://github.com/ibmjstart/wp-bluemix-container but I'd love to hear from docker/wordpress experts on whether there's a better way.

**Comment by tianon** [comment]
Sorry for the massive delay!

I think https://github.com/docker-library/wordpress/pull/249 will probably help with this, since it allows to change the `chown` to a user of your choosing (such that it could match the underlying storage directly).

Since that's I think the best we can do from the image, I'm going to close.  If there's more we can do to help, a new detailed issue (or PR) describing the issue, simple reproducer, and suggested change would be great!
