### ISSUE TITLE
Attempt to create database in docker-entrypoint.sh doesn't work with unix domain sockets

### ISSUE THREAD

**Issue by prashantv** [docker-library/wordpress#138]
The `WORDPRESS_DB_HOST` environment variable is used to set `DB_HOST` in `wp-config.h`. This variable is allowed to be a `host:port` but it may also be a unix domain socket if specified as `localhost:/path/to/socket`.

When using `mysqli`, the caller has to pass the socket to a separate parameter, see the logic in wordpress:
https://github.com/WordPress/WordPress/blob/master/wp-includes/wp-db.php#L1469

Currently, the `docker-entrypoint.sh` fails on the database creation since it does not handle domain sockets:
https://github.com/docker-library/wordpress/blob/master/docker-entrypoint.sh#L154

**Comment by amkumarnet** [comment]
Its Very Usefull to Me thanks dear [http://jobskeeda.in](url)
