### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by signofkoen** [docker-library/wordpress#140]
Will there be an nginx version for Wordpress anytime soon?

**Comment by shankiesan** [comment]
This doesn't directly address your question, but I've had a lot of success using this image behind an nginx reverse proxy – this one includes Let's Encrypt for free...

https://github.com/SteveLTN/https-portal

It means that you can use out-of-the-box WP with nginx speed.

**Comment by yosifkit** [comment]
As I see it, there wouldn't be a `wordpress-nginx` image, but that you should use `wordpress-fpm` with nginx in front of it.

[Pierreozoux](https://github.com/pierreozoux) has a pretty good example in https://github.com/indiehosters/wordpress.  It is using the `indiehosters/wordpress` image which is based on `wordpress-fpm` with a few extra [php modules installed](https://github.com/indiehosters/docker-wordpress/blob/4c21372f7640f61a51074f31232757926fec1889/Dockerfile#L7).

**Comment by signofkoen** [comment]
@yosifkit When using the wordpress-fpm image. I get an 502 Bad Gateway message.

#182
