### ISSUE TITLE
Issue with MySql v5.6 & v5.7

### ISSUE THREAD

**Issue by jwdavidson** [docker-library/wordpress#145]
The Wordpress bootstrap code fails to properly initialize a new database when the target database is mysql version 5.6 or 5.7. The reason for this is that the code that does the boot strap does not set the grant for the wordpress user correctly. The grant in version 5.5of mysql is for wordperss_user@localhost. However docker runs wordpress on a different ip. The default network is 172.17.0.0 and in my case mysql is running on 172.17.0.2 and wordpress 172.17.0.3. 

In mysql version 5.5 the grant for localhost appears to include any network running on localhost. However with the latest version of mysql 5.6 and 5.7 localhost no longer includes networks in the 172.x.y.z ranges. The issue is corrected by issuing a grant to wordpress_user@172.17.0.3

A work around to correct the issue until it is fixed is to manually issue the grant using the following sample (root_password, /path/to/local/dir, wordpress_db, wordpress_user and user_password need to be replaced with real values for your implementation):

```
bash> docker run --name mysql -v /path/to/local/dir:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root_password -d mysql
bash> docker exec -it mysql bash
mysql_docker> mysql -u root -p --host 172.17.0.2
mysql> grant all privileges on wordpress_db.* to 'wordpress_user'@'172.17.0.3' identified by 'user_password'
mysql> exit
mysql_docker> exit
```

This will also fix a Connection Refused error when trying to upgrade a mysql docker instance from version 5.5 to 5.6 or 5.7

**Comment by yosifkit** [comment]
I am not sure what "Wordpress bootstrap code" you are referring to.  The WordPress entrypoint script does not create any database users.

We recommend that you set up a user, password, and database in the mysql container using [its environment variables](https://github.com/docker-library/docs/tree/master/mysql#environment-variables) and then passing those same values to the WordPress container as environment variables `WORDPRESS_DB_USER`, `WORDPRESS_DB_PASSWORD`, and `WORDPRESS_DB_NAME`, respectively.  You would probably also need to supply `WORDPRESS_DB_HOST` to the WordPress container.  See the [documentation](https://github.com/docker-library/docs/tree/master/wordpress#how-to-use-this-image) from the Docker Hub for more information.

**Comment by jwdavidson** [comment]
It is not part of the entrypoint script. Wordpress creates a user in its
initialization PHP, but that user is only set up for localhost. I can see
this is going to be a difficult one to get resolved as it is not part of
the docker configuration, but it only impacts docker users.

That is why I included the work around code.

The Grant All ... command could be added to the entrypoint code if the
msqli() Connection refused is detected. I just don't know if that is wise.

John Davidson

**Comment by tianon** [comment]
I don't think there's anything we can do to fix this in the image, given that it's a quirk of upstream.  I'd recommend pre-creating your database users in order to work around this (and control your own destiny).
