### ISSUE TITLE
Slow performance when using Docker for Mac

### ISSUE THREAD

**Issue by shankiesan** [docker-library/wordpress#149]
Has anyone else started using Docker for Mac and noticed poor performance using the WordPress image compared with using the same image under Docker Toolbox?

It's completely anecdotal, but on our four machines in the office, it all feels slower when using for Mac. Any ideas?

**Comment by jordscream** [comment]
issue in progress : https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076

**Comment by yosifkit** [comment]
Since this is an issue with "Docker for Mac" and not the image itself, I am closing this issue.  Hopefully the issue will help users find the mentioned forum thread.

**Comment by geerlingguy** [comment]
Note that there's an open issue on GitHub now too: https://github.com/docker/for-mac/issues/77

**Comment by hoatle** [comment]
anyone here wanna try a truly universal software development platform?

teracy-dev is created to set up a universal development platform which has the same development workflow on Mac, Linux and Windows with good developer experience and productivity in mind.

We have docker and docker-compose preinstalled, better than docker toolbox, docker native app.

The project is here: https://github.com/teracyhq/dev with getting started docs here http://dev.teracy.org/docs/develop/getting_started.html

I hope this will help. Thanks.

**Comment by keksnicoh** [comment]
For me docker-sync required huge CPU time and after updating rsync it did not work at all. It seems quiet fragile to use rsync or unison as a hack here. docker for mac is a nice tool which is my first choice for most projects. Due to the sync problems, for some projects, I must go back to docker-machine until the this problem is under control. anyway, thanks to the whole team for  all the effort!

**Comment by hoatle** [comment]
hello everyone, you should try this project https://github.com/teracyhq/dev it solves all the slowness on Mac and Windows, you can see how it's used with this guide (apply to other stacks): http://dev.teracy.org/docs/nodejs_dev_guide.html

it has DNS (domains on /etc/hosts file) and https automatically support out of the box.
