### ISSUE TITLE
"siteurl" TLS scheme is ignored when trying to use a reverse proxy

### ISSUE THREAD

**Issue by pdevine** [docker-library/wordpress#150]
We're missing how to do TLS termination with Wordpress in all of our documentation.  There are essentially two ways of doing it:
1. Create a new Dockerfile and make certain you've set up the correct TLS conf/load files and a new apache2.conf file
      (cd /etc/apache2/mods-enabled && ln -s ../mods-available/ssl.conf && ln -s ../mods-available/ssl.load && ln -s ../mods-available/socache_shmcb.load)

OR;
1. Use a reverse proxy container which does the TLS termination for you and just pass-through to the Wordpress container over the bridge network.

The problem with the later solution is that Wordpress checks the http scheme of way you're connecting to it, and ignores the scheme of the siteurl variable.  Unfortunately that means that most URLs generated for your Wordpress site (like static files) are going to have "http://" prepended to them instead of "https://" since the TLS termination isn't happening in the Wordpress container.

**Comment by tianon** [comment]
I think https://wordpress.org/support/topic/wordpress-behind-a-reverse-proxyssl-endpoint-slightly-borked is relevant here -- this isn't really a "container" or "Docker" specific problem; it's more about reverse proxies (and applies generally to upstream as-is).

**Comment by pdevine** [comment]
We should at least doc this to make it useful for people.  Figuring out how to make this work was really painful.
