### ISSUE TITLE
Debug excluded from argument setup

### ISSUE THREAD

**Issue by vyscond** [docker-library/wordpress#153]
Any special reason to not make the following variable being controlled by docker environment setups?

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
@ini_set('display_errors', 0);
```

**Comment by thomasmery** [comment]
I believe you can setup `WORDPRESS_DEBUG` to `1` or `'true'`

making other settings available would be nice indeed

maybe you can use _volumes_ and have a custom `wp-config.php` to be used

for instance in a _docker-compose_ file:

```docker
 volumes:
       - ./my-wp-config.php:/var/www/html/wp-config.php
```

should work (not tested for now)

**Comment by motleydev** [comment]
I would like to revisit this idea and have WP_DEBUG, WP_DEBUG_LOG and WP_DEBUG_DISPLAY as ENV vars for use in a compose file. These are so integral to development of Wordpress I think this feature would get a ton of use.

**Comment by motleydev** [comment]
https://github.com/docker-library/wordpress/pull/142 could also work.
