### ISSUE TITLE
Pretty permalinks broken because of missing "AllowOverride All"

### ISSUE THREAD

**Issue by mlogic** [docker-library/wordpress#158]
The 7/6/2016 update to the WordPress docker image broke the pretty permalinks [1], which is set by using /var/www/html/.htaccess, which again relies on "AllowOverride All". AllowOverride was enabled in all pre-7/6/2016 images (by the customized /etc/apache2/apache2.conf) but isn't set by the new conf-available/docker-php.conf. Please add "AllowOverride All" to conf-available/docker-php.conf.

[1] https://codex.wordpress.org/Using_Permalinks#Using_.22Pretty.22_permalinks

**Comment by tianon** [comment]
This is actually an issue in the `php` image (see https://github.com/docker-library/php/issues/254) -- will track it over there, thanks! :+1:

**Comment by themao** [comment]
Is it broken again? I'm using the latest image and default apache config does not have the `AllowOverride All` directive, so the permalinks don't work

**Comment by yosifkit** [comment]
@themao, it seems fine to me:
```console
$ docker run -it --rm wordpress bash
root@c491c2911728:/var/www/html# cd $APACHE_CONFDIR
root@c491c2911728:/etc/apache2# cat conf-enabled/docker-php.conf 
<FilesMatch \.php$>
	SetHandler application/x-httpd-php
</FilesMatch>

DirectoryIndex disabled
DirectoryIndex index.php index.html

<Directory /var/www/>
	Options -Indexes
	AllowOverride All
</Directory>
root@c491c2911728:/etc/apache2# 
```
