### ISSUE TITLE
saving and restoring the container

### ISSUE THREAD

**Issue by akaydinb** [docker-library/wordpress#16]
Hi,
I am using official mysql container as DB and after pulling the "latest", I am starting it with:
docker run --name somename-mysql -e MYSQL_ROOT_PASSWORD=somepass -d mysql

Then I start latest wordpress container:
docker run --name somename-wordpress --link somename-mysql:mysql -p 8080:80 -d wordpress

I have added some content to wordpress page. 

I regularly backup both containers with the following commands:
docker commit <SQLcontainerID> mysql:sometag
docker commit <WPcontainerID> wordpress:sometag
docker save wordpress:sometag | gzip > wordpress.tar.gz
docker save mysql:sometag | gzip > mysql.tar.gz

After moving the tar.gz files into another docker host and loading them:
docker load < mysql.tar.gz
docker load < wordpress.tar.gz

I cannot see the repo name and tag. Therefore I have to start the containers with the above run parameters using corresponding image IDs. But after this operation I cannot see the content. I only get wordpress' installation screen. Do I something wrong?

Any help will be appreciated. Have a nice day.

**Comment by pierreozoux** [comment]
+1 for @tianon answer.

@akaydinb did it solve your issue? If yes, please consider closing it.

Thanks!

**Comment by akaydinb** [comment]
Hi,
Thanks for the answer (and apologize for my late reply). "volumes-from" worked great. Here is my solution:

## File backup
docker run --rm -v $DIRECTORY:/backups --volumes-from=wordpress busybox tar -c /var/www/html -f /backups/html.tar

## Automated DB backup. Print mysqldump into a file and call it in the container 
cat > $DIRECTORY/dbbackup.sh << EOF
#!/bin/bash

mysqldump --host \$DZ_PORT_3306_TCP_ADDR -u root --password=somepass wordpress > /backups/wordpress.sql
EOF

chmod +x $DIRECTORY/dbbackup.sh

docker run --rm -v $DIRECTORY:/backups --link=mysql:DZ mysql /backups/dbbackup.sh


Thanks.

**Comment by thinhduckhoi** [comment]
@akaydinb Sorry, i just found out about your post. I had the same problem. But when running your command, it didn't work.
docker run --rm -v /root/backup:/backups --volumes-from=wordpress busybox tar -c /var/www/html -f /backups/html.tar

It said: Error response from daemon: no such id: wordpress. Though i pulled wordpress and mysql just like you did.
docker run --name ksql -e MYSQL_ROOT_PASSWORD=789789 -d mysql
docker run --name kwordpress --link ksql:mysql -p 8080:80 -d wordpress

**Comment by yosifkit** [comment]
@thinhduckhoi, the `--volumes-from` needs to have the name or id of your wordpress container (ie, `kwordpress`).  In @akaydinb's case, he ran his wordpress container with `docker run --name wordpress ...`.

`DZ` is the name of the link to the mysql container, so when using `--link  ksql:dz` the variable `$DZ_PORT_3306_TCP_ADDR` will contain the address of the mysql container. The contents of the file would be something like:
```bash
#!/bin/bash
mysqldump --host $DZ_PORT_3306_TCP_ADDR -u root --password=somepass wordpress > /backups/wordpress.sql
```

```console
$ # my containers are running like this:
$ docker run --name ksql -e MYSQL_ROOT_PASSWORD=789789 -d mysql
$ docker run --name kwordpress --link ksql:mysql -p 8080:80 -d wordpress

$ # to back up wordpress files:
$ docker run --rm -it -v "$PWD":/backups --volumes-from=kwordpress busybox tar -c /var/www/html -f /backups/html.tar

$ # backup mysql using the script above
$ docker run --rm -it -v "$PWD":/backups --link=kmysql:dz mysql /backups/dbbackup.sh
$ # or in one line:
$ docker run --rm -it -v "$PWD":/backups --link=kmysql:dz mysql sh -c 'mysqldump --host $DZ_PORT_3306_TCP_ADDR -u root --password=$DZ_ENV_MYSQL_ROOT_PASSWORD wordpress > /backups/wordpress.sql'
```
