### ISSUE TITLE
Media upload always fails in Docker container

### ISSUE THREAD

**Issue by EricTousignant** [docker-library/wordpress#163]
Hello everyone,

I'm a veteran WordPress developer but fairly new to the Docker environment.
I am currently on a time-crunch to finish a project, but it seems I'm stuck on a very annoying problem.

Whenever I try to upload an image to WordPress, either through a post's Media feature, or in the Media Library, the image either get's corrupted or simply fails with the following message: "The uploaded file was only partially uploaded."

![failedupload](https://cloud.githubusercontent.com/assets/2239084/17128893/cc56df58-52dd-11e6-8162-2499e65369be.png)

I'm on a fresh install of Windows 10, and using the latest version of Docker for Windows (HyperV).
I used the default WordPress docker image (wordpress:latest) in a docker-compose.yml (attached).

At first, I was using a complicated setup with an nginx reverse proxy and data volumes.
So I ran some tests and ended up with the following [docker-compose.yml](https://github.com/docker-library/wordpress/files/383209/docker-compose.txt) that is the bare minimum and taken nearly exactly from this page https://docs.docker.com/compose/wordpress/.

I tried port 80 and 8080, I tried using 127.0.0.1 and the hostname (domain) I was using when I first noticed the issue. In all cases I could still reproduce the issue.

**EDIT:** When I started running tests to isolate the problem, I stopped the reverse proxy configuration and was using only the two containers in the attached docker-compose.yml!

Thank you in advance.

**Comment by EricTousignant** [comment]
So after being obsessed with this, I tried a lot of things and it seems it's a [Docker for Windows bug](https://forums.docker.com/t/php-file-upload-fails-with-upload-err-partial-on-docker-for-windows/18252).

If you want a quick workaround for the moment, apparently the uploads work fine when accessing the wordpress install through http://docker/ instead of whatever domain/hostname you had setup. This is not helping me since I need access from outside my network, but at least it might help some other people.

**Comment by EricTousignant** [comment]
This upload issue was fixed by the latest release of Docker for Windows.

**Comment by Pixelartist** [comment]
I can confirm that with the latest update this issue vanished.
