### ISSUE TITLE
TERM not found

### ISSUE THREAD

**Issue by andrewbanchich** [docker-library/wordpress#169]
When I run `docker exec -it [container] bash` to go into the shell of a WordPress container, I cannot run `clear` to clear out my terminal. When I do, it gives me a TERM not found error. This is not an issue with other containers I have used, so I am thinking it is a bug with the WordPress one.

I'd love a fix for this since the terminal can get so messy without `clear`.

**Comment by yosifkit** [comment]
This is not really an issue with the image; `TERM` comes from the environment, so `docker exec` will only have `TERM` set if it is set in the image or during `docker run`.  There is a PR in docker for adding `--env` to `docker exec`, but it is still in progress: https://github.com/docker/docker/pull/24594.

You could use `reset`, but then you loose scroll-back.

**Comment by andrewbanchich** [comment]
@yosifkit Is there a reason why the official WordPress image doesn't set it in the image? I know there are workarounds, but it would be nice to have support for this out of the box.

**Comment by yosifkit** [comment]
We don't set it in any of the official images. We can't really know what to set it to; on my local machine in an xfce4-terminal it is `xterm-256color`, but if I check one of the console ttys its value is `linux`, whereas if I am in a tmux session the value is `screen`.

**Comment by tianon** [comment]
Closing since this isn't an issue with the image.

Also, in newer versions of Docker, `docker exec -t` will automatically set `TERM` to `xterm`.
