### ISSUE TITLE
Should we remove readme.html for security reason?

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/wordpress#170]

**Comment by lazyfrosch** [comment]
Isn't that file replaced / created with a Wordpress Self-Update?

If you are worried about the version:

    <meta name="generator" content="WordPress 4.5.4" />

**Comment by tianon** [comment]
I agree with @lazyfrosch; I think this is probably a somewhat misleading game of cat-and-mouse that we ought not participate in.  We provide a fairly stock install of Wordpress following upstream's installation recommendations, which is one of our primary focus points for the maintenance of this image, and there are other means of determining the Wordpress version than just `readme.html`. :+1:
