### ISSUE TITLE
Environment variables starting with a dash break sed

### ISSUE THREAD

**Issue by aficiomaquinas** [docker-library/wordpress#171]
I could finally track why passing my salts as env variables was giving me a fatal error. One of them started with a dash `-`.
Basically, any variable (not just the salts) passed as env variable starting with a dash, will produce an error, some preventing the image to be initialized, others writing errors onto the `wp-config.php` file.

For instance, this variable:
`WORDPRESS_SECURE_AUTH_SALT=-L&.VgRfNp =}{,pT/uSwwLbN$N+$P5;pW;JfSZ~F/n;Qr?> U{B@C.L*dzos:uj`
Will throw this fatal error in the docker terminal:
```sed: -e expression #1, char 88: unterminated `s' command` error.```, preventing it from starting.

While this one:
`WORDPRESS_SECURE_AUTH_SALT=-r&.VgRfNp =}{,pT/uSwwLbN$N+$P5;pW;JfSZ~F/n;Qr?> U{B@C.L*dzos:uj`
Produces the following output in the `wp-config.php` file:
`define('SECURE_AUTH_SALT', You can use -r only once.);`

So my guess is that sed is taking that first letter after the dash as an argument.
I'd be delighted to submit a patch, but my sed skills are close to zero.

**Comment by tianon** [comment]
Excellent, thanks for the detailed report!  I'll take a look and see if I can track down a fix. :+1:
