### ISSUE TITLE
Add an image with just WP (w/o web server)?

### ISSUE THREAD

**Issue by otravers** [docker-library/wordpress#175]
It seems the only available images include either Apache or PHP-FPM. Can you add an image with just WordPress, so that I can run PHP-FPM in its own container and elect which version of PHP I want to run, add Xdebug etc.

This would solve this issue:
https://github.com/docker-library/wordpress/issues/106

**Comment by tianon** [comment]
Not sure what exactly you're asking for here -- do you mean an image that doesn't have PHP at all and simply includes the Wordpress tarball?

**Comment by otravers** [comment]
Yes, that's what I meant, so that I can run WP, php-fpm and Nginx in three separate containers.

**Comment by otravers** [comment]
Yes, so that I can run WP, php-fpm and Nginx in three separate containers.

**Comment by tianon** [comment]
The issue with that is that without PHP/`php-fpm`, "running WordPress" doesn't make any sense -- WordPress itself is merely source code executed by the PHP interpreter at runtime via PHP-FPM itself. :confused:

**Comment by otravers** [comment]
Right. Since posting this I moved on to managing WordPress as a Composer dependency.
