### ISSUE TITLE
Get Bad Gateway when using Wordpress:fpm

### ISSUE THREAD

**Issue by signofkoen** [docker-library/wordpress#182]
When using the wordpress:fpm image. I get the 502 Bad Gateway error on the webpage.

I'm using jwilder/nginx-proxy container infront of the Wordpress:fpm container.

**Comment by yosifkit** [comment]
`jwilder/nginx-proxy` is not an fcgi frontend, and is just a pass-through proxy for your containers.  Its config would need to have something similar to [line 83](https://github.com/indiehosters/wordpress/blob/9ea47cd181f4f41d059c4758d3b4aefc79a42624/nginx.conf#L83) in `indiehosters/wordpress`.  The fpm container does not speak http and requires a service in front that speaks http to the client and fcgi to php-fpm.
