### ISSUE TITLE
Enable fast-cgi option on wordpress container

### ISSUE THREAD

**Issue by cyrusd87** [docker-library/wordpress#191]
Hi, 
I am using docker with Convox to build a wordpress website (with apache image).
I am having some performance issues and I would like to enable the fast-cgi option to try to improve the performance.

Is there a way with docker to make this? Are there other solutions to improve the performance?

Thanks a lot

**Comment by tianon** [comment]
Fixed in https://github.com/docker-library/wordpress/pull/61! :+1:
