### ISSUE TITLE
Variable Unbound Error: When adding a custom entrypoint that uses the original docker-entrypoint.sh

### ISSUE THREAD

**Issue by myuseringithub** [docker-library/wordpress#194]
Official Wordpress "docker-entrypoint.sh" is run from a custom shell script, throughs an error:
`/usr/local/bin/docker-entrypoint.sh: line 26: $1: unbound variable`
Line points to:
`if [[ "$1" == apache2* ]] || [ "$1" == php-fpm ]; then` in https://github.com/docker-library/wordpress/blob/master/docker-entrypoint.sh

Steps to reproduce: 

- Add a custom entrypoint to docker-compose.yml (after adding the file to container /usr/local/bin/custom-entrypoint.sh using the Dockerfile): 
`... 
entrypoint: custom-entrypoint.sh`
Contents of custom-entrypoint.sh: 
```
sed -i -e 's/^exec "$@"/#exec "$@"/g' /usr/local/bin/docker-entrypoint.sh
source docker-entrypoint.sh
exec "$@"
```

- Build & Run the error will appear, although it is the exact same shell from the official repository, what's different ?

**Comment by tianon** [comment]
What's different is the arguments provided -- in the image as-is, we don't run `docker-entrypoint.sh` by itself, but rather pass `apache2-foreground` or `php-fpm` to it (depending on which variant we're using).  So the final command is something more like `docker-entrypoint.sh apache2-foreground`.

**Comment by myuseringithub** [comment]
That what I was missing... Thanks ! I ended up forking the `dockerfile` and related `docker-entrypoint.sh`, and added what I need. 
Can you explain to me in simple words what this gibberish means: 
`sed -i -e 's/^exec "$@"/#exec "$@"/g' /usr/local/bin/docker-entrypoint.sh` 
Where does it search for exec in ? what does it replace ? Why ?

**Comment by tianon** [comment]
That line searches for a line that starts with `exec "$@"` in the existing entrypoint script and comments it out so that it doesn't run.  That `exec` line will actually _run_ the arguments to the script after it executes, rather than simply running the initialization steps.

**Comment by myuseringithub** [comment]
Oh.. simple way of extending the shell script. Thanks

**Comment by jfahrenkrug** [comment]
Just some background info for others who find this thread:
The basic problem is that if the base image defines *BOTH* `CMD` and `ENTRYPOINT`, your image also has to override both. You can't just override `ENTRYPOINT` and then keep/inherit `CMD`. The docs say:

> Note: If CMD is defined from the base image, setting ENTRYPOINT will reset CMD to an empty value. In this scenario, CMD must be defined in the current image to have a value.

Source: https://docs.docker.com/engine/reference/builder/#entrypoint

**Comment by semihsezer** [comment]
If you end up here because of a similar issue in bitnami/postgresql chart, see this thread instead. It could be due a dollar sign in the password.

`/entrypoint.sh: line 17: $4: unbound variable`

https://github.com/bitnami/bitnami-docker-postgresql/issues/213
