### ISSUE TITLE
Configure all wp-config.php variable with Docker environment variables ?

### ISSUE THREAD

**Issue by harobed** [docker-library/wordpress#200]
What do you think about configure `wp-config.php` with Docker environment variables ?

Like this:

```
<?php

define('WP_CONTENT_DIR', '/var/www/wp-content');

$table_prefix  = getenv('TABLE_PREFIX') ?: 'wp_';

foreach ($_ENV as $key => $value) {
  $capitalized = strtoupper($key);
  if (!defined($capitalized)) {
    define($capitalized, $value);
  }
}

if (!defined('ABSPATH'))
    define('ABSPATH', dirname(__FILE__) . '/');

require_once(ABSPATH . 'wp-settings.php');
?>
```

source: https://codeable.io/wordpress-developers-intro-to-docker-part-two/#configuring-wp-configphp

It is useful for instance to configure `FS_METHOD=direct`.

**Comment by tianon** [comment]
See also https://github.com/docker-library/wordpress/pull/8, https://github.com/docker-library/wordpress/pull/142, https://github.com/docker-library/wordpress/issues/147#issuecomment-266227769

**Comment by harobed** [comment]
> See also #8, #142, #147 (comment)

ok and what we do? This request are rejected?

I want to configure `FS_METHOD=direct` and I don't want mount `wp-config.php`. What I need to do?

**Comment by sheadscott** [comment]
I was able to work around this by creating a new Dockerfile: 
```
FROM wordpress:4.8.1-php7.1-fpm-alpine
COPY wordpress-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["wordpress-entrypoint.sh"]
CMD ["php-fpm"]
```
wordpress-entrypoint.sh is a copy of the official docker-entrypoint.sh where I added additional values to the list of uniqueEnvs. Just be sure to prefix them with WORDPRESS_ when passing them in like the other default uniqueEnvs. I'm not sure why they didn't include all the config variables in the entrypoint script by default.

**Comment by NathanTheGr8** [comment]
I would be interested to know what solution you found @harobed. I am currently trying to customize wp-config and I can't get wp-config.php mounted by itself #231 #135. So I am going to just mount /var/www/html to the host.

Strangely I can mount uploads.ini by itself.

**Comment by drzraf** [comment]
IMO there is too much complexity in virt/autodeploy WP images.
Part of this comes from tweaking `wp-config.php` to read from `getenv()`, read sensitive value from file, ...
Would be better if someone could open a bug upstream and provide a standard/consistent/simple/flexible and secure way to pass `WP_*` to vanilla WordPress tarball.

I think env' is good enough in most case (and can be given to the php-interpreter itself).
Some others (db password) may be obtained by reading a file whose path is obtained from the environment.

**Comment by tianon** [comment]
Closing in favor of https://github.com/docker-library/wordpress/pull/142. :+1:
