### ISSUE TITLE
Problem with docker-entrypoint.sh

### ISSUE THREAD

**Issue by GrzegorzDrozd** [docker-library/wordpress#208]
Hello.

Sed command to change newline characters in docker-entrypoint.sh file (https://github.com/docker-library/wordpress/blob/master/php7.1/fpm/docker-entrypoint.sh#L107) affects all files matching a wildcard in that directory including files that are not php nor from wordpress installation. It should at least have .php at the end or even better list all files that it is targeting.

Thank you and have a nice day.

**Comment by tianon** [comment]
Sorry for the delay!  You're speaking of `sed -ri -e 's/\r$//' wp-config*`?

https://github.com/docker-library/wordpress/blob/583768e49b56d478cc039671f25d3f73a949f2c6/docker-entrypoint.sh#L128

It _is_ limited to things which start with `wp-config`, which IMO is specific enough, but it probably wouldn't hurt to also include a `.php` on there if this is actually causing issues for someone.  Did this cause an issue in a real-world installation of WordPress?  What additional files were being stored in the WordPress root directory (especially matching that prefix), and why?  (Trying to understand the use-case which is affected by this.)

**Comment by tianon** [comment]
Closing since I'm still not sure I see a real-world issue here -- I wouldn't reject a PR which added `.php` to the end of that glob though!
