### ISSUE TITLE
Using different DB port

### ISSUE THREAD

**Issue by arkaitzmugica** [docker-library/wordpress#212]
Hi,

I can't find an environment variable to set up a port other than the default mysql's 3306. For instance, I would like to set up 4306.

How can I do that?

Thank you in advance for your help.

**Comment by luisnabais** [comment]
You didn't read the front hub page, didn't you?

"-e WORDPRESS_DB_HOST=... (defaults to the IP and port of the linked mysql container)"

in https://hub.docker.com/_/wordpress/

**Comment by tianon** [comment]
Indeed, this is easily solved by setting the appropriate environment variable. :+1:
