### ISSUE TITLE
ZipArchive is missing

### ISSUE THREAD

**Issue by alexander-zimmermann** [docker-library/wordpress#213]
Hi,

does it make sense to deploy is the ZipArchive in the image?

BR,
Alex

**Comment by mshayden** [comment]
It makes a great deal of sense because it is a prerequisite for all the useful backup plugins amongst other things.  Forgetting to deploy ZipArchive was a major oversight!

**Comment by kirlat** [comment]
I second that. Having ZipArchive enabled by default would be a must. So many plugins are using it!

**Comment by buchdag** [comment]
Ditto.

**Comment by ht512512** [comment]
Very useful to have ZipArchive.  Tried to create an image from wordpress using the following Dockerfile but did not work (any suggestions are welcome). 

FROM wordpress:latest
RUN apt-get update && apt-get install -y libz-dev && pecl install zlib zip
EXPOSE 80

**Comment by kirlat** [comment]
I managed to do it with
`
RUN apt-get install -y zlib1g-dev \
&& rm -rf /var/lib/apt/lists/* \
&& docker-php-ext-install zip
`
Please check my Dockerfile at [https://github.com/kirlat/docker-wp-dev-blaze-edition/blob/master/Dockerfile](https://github.com/kirlat/docker-wp-dev-blaze-edition/blob/master/Dockerfile). It has a bunch of other staff for Xdebug and WP CLI, and is based on `wordpress:php7.1-apache` but I believe the command above should work the same for any WP image variation.

Please let me know if you'll have any questions. I will be glad to help!

**Comment by erowley** [comment]
I am a newbie who is using docker-compose. The syntax for docker-compose is different from a normal dockerfile. Can instructions be given for how to update a running docker image? I would really prefer not to have to build my wordpress from scratch again just because I wanted to enable ZipArchive for Duplicator.

**Comment by kirlat** [comment]
Hi @erowley! Sorry for a late response, was extremely busy with work. I'm not 100% sure what do you mean by saying that you want to "to update a running docker image". Do you want to modify docker-compose.yml to include ZipArchive into it? Sorry, but this is not possible.

The only way to solve this I know of is to build a new image that will include ZipArchive. Luckily, you can base it on a WordPress image and add commands that will install any additional elements you want (i.e. ZipArchive). Would it work for you?

If it will, then you can create a Dockerfile with the following:
`FROM wordpress:latest

RUN apt-get update \
    && apt-get install -y --force-yes --no-install-recommends less libxml2-dev \
    && docker-php-ext-install soap \
    && rm -rf /var/lib/apt/lists/*

# Add PHP Zip Archive extension
RUN apt-get install -y zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
&& docker-php-ext-install zip`
and build an image from it.

Sorry, I'm a newbie to Docker, but was able to build an image with ZipArchive (and Xdebug with WP-CLI) for my own needs so I can share my experience, if that'll be helpful.

**Comment by blachawk** [comment]
How can we incorporate the same process of commands through docker-compose yml file?

**Comment by buchdag** [comment]
You can't, these modifications have to be made in the Dockerfile.

**Comment by blachawk** [comment]
Then what are the proper steps for installing wordpress, mysql and enabling php zip archiving in docker?

**Comment by tianon** [comment]
> Bottom line is you'll need a custom Dockerfile based on the official image and to build it a at some point.

This is spot on; thanks for the excellent summary and example `Dockerfile`, @buchdag. :heart:
(https://github.com/docker-library/wordpress/issues/213#issuecomment-337260184)

While needing the `zip` extension installed may be common, it's not _required_ for all users (or even any of the functionality in the default install, as far as I'm aware), and thus is outside the scope of the official image (if we were to expand the scope to include "commonly necessary modules", that becomes a slippery slope, since I'm not aware of an accepted authority we could point to for which modules are actually "commonly necessary").  Thanks!

**Comment by blachawk** [comment]
Please forgive me for asking until I understood it. The solution does work and also opens my eyes to seeing how Dockerfile can run actions on initial images to form custom images.  Thank you Thank you Thank you

**Comment by cirovladimir** [comment]
If you have a running container and would like to enable ZipArchive, you can bash into it and then running the commands suggested previously

```
docker exec -it <container_name> /bin/bash
apt-get update &&  apt-get install -y zlib1g-dev
docker-php-ext-install zip
/etc/init.d/apache2 reload
```

you must reload apache configuration which is done by the last command.

This way I was able to use duplicator plugin successfully.

**Comment by gerickt** [comment]
thanks! @cirovladimir  works like a charm

**Comment by joshcanhelp** [comment]
If anyone is getting `/bin/sh: apt-get: not found`, you need to switch the update/install to use `apk`. This worked for me:

```
# Make sure we can add packages
USER root

# Update and install, similar to the above but different command and package names
RUN apk update \
    && apk add zlib-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install zip

# Switch back to the right user to run the remaining commands in the Dockerfile
USER www-data
```

**Comment by 1beb** [comment]
+1 for including this
