### ISSUE TITLE
EXIF support is not preconfigured

### ISSUE THREAD

**Issue by quis** [docker-library/wordpress#216]
Hey,

A Wordpress site that I’ve built relies on using [`exif_read_data`](http://php.net/manual/en/function.exif-read-data.php) to  extract meta information from photos.

I understand that PHP needs to be configured with the `--with-exif` flag for this to work.

This is the _Configure Command_ section of `<?php phpinfo() ?>`’s output when I’m running my site from the Docker container:
```
'./configure' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--disable-cgi' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--with-apxs2' 'CFLAGS=-fstack-protector-strong '-fpic' '-fpie' '-O2'' 'LDFLAGS=-Wl,-O1 '-Wl,--hash-style=both' '-pie'' 'CPPFLAGS=-fstack-protector-strong '-fpic' '-fpie' '-O2''
```

How can I reconfigure PHP to have EXIF support enabled?

Sorry if this is the wrong place for this question, I’m really new to all this Docker stuff and still getting my head around it.

Thanks,
Chris

**Comment by quis** [comment]
OK, I figured it out.

EXIF support can be enabled by running the `docker-php-ext-install exif` command. This command only works when building the container.

I can’t modify the official container; the Docker way to do this (which is the part I didn’t understand) is to build my own container on top of the official one. Then when I build my own container I can run the command to enable EXIF support. Everything else is inherited from the official Wordpress container. So I made a file called `Dockerfile` containing this:

    FROM wordpress:latest
    
    RUN docker-php-ext-install exif
    
    ENTRYPOINT ["docker-entrypoint.sh"]
    CMD ["apache2-foreground"]


Then I ran this shell command to build an image from this file:  
`docker build -t wordpress-exif .`

Then it’s just a case of pointing the Docker compose file at my custom container, rather than the generic one. So in `docker-compose.yml` I changed `image: wordpress:latest` to `image: wordpress-exif`.

***

Hope that helps anyone else who’s stuck with this.

**Comment by tianon** [comment]
Is the exif functionality in WordPress itself or in a plugin?

**Comment by quis** [comment]
@tianon It’s in a plugin.

**Comment by tianon** [comment]
Ah ok -- thanks for confirming and glad you got it figured out!  I think we
should probably update the docs to mention this sort of thing if they don't
already. 😇

**Comment by quis** [comment]
Looks like they do already: https://github.com/docker-library/docs/blob/7edf26875db537de6c66f13aa3e97e8fb666e410/wordpress/README.md#adding-additional-libraries--extensions

But I didn’t find that content until just now, so it wasn’t very Google-able.

**Comment by tianon** [comment]
Ah, glad you got it figured out anyhow! :+1: :heart:
