### ISSUE TITLE
WordPress installation without language selection

### ISSUE THREAD

**Issue by mraspe** [docker-library/wordpress#217]
Hi,
I´m using Docker for Windows (17.03.1-ce-win5 (10743)) for local WordPress development.

Here my docker-compose file:

> version: '3'
> 
> 
> 
> 
> services:
> 
>   wordpress:
>     image: wordpress:4.7-php7.1-apache
>     links:
>       - mysql:mysql
>     ports:
>       - "80:80"
>     volumes:
>       - ./wp-content:/var/www/html/wp-content
>     environment:
>       WORDPRESS_DB_PASSWORD: secret
> 
>   mysql:
>     image: mysql:5.7
>     volumes:
>       - ./.data:/var/lib/mysql
>     environment:
>       MYSQL_ROOT_PASSWORD: secret

When I call docker compose to create the containers and then I start the WordPress installation (localhost), the selection for languages is not showing. I think, the volume has no permissons to write in wp-content folder(?) How can I fix it?

Mario

**Comment by gletellier** [comment]
I have the same problem. I have tested all tags with same result : 
It seems to skip language selection and goes directly to the "Welcome to the famous five-minute WordPress installation process" page.

If I continue installation in english, the language selection box is not available later in settings.

**Comment by gletellier** [comment]
Ok, it seems that for some reason, i have slow DNS resolution from inside my wordpress container, which cause timeout during attemps to connect to api.wordpress.com.
There is a fallback mechanism skiping language download when wordpress.com connection is not available.

Got it sorted by adding manual entry to container hosts file

echo "66.155.40.202 api.wordpress.org" >> /etc/hosts

**Comment by tianon** [comment]
Awesome, glad you figured out the root cause, @gletellier! :+1: :heart:

**Comment by protekshen** [comment]
@mraspe try to add language to values in your docker-compose file (If your languages folder in source code exist languages to they should be available in 'Settings/General/Site Language' in admin dashboard)

  ```
   volumes:
        - ./wp-content/languages:/var/www/html/wp-content/languages
```
