### ISSUE TITLE
Build Dockerfile fails

### ISSUE THREAD

**Issue by timkunze** [docker-library/wordpress#219]
Used default dockerfile from wordpress/php7.1/apache/Dockerfile (https://github.com/docker-library/wordpress/)
docker build -t pemedia/52docker .
Sending build context to Docker daemon 106.5 MB
Step 1 : FROM php:7.1-apache
7.1-apache: Pulling from library/php
1hp/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -
...
...
...
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
/bin/bash /usr/src/php/ext/opcache/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/src/php/ext/opcache -DPHP_ATOM_INC -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2   -c /usr/src/php/ext/opcache/ZendAccelerator.c -o ZendAccelerator.lo 
mkdir .libs
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/src/php/ext/opcache -DPHP_ATOM_INC -I/usr/src/php/ext/opcache/include -I/usr/src/php/ext/opcache/main -I/usr/src/php/ext/opcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -c /usr/src/php/ext/opcache/ZendAccelerator.c  -fPIC -DPIC -o .libs/ZendAccelerator.o
In file included from /usr/src/php/ext/opcache/ZendAccelerator.c:42:0:
/usr/local/include/php/ext/pcre/php_pcre.h:29:18: fatal error: pcre.h: No such file or directory
 #include "pcre.h"
                  ^
compilation terminated.
Makefile:193: recipe for target 'ZendAccelerator.lo' failed
make: *** [ZendAccelerator.lo] Error 1
The command '/bin/sh -c set -ex; 		apt-get update; 	apt-get install -y 		libjpeg-dev 		libpng12-dev         nano 	; 	rm -rf /var/lib/apt/lists/*; 		docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; 	docker-php-ext-install gd mysqli opcache' returned a non-zero code: 2
[ec2-user@ip-172-16-1-59 52docker]$ 

Complete build: https://pastebin.com/SbZZ6atq

**Comment by yosifkit** [comment]
Fixed by https://github.com/docker-library/php/pull/433 and is incoming to the Docker Hub once  https://github.com/docker-library/official-images/pull/2947 merges.
