### ISSUE TITLE
Apache config for /subfolder setup SSL -> NoSSL

### ISSUE THREAD

**Issue by clementparov** [docker-library/wordpress#222]
Hello !
First congrats for the great work, install and first setup in seamless!
I'm struggling pretty bad with my apache config though...
I installed wordpress to be used as http://www.mysite.com:8080 and everything works like a charm, but now I would like to put wordpress under httpS://www.mysite.com/blog/
So here is my apache config:

```
<IfModule mod_ssl.c>
  <VirtualHost *:443>
    SSLCertificateFile /etc/letsencrypt/live/mysite.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/mysite.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf

    ServerName www.mysite.com

    ServerAdmin contact@mysite.com
    DocumentRoot /var/www/mysite/public
    # My main site's folder

        <Directory "/var/www/mysite">
            AllowOverride All
            SetEnv COMPOSER_HOME "/usr/bin/"
            Order Deny,Allow
        </Directory>

        ProxyRequests Off
        SSLProxyCACertificateFile /etc/letsencrypt/live/mysite.com/fullchain.pem
        SSLEngine On
        SSLProxyEngine On
        ProxyPreserveHost On

        ProxyPass /blog/ http://0.0.0.0:8080/
        ProxyPassReverse /blog/ http://0.0.0.0:8080/
        ProxyPassReverse https://www.mysite.com/blog/ https://www.mysite.com/blog/

        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set X-Forwarded-Port "443"
  </VirtualHost>
</IfModule>
```

The issue I have is that when I connect to /blog/wp-admin it redirects me to /wp-admin, so the dashboard appears but all actions I do inside fail because all links are generated without /blog/ ...

**Do you have an idea why the redirection occurs?**

If it may help, here is my .htaccess in wordpress root folder (automatically generated by wordpress):

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /blog/
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /blog/index.php [L]
</IfModule>
```

**Second issue with this config:** I can load the landing page (https://www.mysite.com/blog/) but cannot access any other page. I get the following error 500:

Apache/2.4.10 (Debian) Server at www.mysite.com Port 80

This error must come from docker's apache (it's talking about port 80), I'm not sure how to access theses error logs...

Thanks in advance for your help !!

**Comment by faftoz** [comment]
Up @tianon @md5 @yosifkit  :)
I'd really appreciate your help and I'm sure it's nothing big and it can also help others !

**Comment by tianon** [comment]
You're trying to move your _existing_ blog over?  In my experience, changing the base URL of WordPress is a bit complicated, since WordPress itself tries to do redirects, and depending on how carefully your pages/posts are crafted, they might contain explicit links to the old location as well.

See https://codex.wordpress.org/Moving_WordPress%20 for more on this topic.
