### ISSUE TITLE
date.timezone warning in phpinfo()

### ISSUE THREAD

**Issue by Richard87** [docker-library/wordpress#224]
Hi, I get this warning when running phpinfo():

I have tested `wordpress:php7.1-fpm` and `wordpress` with the same warning

> Warning: phpinfo(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/info.php on line 2

**Comment by tianon** [comment]
Yes, this is an intentional feature of PHP -- if you wish to have a timezone set, you need to set one.  I believe WordPress handles this internally via `date_default_timezone_set` (as described in that warning), but I could be mistaken.  Either way, this is working-as-designed.  Thanks!
