### ISSUE TITLE
Support docker secrets for WORDPRESS_DB_PASSWORD

### ISSUE THREAD

**Issue by SKoschnicke** [docker-library/wordpress#225]
The [official MySQL docker image](https://hub.docker.com/_/mysql/) supports docker secrets to set the database password. This seems not to be possible with this image, or am I missing something?

If it is not yet available, I would implement it parallel to the MySQL image functionality (support for `WORDPRESS_DB_PASSWORD_FILE`)

**Comment by yosifkit** [comment]
Those should already exist: https://github.com/docker-library/wordpress/pull/186

**Comment by SKoschnicke** [comment]
You are right, thank you! How about a PR for adding this to the readme? :)

**Comment by tianon** [comment]
That'd be great!  The appropriate file for that would be
https://github.com/docker-library/docs/blob/master/wordpress/content.md.
:+1:

**Comment by SKoschnicke** [comment]
Sorry for the delay, added it.
