### ISSUE TITLE
providing a dev/test/wp-cli oriented WordPress Docker image

### ISSUE THREAD

**Issue by drzraf** [docker-library/wordpress#229]
Testing is probably now (and in a foreseeable future), the main usecase of WordPress Docker images.
`wp-cli` already manages auto-generation of phpunit-oriented WP-setup but [it's not the place](https://github.com/wp-cli/scaffold-command/issues/30) to maintain a related Docker image ATM.

The one [currently](https://github.com/wp-cli/scaffold-command/blob/master/templates/plugin-gitlab.mustache#L27) elected is named [tetraweb/php](https://github.com/TetraWeb/docker/blob/master/php/7.1/Dockerfile) which I found to be disappointing (not oriented for Wordpress, a overly heavy PHP configuration, a serious bug with Debian package and obviously _missing useful tools and useless others_ ...) and of course my_docker_image_is_[better](https://github.com/drzraf/ui-autotesting/blob/master/Dockerfile)™ ...

Subjectivity set aside, I think it would be safer and more efficient if an _official_ (= /wordpress/ namespaced) Docker image, suitable for developers/testers/themers, could be made available.

It means choosing a common (reduced?) set of useful tools

`<<<< wishlist <<<<<<`
* `git svn curl wget make sed zip unzip`: basic tools
* `composer`: obviously
* `phpunit` + `phpcs` (_PHP CodeSniffer_): the main reason for using the image in the first place
* `behat` + `mink` + `chrome-mink-driver` + `google-chrome-beta`: to run behavior test and is "lighter" than a `Selenium`-based setup
* `wp-cli`: ease so much most of the tasks, even more in an autonomous/continued-integration setup
* `xsltproc`: I found it quite useful when processing XHR dumps (used as fixtures for test-data initialization)
* `uglify-es`: (= uglifyjs) useful extra, esp. for themers and/or when a plugin|theme|demo end up being hosted fully, or partly in things like gitlab.io.

`>>>> wishlist >>>>>>`

Then comes the distribution to choose and the PHP extensions wishlist, which PHP versions are avaiable and whether an httpd daemon should be provided (or if `php -S` suffice)
And deciding if the image must come with WordPress installed or not, and which version.
(If the majority only test against the two last stable releases, then the answer is "yes")
Some developer may want to download a specific WP version to test against (`wp-cli scaffold` already help doing so) but providing a default installation wouldn't hurt while still improving dramatically the speed of the testrun.

**Comment by tianon** [comment]
The currently-existing `cli` variants of this image are based on `wp-cli` releases (see https://github.com/docker-library/wordpress/blob/648a2715dad185ad90155350b48f190b3f95ae21/php5.6/cli/Dockerfile, for example), and are the closest we plan to support to what you've described in this image.
