### ISSUE TITLE
sed: -e expression #1, char 80: unterminated `s' command

### ISSUE THREAD

**Issue by vshulev** [docker-library/wordpress#233]
Hi, I'm getting the following error logs when trying to run the container:
```sh
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html
sed: -e expression #1, char 80: unterminated `s' command
```
Tried with tags latest and 4.3. I've defined the following environment variables: `WORDPRESS_DB_HOST`, `WORDPRESS_DB_USER`, `WORDPRESS_DB_PASSWORD`, `WORDPRESS_DB_NAME`.

**Comment by yosifkit** [comment]
Do you have a new line in one of your environment variables?
