### ISSUE TITLE
chmod docker-entrypoint

### ISSUE THREAD

**Issue by mbruts** [docker-library/wordpress#236]
I had to run a chmod +x on line 58 to get this image to run...

ADD to Line 58 of Dockerfile:
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

**Comment by yosifkit** [comment]
If you use "git clone" rather than simply copying the files by hand, this script will already be executable. Otherwise, please do "chmod +x docker-entrypoint.sh" in your own local environment instead.
