### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by huegelc** [docker-library/wordpress#239]
Trying to pull latest image either with `docker compose up -d` and

```
# Dockerfile with SSL activated

FROM wordpress
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get dist-upgrade -y  --no-install-recommends -o Dpkg::Options::="--force-confold"   && \
    apt-get install -y  --no-install-recommends ssl-cert apt-utils && \
    rm -r /var/lib/apt/lists/* && \
    a2enmod ssl && \
    a2ensite default-ssl

COPY ./tests/test.sh /test.sh
RUN chmod 755 /test.sh

EXPOSE 80
EXPOSE 443
ENV DEBIAN_FRONTEND teletype
```

or `docker pull wordpress`and get:

```
latest: Pulling from library/wordpress
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by qmachard** [comment]
Hi @huegelc, I have the same problem, if I fix it easily I say you !

**Comment by tianon** [comment]
See also https://github.com/docker-library/rabbitmq/issues/188, https://github.com/docker-library/ruby/issues/159, https://github.com/c0b/docker-erlang-otp/issues/75, and https://github.com/docker-library/official-images/issues/3472.

**Comment by tianon** [comment]
Also, https://github.com/docker-library/oi-janky-groovy/commit/b63900158a3314eacd19a5f7a51c5a48343657fb which should help with this problem in the future.

**Comment by tianon** [comment]
I've also gone and triggered a build of `amd64/wordpress` right now.

**Comment by huegelc** [comment]
👍 can confirm it works again

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:

**Comment by jawadrehman** [comment]
getting the same error 
php7.1-apache: Pulling from library/wordpress
no matching manifest for linux/amd64 in the manifest list entries

**Comment by jeroenhendricksen** [comment]
In can confirm this error is present (again):

`docker pull wordpress:4-php5.6-apache
4-php5.6-apache: Pulling from library/wordpress
no matching manifest for linux/amd64 in the manifest list entries`

docker --version
Docker version 18.01.0-ce, build 03596f5

uname -a
Linux HOSTNAME 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tianon** [comment]
@jeroenhendricksen yes, please stop posting it everywhere and actually read the contents of https://github.com/docker-library/official-images/issues/3835 instead -- it's building, and will be available soon

**Comment by jeroenhendricksen** [comment]
@tianon This is the first time and place I'm posting this, so I'm not sure what you mean by "stop posting it everywhere", but I've read the thread and I'll await the build. Thank you for your reply though.

**Comment by tianon** [comment]
Sorry, posted a little too fast -- that part of the comment was intended for @jawadrehman who has cross-posed; my apologies.

Feel free to track https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/wordpress/ for build availability.

**Comment by jawadrehman** [comment]
Sorry , didn't follow through the issue posted ..
Thanks for the update

On 18 Jan 2018 21:29, "Tianon Gravi" <notifications@github.com> wrote:

Sorry, posted a little too fast -- that part of the comment was intended
for @jawadrehman <https://github.com/jawadrehman> who has cross-posed; my
apologies.

Feel free to track https://doi-janky.infosiftr.ne
t/job/multiarch/job/amd64/job/wordpress/ for build availability.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/docker-library/wordpress/issues/239#issuecomment-358787550>,
or mute the thread
