### ISSUE TITLE
Enable PHP7.X-FPM Unix Sockets?

### ISSUE THREAD

**Issue by kawaii** [docker-library/wordpress#245]
Using the `docker-php-ext-install sockets` command you can enable access to the PHP API via a Unix socket file as opposed to the usual method, over TCP. Would it be possible to get this as an option in the form of environment variable so that I can mount the socket file between my WordPress and nginx Docker containers and eliminate the TCP overhead? :slightly_smiling_face:

**Comment by tianon** [comment]
I'd recommend writing a short `Dockerfile` which enables that extra extension, something like this:

```dockerfile
FROM wordpress:php7-fpm
RUN docker-php-ext-install sockets
```

Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with Unix sockets enabled by default. :+1:

**Comment by kawaii** [comment]
@tianon you're a genius, thanks. :slightly_smiling_face:
