### ISSUE TITLE
Issue with wp-content/uploads setting owner to 999 instead of www-data

### ISSUE THREAD

**Issue by pragmaticivan** [docker-library/wordpress#246]
### Dockerfile
```
FROM wordpress:4.8.2-php7.1-apache

ADD ./wp-content/plugins /var/www/html/wp-content/plugins
ADD ./wp-content/themes /var/www/html/wp-content/themes
```

<img width="477" alt="screen shot 2017-10-30 at 11 29 27 am" src="https://user-images.githubusercontent.com/301291/32188643-a5d9386e-bd65-11e7-8a89-bdefb5bc1c15.png">

Causing an issue on file uploading:

<img width="1007" alt="screen shot 2017-10-30 at 11 30 09 am" src="https://user-images.githubusercontent.com/301291/32188695-c23eb2ea-bd65-11e7-849f-e3745bb6d467.png">

Tested on Docker for mac and ubuntu versions

Local volume: `/var/www/html/wp-content/uploads`

**Comment by tianon** [comment]
I think you'll need to give us a bit more information about how you're running the image resulting from building this `Dockerfile` -- do you include any bind mounts or external volumes, for example?

**Comment by pragmaticivan** [comment]
Hi @tianon thanks, just updated with the volume I'm currently using. It's pretty much a custom image adding a theme/plugins and running that on docker swarm as a container.

**Comment by tianon** [comment]
Have you tried doing a `chown` to `33:33` on the directory?  The image won't have created that if it already existed, and won't touch the permissions after it exists, so my hunch is that if you simply correct the permissions manually, things should start working again.

**Comment by pragmaticivan** [comment]
I thought about changing the ownership, but doesn't seems to be the right approach for general usage.

The current image downloads a wordpress project that doesn't come with a upload folder. 

For me, the right approach would be creating a upload folder on this docker image with the right user so any general user would not have issues with that anyway.

`uploads` folder seems to be a really big deal for wordpress users, since generally you would use that with a volume.

**Comment by tianon** [comment]
The reason we don't do anything special with `uploads` alone is because the entire _install_ is considered by upstream to be mutable state -- WordPress expects to self-update (and IMO anyone who doesn't allow it to do so these days is asking for trouble), so we simply recommend that users instead make the entire install a directory and be done with it.  If you'd like a fresh install from an image to include pre-installed themes or plugins, simply add them to the source directory in `/usr/src/wordpress` (which is what gets copied into `/var/www/html` at runtime).

**Comment by pragmaticivan** [comment]
Hey @tianon that explains a lot when you talk about the "whole mutable state", that makes sense for me now. Thanks for you time o/

**Comment by reachdevelopers** [comment]
My issue is that I can't edit any files inside wp-content on Ubuntu and if I changed permissions to the wp-content than adding plugins or changing themes gives me some ftp access credentials. Hope this makes sense.

**Comment by tianon** [comment]
@reachdevelopers if you need to modify for development purposes, I'd recommend using `--user` to run the `wordpress` container explicitly as your Ubuntu UID/GID (which is probably `1000:1000`)

If that doesn't work, try doing `APACHE_RUN_USER=your-user` and bind-mounting `/etc/passwd` and `/etc/group` read-only:

```console
$ docker run ... -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -e APACHE_RUN_USER=reachdevelopers -e APACHE_RUN_GROUP=reachdevelopers ... wordpress ...
```

**Comment by reachdevelopers** [comment]
sorry, I new at docker and I run docker docker-compose up where do I use --user? Can you porvide me with an example?

**Comment by tianon** [comment]
https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

**Comment by electrovladyslav** [comment]
Hello, @tianon, hope you can help my issue - same as @reachdevelopers : no possible to install any plugin to Wordpress (apparently change content of `wp-config`)
I've made up image from    `FROM cvla/nginx-light:first` and run it like container with volume `./wp-content:/usr/share/nginx/html/wp-content`
Inside of container I see this picture :
![image](https://user-images.githubusercontent.com/7540757/41241236-19159f58-6da5-11e8-826a-d0d131a55b46.png)
So everybody can read, write and enter dir `wp-content`. So what is the problem with access?
I've tried to run container with my system user and passwords files, but can't start container.
Anyway, why I should put my local passwords inside of container?
I'm using Linux Mint 18.2 Sonya and Docker version 18.03.0-ce, build 0520e24
