### ISSUE TITLE
Question/ Help - AH00169: caught SIGTERM, shutting down

### ISSUE THREAD

**Issue by barundel** [docker-library/wordpress#261]
Hey

I'm new to containers so sorry if this is me being stupid. 

I am trying to run wordpress:php7.1-apache on AWS ECS with RDS, I have a docker file:

```
FROM wordpress:php7.1-apache

ENV WORDPRESS_DB_USER administrator
ENV WORDPRESS_DB_PASSWORD password
ENV WORDPRESS_DB_NAME user
ENV WORDPRESS_DB_HOST wordpresstest.BLAH.eu-west-1.rds.amazonaws.com:3306
```

which i build with just the docker build command. I push this onto ECS and everything is fine for a time, I can install wordpress and the site works.

However after about 3 mins the container shuts down with:

`[Fri Dec 15 22:47:29.945785 2017] [mpm_prefork:notice] [pid 1] AH00169: caught SIGTERM, shutting down`

ECS notices the container has died and brings back another one which works for about 3 mins, ive tried a few variations of the image (php version, alpine etc) changed the CPU, RAM without success. 

Im running another container image (php:7.0-apache) with just a static site running which is working fine. 

I hope there is something I am fundamentally missing and you can point me in the right direction?

**Comment by yosifkit** [comment]
I'm not that familiar with ECS, but perhaps it has a default health check or something?  I really am unsure where a random `SIGTERM` would be coming from.

**Comment by barundel** [comment]
Hi

After much messing it was the health check of the target group, for anyone that finds this via google as a quick win I created a healthy.html and copied it into /var/www/html/ as part of the docker build, I then set the path of the health check to that file, not good if wordpress itself dies but it will spawn another container if something happens to apache.
