### ISSUE TITLE
Support SSL connection to MySQL

### ISSUE THREAD

**Issue by edevil** [docker-library/wordpress#264]
I see no place to enable SSL while connecting to MySQL. In my case I can't connect because of this.

```
MySQL Connection Error: (9002) SSL connection is required. Please specify SSL options and retry.
```

**Comment by tianon** [comment]
See https://core.trac.wordpress.org/ticket/28625 and https://wordpress.org/plugins/secure-db-connection/ (this is a limitation of WordPress itself).
