### ISSUE TITLE
Can't use SSL behind nginx reverse proxy

### ISSUE THREAD

**Issue by 0Kills** [docker-library/wordpress#265]
Discovered my own workaround, but if the container is running behind nginx serving up the SSL certificate, it is not aware it is using an SSL cert and writes all stylesheets and form elements using http://. Browsers disable mixed content, so it shows it with no styles.

Workaround for me was to make is_ssl() in wp-includes/load.php always return true.

**Comment by oonnnoo** [comment]
This is the same as #251

**Comment by tianon** [comment]
See the following block of code (and also http://codex.wordpress.org/Administration_Over_SSL#Using_a_Reverse_Proxy).  Make sure your NGINX proxy is sending the appropriate value for the `X-Forwarded-Proto` header.

https://github.com/docker-library/wordpress/blob/583768e49b56d478cc039671f25d3f73a949f2c6/docker-entrypoint.sh#L130-L139
