### ISSUE TITLE
Change URL to access WP

### ISSUE THREAD

**Issue by miguemiguemigue** [docker-library/wordpress#275]
I've migrated a WordPress site to Docker container.

There are coworkers coding plugins for the site, but their local environment is Apache. So, their code contain the URI `/wordpressName/`, because the site is one of the projects of the Apache server. This is a problem, because the Docker container expose the site in `/` and everytime I put a plugin in my Docker context I have to replace the URI from `/wordpressName/` to `/`.

Inside the WordPress docker image, there is an Apache server too. So, Is there any way to change the endpoint of the site in the Docker image from `/` to `/wordpressName/`?

Thanks in advance

**Comment by yosifkit** [comment]
Oh, just a subdirectory? See https://github.com/docker-library/wordpress/issues/221#issuecomment-356457710
