### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [docker-library/wordpress#276]
When running `docker pull wordpress` or `docker pull wordpress:latest`, or really any currently tagged version, I get an the error in the title.

```
% docker pull wordpress                                      
Using default tag: latest
latest: Pulling from library/wordpress
no matching manifest for linux/amd64 in the manifest list entries
%
```

Seems similar to #239

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/3835.

**Comment by DougBeney** [comment]
Was just about to open this same issue. 

@tianon Very interesting. Is there any workaround I could do right now to get around this issue - even if it means using a previous verison?

**Comment by tianon** [comment]
https://github.com/docker-library/repo-info/tree/master/repos/wordpress/remote :wink:

(use either an explicit three-part version tag like `wordpress:4.9.1` or grab a sha256 digest from that directory or the history of the files there)

**Comment by DougBeney** [comment]
You rock! Thanks for the super fast reply too.

**Comment by JinGangRed** [comment]
@tianon Your answer is very nice.And it works for me
