### ISSUE TITLE
media.php error

### ISSUE THREAD

**Issue by RicoOtto** [docker-library/wordpress#278]
Hello, whenever I install Wordpress in docker I get this error whenever images get loaded.

<img width="1324" alt="schermafbeelding 2018-01-29 om 13 23 06" src="https://user-images.githubusercontent.com/34710995/35510353-0b67039e-04f8-11e8-90fc-19fa52230109.png">

**Comment by andreccosta** [comment]
Also had this issue come up recently. Looks like it was [acknowledged upstream](https://core.trac.wordpress.org/ticket/43201) and should be fixed in 4.9.5.

**Comment by yosifkit** [comment]
Thanks @andreccosta for the information.  Closing since this is an upstream bug and will be fixed in the next release.
