### ISSUE TITLE
Allow local access to the wordpress folder in the container

### ISSUE THREAD

**Issue by stormwild** [docker-library/wordpress#285]
Currently there is no local access to the wordpress files/folder in the container. This prevents an editor/IDE from navigating to the WordPress code that may be referenced when developing themes or plugins. For example when building a custom nav walker the code would need to extend the `Walker_Nav_Menu` in the wordpress code. A developer may want to access the class in the wordpress folder in the container.

Open to other suggestions aside from allowing for locally mounted wordpress.

**Comment by yosifkit** [comment]
The only answer to access container files from your host is to mount a local empty directory to the proper path in the container and to have it filled with WordPress by the entrypoint script.

**Comment by stormwild** [comment]
Thanks @yosifkit will work it out.
