### ISSUE TITLE
Disable auto install of themes and plugins

### ISSUE THREAD

**Issue by jevonearth** [docker-library/wordpress#288]
When running this wordpress docker image, it appears to automatically install the akistmet and hello dolly plugins, and a few themes into `plugins/` and `themes/`.

How can we disable this behavior?

**Comment by yosifkit** [comment]
That is part of the default WordPress install from upstream. We don't add or remove from their tarball.

**Comment by jjrdevspace01** [comment]
wordpress also provide no-content distros which you could offer to avoid this
