### ISSUE TITLE
No new images in Docker registry

### ISSUE THREAD

**Issue by limestreet** [docker-library/wordpress#296]
There are still only 4.9.4 images available in Docker registry: https://hub.docker.com/_/wordpress/
May I know when 4.9.5 will be built?

**Comment by tianon** [comment]
From https://github.com/docker-library/wordpress/blob/master/README.md:

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/wordpress" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/wordpress), especially [PRs with the "library/wordpress" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fwordpress). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

We'll get a PR up today.  In the meantime, I'd recommend leaving the built-in Wordpress auto-update functionality enabled.
