### ISSUE TITLE
Use MYSQL_ROOT_PASSWORD to create new user that has access only to the DB of this container

### ISSUE THREAD

**Issue by martinvirtel** [docker-library/wordpress#300]
If several containers share a mysql instance and use a root password, they can read and write each others data because the root passwort and username are used inside the wp_config.php.

The root password could instead be used to create a "this database only" user when the database is created.

**Comment by tianon** [comment]
Honestly, the code in https://github.com/docker-library/wordpress/blob/5174f87ddfa7382eb2f8c9c2e172fe2e1f498fd7/docker-entrypoint.sh#L235-L275 is a last-ditch effort to try and create the database if it doesn't exist and the user has access to do so (which is a pretty slim scenario).  This is definitely something that ought to be done separately, and the `mysql` image (and the various forks like `mariadb` and `percona`) provide environment variables to assist in doing so (and even setting `root`'s password to something random so it gets lost and nobody has `root` access to the database anymore once it's no longer necessary).
