### ISSUE TITLE
Should install zip

### ISSUE THREAD

**Issue by taoyouh** [docker-library/wordpress#302]
The new "export user data" function in 4.9.6 requires zip function to work, but the default installation doesn't include zip.
I think we should install zip in the image.

**Comment by tianon** [comment]
I've managed to reproduce with a stock WordPress setup:

> An error occurred while attempting to export personal data.
> Unable to generate export file. ZipArchive not available.

I'll make a PR shortly. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/wordpress/pull/304 :+1:
