### ISSUE TITLE
Error logs don't show in stdout

### ISSUE THREAD

**Issue by roopemerikukka** [docker-library/wordpress#311]
I'm getting only access logs to the stdout and at least I assume that the error logs should be shown in there also. Im using custom image `FROM wordpress:php7.1-fpm-alpine` which doesn't touch to any logging options (at least not purposely). The image that I'm using is: https://github.com/bond-agency/docker-wpbp-wordpress

Is there something wrong with the configuration of that image or do I have to turn the logging on separately?

**Comment by wglambert** [comment]
In the Dockerfile `error_log` and `access.log` are redirected to `stderr` not stdout.

https://github.com/docker-library/php/blob/master/7.2/alpine3.7/fpm/Dockerfile#L191
> && { \
> 		echo '[global]'; \
> 		echo 'error_log = /proc/self/fd/2'; \
>                 . . . 
> 		echo '[www]'; \
> 		echo '; if we send this to /proc/self/fd/1, it never appears'; \
> 		echo 'access.log = /proc/self/fd/2'; \
> 		. . .
> 	} | tee php-fpm.d/docker.conf \

For why this is: https://github.com/docker-library/php/issues/358#issuecomment-271033464
>php-fpm likely closes STDOUT as part of its own startup routines.

**Comment by wglambert** [comment]
Issue seems resolved so going to close

**Comment by pentago** [comment]
Thing is, I don't use Docker, rather Docker container in Kubernetes. How does that impact PHP-FPM logging?

**Comment by wglambert** [comment]
It shouldn't? You're just using `kubectl logs` instead

For some more info about this nuance see https://github.com/docker-library/php/issues/811#issuecomment-481029692
