### ISSUE TITLE
Can the wordpress docker files and every software it installs be used for commercial purpose ?

### ISSUE THREAD

**Issue by user-mk** [docker-library/wordpress#325]
The WordPress docker files installs many software including WordPress, PHP, some php extensions and it also uses php docker file such as `php:5.6-apache` which installs many software for it to run.

My question is can those software that those docker images are installing be used to create WordPress Themes and Plugins for commercial purpose ?

Please note that i will be selling the WordPress themes and plugins that i create. I will not be selling the docker files or any software the docker file installs.

**Comment by wglambert** [comment]
Section about licensing in the [docs](https://github.com/docker-library/docs/tree/master/wordpress#license)

Wordpress license https://wordpress.org/about/license/
Licenses from packages in `wordpress:4.9.8-apache` https://github.com/docker-library/repo-info/blob/master/repos/wordpress/local/php7.2-apache.md#dpkg-deb-based-packages
