### ISSUE TITLE
Pulling wordpress:cli fails - Jenkins build seems to be broken

### ISSUE THREAD

**Issue by phillip-elm** [docker-library/wordpress#329]
When I try to create a container using `wordpress:cli`, I receive the following error:

`ERROR: No matching manifest for unknown in the manifest list entries.`

I've tried this on both my Mac's installed version of docker, and on a Ubuntu 18.04 VM on my Mac, after having restarted docker and having cleared the cache.

Pulling other images works fine.

I do notice that the Jenkins build that started on August 27 has now been running for 1 day and 3 hours (at the time of writing) - and it seems to be blocking subsequent builds. I'm still learning the inner workings of Docker - but could this be the cause?

- [Jenkins Overview](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/wordpress/)
- [Build 109 (currently ongoing)](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/wordpress/109/)

**Comment by phillip-elm** [comment]
Update: Having another look at this, there seems to be some correlation between this issue and Jenkins being stuck for the amd64 and i386 platforms. 

Running docker in experimental mode and pulling `arm64` or `ppc64le` with the following works:

```
docker pull wordpress:cli --platform linux/arm64
docker pull wordpress:cli --platform linux/ppc64le
```

While these do not:

```
?> docker pull wordpress:cli --platform linux/amd64
no matching manifest for linux/amd64 in the manifest list entries

?> docker pull wordpress:cli --platform linux/i386
no matching manifest for linux/386 in the manifest list entries
```

**Comment by tianon** [comment]
Crap, this is the same issue as https://github.com/docker-library/official-images/issues/4789; I'm going to close this to track both issues there (as a catch all for this infra issue).  Sorry for the trouble!
