### ISSUE TITLE
Entrypoint.sh Wordpress Copy Process Skipping wp-content when mounted.

### ISSUE THREAD

**Issue by JD1337** [docker-library/wordpress#344]
I was hoping to be able to use the standard wordpress image to preinstall themes and plugins by mounting the wp-content folder that contains the themes I wanted into the /usr/src/wordpress/wp-content/ folder.

The idea was that this would get copied across as per normal during the entrypoint.sh

tar cf - --one-file-system -C /usr/src/wordpress . | tar xf -

however, because of the --one-file-system option tar is ignoring the mounted volume with the following verbose error

tar: ./wp-content/: file is on a different filesystem; not dumped 

simply removing the option appears to work correctly. Was there a reason this was included? Can we remove it?

tar cf - -C /usr/src/wordpress . | tar xf -

**Comment by wglambert** [comment]
https://github.com/docker-library/wordpress/issues/341
Plugins go in `/usr/src/wordpress/wp-content/plugins`
Themes go in `/usr/src/wordpress/wp-content/themes`

```Dockerfile
FROM wordpress

ADD ./wordpress_theme /usr/src/wordpress/wp-content/themes/wordpress_theme
```

I'll go make a docs PR

**Comment by wglambert** [comment]
I've noticed that the `--one-file-system` does cause some problems as well; notably when looking at the theme in the webui `themes` tab I see `Stylesheet is missing.`. So mounting instead to `/var/www/html/wp-content/themes/` will mount the files correctly.

**Comment by tianon** [comment]
Doh, not sure why we used `--one-file-system` in the first place -- IMO removing that makes sense. :+1:
