### ISSUE TITLE
Unable to start container in kubernetes because of docker-entrypoint.sh

### ISSUE THREAD

**Issue by BlocML** [docker-library/wordpress#354]
Error: failed to start container "web": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH"

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by wglambert** [comment]
See also https://github.com/docker-library/php/issues/695
