### ISSUE TITLE
Exit code 2

### ISSUE THREAD

**Issue by Andreypnfrv** [docker-library/wordpress#357]
I'm trying to run docker-compose with wordpress container. MySQL starts ok, but wordpress container exits with code 2.

Here's the text of docker-compose files:

**docker-compose.yml**
`
version: "3"

services:

    mysql:
        image: mysql:5.7
        volumes:
           - ./mysql/data:/var/lib/mysql
        env_file:
            - .env

    wordpress:
        image: wordpress:latest
        volumes:
          - ./wp/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
          - ./wp/themes/:/var/www/html/wp-content/themes/
          - ./wp/plugins/:/var/www/html/wp-content/plugins/
          - ./wp/includes/:/var/www/html/wp-includes/
        env_file:
            - .env
        depends_on:
            - mysql
        links:
            - mysql:mysql
`

**docker-compose.dev.yml**
`
version: "3"

services:

    wordpress:
        volumes:
          - ./wp/phpinfo.php:/var/www/html/phpinfo.php
        ports:
          - 80:80
          - 443:443
`
**command:**
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d && docker-compose logs -f 

**some extra info**
If I try _docker-compose run wordpress bash_ and then _ls_ I see that _/var/www/html/_ contains only volumes

I also noticed that if i remove volumes - everything starts ok and wordpress is copied to folder. Than I can add volumes and everything is ok. So this problem persists only on the container creation

**Comment by wglambert** [comment]
Your volume mount `- ./wp/includes/:/var/www/html/wp-includes/` is overwriting the contents of that directory, it doesn't populate bind-mounted volumes, only "named" volumes such as the docker declared ones are populated from a directory.

You can either put all necessary files in that host directory or use a named volume
