### ISSUE TITLE
Update to 5.0.1

### ISSUE THREAD

**Issue by joeldeteves** [docker-library/wordpress#359]
Guys, my understanding is that this is a big security release and it's been out for quite a few days. Just wondering when it will be pushed to the Hub as I see it's already been merged here?

**Comment by edden87** [comment]
I needed 5.0.1 due to security update.

**Comment by zhipu123** [comment]
It looks like the CI already publish tags 
https://doi-janky.infosiftr.net/job/update.sh/job/wordpress/3295/console
just don't know why there are no 5.0.1 tags on docker-up

**Comment by zhipu123** [comment]
There's no PR to add WordPress 5.0.1 official images
https://github.com/docker-library/official-images/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Alibrary%2Fwordpress+
