### ISSUE TITLE
Allow PHP error logs to be switched on

### ISSUE THREAD

**Issue by mattgibson** [docker-library/wordpress#36]
I ran into an issue with the image cropping not working for certain files. No way to get PHP errors back, so no idea if there's a missing library. Need a way to set error login to max in php.ini and/or wpconfig.php

**Comment by tianon** [comment]
There's nothing in the `docker logs` for the container?  You should be able to inject files into `/usr/local/etc/php/conf.d/` to set the relevant PHP error flags (or you could put them in `.htaccess`).

**Comment by yosifkit** [comment]
This looks to be solved.

Closing old issue, if you feel this was closed in error please let us know.
