### ISSUE TITLE
enable mod_remoteip for Apache

### ISSUE THREAD

**Issue by rmoriz** [docker-library/wordpress#365]
I'm surprised how hard this image and `php:7.3-apache` makes it for one to enable `mod_remoteip` given that so many people are deploying sites behind an ingress-proxy or service (think of cloudflare).

This should be possible without having to rebuild the base image(s) IMHO.

**Comment by yosifkit** [comment]
You don't have to rebuild the php-apache image.  It is the regular apache2 from Debian, so you can just use `a2enmod`.

You can either make a an image `FROM` the WordPress (or php-apache) you desire and `RUN a2enmod remoteip`. Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` WordPress with the required modifications.

Or adjust the command to do that on startup

```console
$ docker run ... wordpress:5 sh -c 'a2enmod remoteip && exec docker-entrypoint.sh apache2-foreground'
# or php image directly
$ docker run ... php:7.3-apache sh -c 'a2enmod remoteip && exec apache2-foreground'
```

**Comment by rmoriz** [comment]
As you pointed out, it requires additional image building. You also missed the apache-configuration part. IMHO this should be a "core feature" given that so many people deploying containers in load-balanced environments like Swarm and K8s which all run into that problems aswell.
