### ISSUE TITLE
Unable to run Wordpres + PHP FPM with non-root user

### ISSUE THREAD

**Issue by lucabarbosa** [docker-library/wordpress#368]
```shell
$ docker --version
Docker version 18.06.1-ce, build e68fc7a

$ docker-compose --version
docker-compose version 1.23.2, build 1110ad01

Debian 9
```
Hello, everybody!

I need to run a container with Wordpress + PHP FPM in a non-root user, however I can not do it.

Folloy my code bellow:

```shell
$ docker run --rm --name test -it --user 33:33 wordpress:5.0.3-php7.3-fpm
WordPress not found in /var/www/html - copying now...
tar: ./license.txt: Cannot open: Permission denied
tar: ./index.php: Cannot open: Permission denied
tar: ./wp-signup.php: Cannot open: Permission denied
tar: ./wp-content: Cannot mkdir: Permission denied
tar: ./wp-content: Cannot mkdir: Permission denied
tar: ./wp-content/themes: Cannot mkdir: No such file or directory
tar: ./wp-content: Cannot mkdir: Permission denied
............. and keeps going
```

When I remove user flag, it's runs normally, but when I set a non-root user, it doesn't run.

If I use an image only of PHP FPM and set the user flag, it performs correctly, but when I use the image of Wordpress with PHP FPM and the user flag, it breaks.

Can anyone help me?

**Comment by tianon** [comment]
Great catch!  I've filed https://github.com/docker-library/php/pull/787, which should fix it. :+1:
