### ISSUE TITLE
why do not use ldap plugin

### ISSUE THREAD

**Issue by kamihicouki** [docker-library/wordpress#37]
i want use to Active Directory Integration Plugin.

but, show the following at plugin setting page.
same even if installed php5-ldap module.
please help

```
 ATTENTION: You have no LDAP support. This plugin won´t work.

You must install or enable LDAP support in PHP. Further information: http://php.net/manual/en/book.ldap.php at the pluginsetting page 
```

**Comment by md5** [comment]
You'll need to create your own image based on this one that does a `RUN docker-php-ext-install ldap`. Installing the `php5-ldap` package doesn't affect the PHP installation used by the [`php`](https://github.com/docker-library/php) base image that `wordpress` is based on.

I thought the `docker-php-ext-install` stuff was documented somewhere, but I can't find it at that moment.

**Comment by kamihicouki** [comment]
oh, thnaks.

i have try, create original images.

thank you for responding to my issue.

**Comment by kamihicouki** [comment]
Close.

at
https://github.com/kamihicouki/wordpress

**Comment by hurrycaine** [comment]
This is the number 1 hit on google when searching wordpress docker ldap...
The previous link no longer works... putting the answer here.

```
RUN \
    apt-get update && \
    apt-get install libldap2-dev -y && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install ldap
```
