### ISSUE TITLE
Container terminates before database is up

### ISSUE THREAD

**Issue by teeling** [docker-library/wordpress#378]
I'm trying to run Wordpress on Amazons ECS, where I have a task that starts a wordpress and a mariadb container. The problem is that wordpress shuts down before my mariadb is up and ready for connections.
I can see in the docker-entrypoint.sh that it tries 10 times before it shuts down. Would it make sense to be able to increase the 10 times to something more, in case the database takes a while to start up?

**Comment by tianon** [comment]
It probably just makes sense to make it non-fatal instead (and throw a suitably large warning that it wasn't able to connect and thus could not ensure that the database is created).
