### ISSUE TITLE
restart host server  container cannot start again

### ISSUE THREAD

**Issue by oliveagle** [docker-library/wordpress#38]
restart host machine,   start wordpress_mysql ok.  but when to start / restart wordpress container directly. log says:    

     $ docker start 84c63ccfcde0
     $ docker logs --tail=10 

      ...
     httpd (pid 1) already running

docker process

    84c63ccfcde0        wordpress:4                 "/entrypoint.sh apac   27 hours ago        Exited (0) 22 seconds ago                       wordpress           
    6bdd37b885fa        mysql:5                     "/entrypoint.sh mysq   27 hours ago        Up 3 minutes                3306/tcp            wordpress-mysql

**Comment by oliveagle** [comment]
thx. 
btw, is this the latest version ? 

    wordpress           4.1.0               c615b3914d6b        4 days ago          461 MB
    wordpress           latest              c615b3914d6b        4 days ago          461 MB

this issue exists on version 4.1.0    

update images in docker repository would be great. thx a lot :)

**Comment by yosifkit** [comment]
It seems that we did not update the `CMD` in wordpress to reflect the pid-file cleaner (fixing this in #39).
