### ISSUE TITLE
PHP error log

### ISSUE THREAD

**Issue by homerjam** [docker-library/wordpress#390]
It'd be useful to have the PHP error log available via `docker logs`, [this suggestion](https://github.com/docker-library/php/issues/212#issuecomment-204817907) may be effective.

**Comment by wglambert** [comment]
The images don't load a php configuration file by default, they do come with the two default "sample" and "production" `.ini`'s, but by default one of them isn't chosen. https://github.com/docker-library/docs/tree/master/php#configuration
```console
$ docker run --rm wordpress php -i | grep "Loaded Configuration File"
Loaded Configuration File => (none)

$ docker run --rm wordpress:fpm php -i | grep "Loaded Configuration File"
Loaded Configuration File => (none)
```
