### ISSUE TITLE
APACHE_RUN_USER / APACHE_RUN_GROUP

### ISSUE THREAD

**Issue by jucajuca** [docker-library/wordpress#391]
this two environment variables should also be mentioned in the main page under "Running as an arbitrary user"

APACHE_RUN_USER 
APACHE_RUN_GROUP

**Comment by yosifkit** [comment]
Rather than repeating what is on the PHP page, we link to the PHP docs: 

> See [the "Running as an arbitrary user" section of the `php` image documentation](https://hub.docker.com/_/php/).
>
> \- [Arbitrary User on Wordpress Docker Hub docs](https://github.com/docker-library/docs/tree/c9df6fb417ff60180f6a98816e0309bca7b3a05d/wordpress#running-as-an-arbitrary-user)
