### ISSUE TITLE
Longer retry timeout

### ISSUE THREAD

**Issue by borekb** [docker-library/wordpress#392]
Currently, the startup scripts tries to connect to MySQL for 30 seconds:

https://github.com/docker-library/wordpress/blob/acd229d6d638566a3ccd921d20075182db9e1185/php7.2/apache/docker-entrypoint.sh#L255-L266

On older hardware, that's not always enough, especially if MySQL starts from a clean state (no volume created).

It would be great to have a way to configure the timeout, or maybe just prolong it: it would not affect the majority of users and those with slower hardware would just wait a bit longer.

**Comment by borekb** [comment]
For reference, the current code has been implemented in #48 and a similar issue has been reported in #110.

**Comment by tianon** [comment]
See #386

**Comment by tianon** [comment]
Closing in favor of #386.
