### ISSUE TITLE
Add no-content images

### ISSUE THREAD

**Issue by dingo-d** [docker-library/wordpress#396]
Can you add images that won't add the content (default plugins and themes) when pulling the docker image?

There is already a link for this and wp-cli has this option.

For instance the latest one is

```
https://downloads.wordpress.org/release/wordpress-5.1.1-no-content.zip
```

**Comment by yosifkit** [comment]
We are unlikely to add a variant that would almost double the current number of images.

**Comment by dingo-d** [comment]
Yeah, I get it. Thanks for the info 👍
