### ISSUE TITLE
A tiny translate issue in official theme Twenty Sixteen version 1.9

### ISSUE THREAD

**Issue by isnanx** [docker-library/wordpress#398]
Extra letter y here. XD
![wp](https://user-images.githubusercontent.com/49234985/56748974-669ec980-67b3-11e9-9e3f-5447632e3359.PNG)

**Comment by wglambert** [comment]
You're probably wanting https://wordpress.org/support/theme/twentysixteen/
This repo is for the Docker image of WordPress, and that theme is just something that comes default with a WordPress install

**Comment by isnanx** [comment]
Ok, thanks. @wglambert
