### ISSUE TITLE
override htaccess with rancher nfs

### ISSUE THREAD

**Issue by mkrierQape** [docker-library/wordpress#400]
Hello,

i want run this image with a multisites wordpress configuration, for this it required to modify the .htaccess locate in /var/www/html but every time i upgrade my service in rancher it rollback to the default one.

So i have mounted a volume from rancher-nfs with this path : `wordpress_httpds_data/.htaccess:/var/www/html/.htaccess`

Instead of mapping my .htaccess file it create a empty folder named .htaccess

is there a solution to prevent that ?

**Comment by wglambert** [comment]
May be a misconfiguration of sorts with NFS, perhaps permissions?

Mounting the file normally works fine

```console
$ docker run -dit --rm -v $(pwd)/.htaccess:/var/www/html/.htaccess wordpress
bfa861763e03814106690691c6f15d7b1cba88b899443e9736745eabd54601b4

$ docker exec bfa cat .htaccess
# Test comment
```

**Comment by wglambert** [comment]
Closing since there isn't anything we can really change in the image for this
