### ISSUE TITLE
5.2.1 on Docker hub / Automation publishing to Docker hub

### ISSUE THREAD

**Issue by radeno** [docker-library/wordpress#401]
Hi guys,

can you explain me automation of publishing of new versions?
I see 2 days old commit updating to 5.2.1 https://github.com/docker-library/wordpress/commit/56a0ef591e95925beb93e2c390dc50b48de11246 but on docker hub is no new version. Are there some issues about publishing newest versions?

Please do not refer to updating through WP interface. We have custom WP image based on WP official image with added CLI, Redis and MU-plugins installed through Composer (https://wpackagist.org) are included. And every new WP version is updated as new deployed image.

**Comment by tianon** [comment]
https://github.com/docker-library/wordpress#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

> Check [the "library/wordpress" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/wordpress), especially [PRs with the "library/wordpress" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fwordpress).
>
> For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

Thus, see https://github.com/docker-library/official-images/pull/5941.

**Comment by radeno** [comment]
My holy blindness. Sorry for stupid issue.
