### ISSUE TITLE
Missing exif and bcmath

### ISSUE THREAD

**Issue by radeno** [docker-library/wordpress#402]
Hi,

with WP 5.2 there is new Site Health Status and it warns that some PHP modules are not available.
`exif` and `bcmath`.
Both are also in recommended list https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions

I know anybody should make own image. But i don't think this is a way. This is WP image, not just raw PHP image. WP should be satisfied by all requirements and work like a charm.
If some developers wan't to make own image, this image should be good inspiration to make it best as they can.

Do you consider to add them ?

**Comment by tianon** [comment]
Yes, given they're required by / recommended for core WordPress
functionality, I agree we should add them.
