### ISSUE TITLE
Remove 'opcache.enable_cli=1'

### ISSUE THREAD

**Issue by J0WI** [docker-library/wordpress#407]
This came up at https://github.com/nextcloud/documentation/issues/1439:

> Enabling OPcache for CLI has the following effect: it will optimize the CLI script (which takes of course more time the first time to do). However, in the case of a CLI script, it is always the first time for every single invocation of the script. The cache only lives until the process terminates, so as soon as the script ends the optimizations are gone.

**Comment by yosifkit** [comment]
Seems reasonable to me. cc @tianon

See also: https://stackoverflow.com/a/25047263

**Comment by tianon** [comment]
+1

**Comment by J0WI** [comment]
Same for Drupal: https://github.com/docker-library/drupal/pull/154
