### ISSUE TITLE
Extend wordpress cli image to extend entrypoint for running wp cli commands on container start up.

### ISSUE THREAD

**Issue by EngrArslanLiaqat** [docker-library/wordpress#409]
Running wp-install from bash file , by extending entrypoint for wordpress:cli always returns an error :
docker file standard_init_linux.go:207

**Comment by tianon** [comment]
Can you please be more specific about exactly what you've tried (specific `docker run` commands, `Dockerfile` contents, etc), what you expected it to do, and what it did instead so we can try to reproduce?
