### ISSUE TITLE
mysql IP increasing automatically?

### ISSUE THREAD

**Issue by oliveagle** [docker-library/wordpress#41]
mysql instance running at `172.17.0.2`

    # docker run -ti --rm --link wordpress-mysql:mysql busybox ping "mysql"
    PING mysql (172.17.0.2): 56 data bytes
    64 bytes from 172.17.0.2: seq=0 ttl=64 time=3.477 ms
    64 bytes from 172.17.0.2: seq=1 ttl=64 time=0.061 ms

because previous version, wordpress container cannot be start again see #38 . so I have to start a new container of wordpress.   but newly created container always exits immediately after creation.  and I observed that **mysql host ip is increasing automatically**. 

    # docker run --link wordpress-mysql:mysql --volumes-from wordpressData -p 80:80 -e WORDPRESS_DB_PASSWORD='$MYSQL_ROOT_PASSWORD' -ti --rm  wordpress /bin/sh

    Warning: mysqli::mysqli(): (HY000/1045): Access denied for user 'root'@'172.17.0.17' (using password: YES) in - on line 5
    MySQL Connection Error: (1045) Access denied for user 'root'@'172.17.0.17' (using password: YES)
    # docker run --link wordpress-mysql:mysql --volumes-from wordpressData -p 80:80 -e WORDPRESS_DB_PASSWORD='$MYSQL_ROOT_PASSWORD' -ti --rm  wordpress /bin/sh

    Warning: mysqli::mysqli(): (HY000/1045): Access denied for user 'root'@'172.17.0.18' (using password: YES) in - on line 5
    MySQL Connection Error: (1045) Access denied for user 'root'@'172.17.0.18' (using password: YES)

I didn't observe the same behavior of other images. 

    # docker run -ti --rm --link wordpress-mysql:mysql busybox ping -c 2 "mysql" && date
    PING mysql (172.17.0.2): 56 data bytes
    64 bytes from 172.17.0.2: seq=0 ttl=64 time=0.774 ms
    64 bytes from 172.17.0.2: seq=1 ttl=64 time=0.062 ms
    
    --- mysql ping statistics ---
    2 packets transmitted, 2 packets received, 0% packet loss
    round-trip min/avg/max = 0.062/0.418/0.774 ms
    Fri Jan 16 06:17:43 UTC 2015
    # docker run -ti --rm --link wordpress-mysql:mysql busybox ping -c 2 "mysql" && date
    PING mysql (172.17.0.2): 56 data bytes
    64 bytes from 172.17.0.2: seq=0 ttl=64 time=0.648 ms
    64 bytes from 172.17.0.2: seq=1 ttl=64 time=0.081 ms

    --- mysql ping statistics ---
    2 packets transmitted, 2 packets received, 0% packet loss
    round-trip min/avg/max = 0.081/0.364/0.648 ms
    Fri Jan 16 06:17:46 UTC 2015

**Comment by oliveagle** [comment]
btw:   -e WORDPRESS_DB_HOST='172.17.0.2'   doesn't work:

    # docker run --link wordpress-mysql:mysql --volumes-from wordpressData -ti --rm -p 80:80 -e WORDPRESS_DB_PASSWORD='$MYSQL_ROOT_PASSWORD' -e WORDPRESS_DB_HOST='172.17.0.2' wordpress   

    Warning: mysqli::mysqli(): (HY000/1045): Access denied for user 'root'@'172.17.0.29' (using password: YES) in - on line 5
    MySQL Connection Error: (1045) Access denied for user 'root'@'172.17.0.29' (using password: YES)

**Comment by tianon** [comment]
@yosifkit it might be worth switching over to using the `/etc/hosts` entry since https://github.com/docker/docker/pull/7677 is in 1.3.0+ (and it will still work exactly as it does today in versions older than that); WDYT?

**Comment by yosifkit** [comment]
That sounds like a reasonable solution to me.
