### ISSUE TITLE
not linking database

### ISSUE THREAD

**Issue by ayushpadia** [docker-library/wordpress#413]
@yosifkit
Sorry to keep asking on a closed issue but my problem is not resolved till now. My script is:

version: '3.7'

services:
Database

db:
image: mysql
restart: always
volumes:
- db_data:/var/lib/mysql
ports:
- '8200:3306'
environment:
MYSQL_ROOT_PASSWORD: password
MYSQL_DATABASE: wordpress
MYSQL_USER: wordpress
MYSQL_PASSWORD: wordpress
networks:
- wpsite
phpmyadmin

phpmyadmin:
depends_on:
- db
image: phpmyadmin/phpmyadmin
restart: always
ports:
- '8201:80'
environment:
PMA_HOST: db
PMA_PASSWORD: password
MYSQL_ROOT_PASSWORD: password
networks:
- wpsite
Wordpress

wordpress:
depends_on:
- db
image: wordpress
ports:
- '8202:80'
restart: always
volumes: ['./:/var/www/html']
environment:
WORDPRESS_DB_HOST: db
WORDPRESS_DB_USER: wordpress
WORDPRESS_DB_PASSWORD: wordpress
networks:
- wpsite
networks:
wpsite:
volumes:
db_data:

I am trying it to host it in another computer but whenever I go to port 8201 and try to login with root and password it says cant connect and in port 8202 it says cant connect to database

**Comment by wglambert** [comment]
Your `mysql` uses `mysql:8` which changed the default authentication to [`caching_sha2_password`](https://mysqlserverteam.com/upgrading-to-mysql-8-0-default-authentication-plugin-considerations/)

You can include a `command:` to change it
```yml
image: mysql
command: --default-authentication-plugin=mysql_native_password
```
