### ISSUE TITLE
Install is not persisted when I remove a container

### ISSUE THREAD

**Issue by rokcarl** [docker-library/wordpress#416]
I'm using Docker Compose and I've tried a few volume options, but in the end I've settled on `/data/wordpress/html:/var/www/html`. The problem is that if I stop the containers and then remove them, I get to the installation again (`/wp-admin/setup-config.php`). While the database is left intact, I have to install Wordpress and themes again.

This leads me to think that I'm not mounting some file to the outside and it's not being persisted. What can I do about it?

I'm always setting the following environment variables for Wordpress: `WORDPRESS_DB_HOST`, `WORDPRESS_DB_USER`, `WORDPRESS_DB_PASSWORD`, `WORDPRESS_DB_NAME` and `WORDPRESS_TABLE_PREFIX`‚.

The section for Wordpress in `docker-compose.yml`:

      wordpress:
        image: wordpress:5.2.2-fpm
        depends_on:
          - mysql
        ports:
          - 8080:80
        volumes:
          - /usr/src/wordpress
          - /data/wordpress/html:/var/www/html
          - ./wordpress/php.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
          - WORDPRESS_DB_HOST=mysql
          - WORDPRESS_DB_USER=wp
          - WORDPRESS_DB_PASSWORD="${MYSQL_PASSWORD}"
          - WORDPRESS_DB_NAME=wp
          - WORDPRESS_TABLE_PREFIX=wp_
        restart: always
        networks:
          - frontend
          - backend

**Comment by rokcarl** [comment]
When I install a theme, I don't see it in the `wp-content/themes` folder where I expect it. Where is it?

    docker-compose exec wordpress ls -l /var/www/html/wp-content/themes/
    total 16
    -rw-r--r-- 1 www-data www-data   28 Jun  5  2014 index.php
    drwxr-xr-x 8 www-data www-data 4096 Jul 20 09:21 twentynineteen
    drwxr-xr-x 5 www-data www-data 4096 Jul 20 09:21 twentyseventeen
    drwxr-xr-x 7 www-data www-data 4096 Jul 20 09:21 twentysixteen

**Comment by wglambert** [comment]
Does your `mysql` database have a volume?

With just mounting the `/var/www/html` and mysql's `/var/lib/mysql` then encompassed wordpress configuration changes are persisted and the installation itself is persisted through mysql.

```console
$ curl localhost:8000 2>/dev/null | head                                                                                       
<!doctype html>                                                                                                                                               
<html lang="en-US">                                                                                                                                           
<head>                                                                                                                                                        
        <meta charset="UTF-8" />                                                                                                                              
        <meta name="viewport" content="width=device-width, initial-scale=1" />                                                                                
        <link rel="profile" href="https://gmpg.org/xfn/11" />                                                                                                 
        <title>title &#8211; Just another WordPress site</title>                                                                                              
<link rel='dns-prefetch' href='//s.w.org' />                                                                                                                  
<link rel="alternate" type="application/rss+xml" title="title &raquo; Feed" href="http://localhost:8000/?feed=rss2" />                                        
<link rel="alternate" type="application/rss+xml" title="title &raquo; Comments Feed" href="http://localhost:8000/?feed=comments-rss2" />                      

$ docker-compose down                                                                                                          
Stopping wordpress_wordpress_1 ... done
Stopping wordpress_db_1        ... done
Removing wordpress_wordpress_1 ... done
Removing wordpress_db_1        ... done
Removing network wordpress_default                                                                                                                            

$ docker-compose up -d                                                                                                         
Creating network "wordpress_default" with the default driver                                                                                                  
Creating wordpress_db_1 ... done
Creating wordpress_wordpress_1 ... done

$ curl localhost:8000 2>/dev/null | head
<!doctype html>
<html lang="en-US">
<head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="profile" href="https://gmpg.org/xfn/11" />
        <title>title &#8211; Just another WordPress site</title>
<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="title &raquo; Feed" href="http://localhost:8000/?feed=rss2" />
<link rel="alternate" type="application/rss+xml" title="title &raquo; Comments Feed" href="http://localhost:8000/?feed=comments-rss2" />

$ ls wp/wp-content/themes/
index.php  news-magazine/  twentynineteen/  twentyseventeen/  twentysixteen/
```
The "news-magazine" theme was persisted through the container removal

docker-compose.yml
```yaml
version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress


  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
```

**Comment by rokcarl** [comment]
Yes, as I mentioned, the database is left intact, so yes, I have volumes for Mysql. Maybe it's something with my specific setup, I'll try your compose file as soon as I can and report back.

**Comment by rokcarl** [comment]
Your compose file works as it should, so must be something specific to my set up. I'm trying some other approaches, so closing this for now.
