### ISSUE TITLE
Add PHP pdo_mysql extension for MailPoet v3 WP Plugin

### ISSUE THREAD

**Issue by zbrookslwm** [docker-library/wordpress#425]
Can we get the pdo_mysql php extension added to the image to support the mailpoet version 3 plugin?

https://kb.mailpoet.com/article/152-minimum-requirements-for-mailpoet-3#php_extension

I believe that pdo_mysql needs to be added to the list of the installed packages by the docker-php-ext-install command in the Dockerfile.

![Screen Shot 2019-08-30 at 4 53 28 PM](https://user-images.githubusercontent.com/54386106/64053131-c123aa00-cb46-11e9-881b-479dac2e9a9c.png)

**Comment by wglambert** [comment]
The image supports installing php extensions
https://github.com/docker-library/docs/tree/master/wordpress#adding-additional-libraries--extensions

**Comment by zbrookslwm** [comment]
I wanted to avoid creating my own image but that's fine. Thanks for getting back to me.
