### ISSUE TITLE
Active Environment Variable Usage

### ISSUE THREAD

**Issue by BlenderDude** [docker-library/wordpress#432]
When using this docker library, I see that it extracts itself into `/var/www/html` on first launch, but it also seems to hard code all of the environment variables into the `wp-config.php` file. Is there any particular reason that we don't pull the variables from the environment on each run? 

I've read through the thread over at #333 and agree that it does not make sense to `eval` the `WORDPRESS_EXTRA_CONFIG` variable on each run. Other variables, though, like `WORDPRESS_DB_HOST` and `WORDPRESS_DB_PASSWORD` feel weird to be hard coded. 

Why don't we extract the variables on each run by utilizing `getenv` such that the new `wp-config.php` would contain lines like `define( 'DB_NAME',  getenv('WORDPRESS_DB_NAME'));`. I feel like this might be a cleaner solution, and bar the database password in particular from being hard coded into wp-config. Thoughts?

**Comment by yosifkit** [comment]
First thought is that this would break anyone who is using a custom fpm config with `clear_env = yes`.

Second thought is that this could greatly simplify the entrypoint by removing most of the `sed`ing. But if users are providing a vanilla wordpress via a bind mount and relying on the sed behavior via the env vars...:disappointed:

**Comment by BlenderDude** [comment]
@yosifkit Makes sense, breaking changes are no fun for anyone. As of right now, I have been just putting
```
define( 'DB_NAME', getenv('DB_NAME'));
define( 'DB_HOST', getenv('DB_HOST'));
etc...
```
in the `WORDPRESS_EXTRA_CONFIG` variable such that it all comes from the new variables instead. It works but is definitely not optimal. Might be advantageous for me to just fork and create my own image.

**Comment by tianon** [comment]
In that case, I'd recommend fixing up your copy of `wp-config.php` on-disk how you like it, then just using `--entrypoint` to avoid our extra behavior entirely. 👍

**Comment by BlenderDude** [comment]
Seems like this request seems better suited for a custom fork. I'll go ahead and close to keep the issues clean!
