### ISSUE TITLE
FPM containers returning empty response to http requests

### ISSUE THREAD

**Issue by thisgeek** [docker-library/wordpress#442]
Http request from my host are all failing in at least two versions of fpm wordpress. I've tried two so far:

The latest
```
docker run -p 9000:9000 wordpress:5.2.3-fpm
```
and
```
docker run -p 9000:9000 wordpress:4.8.1-fpm
```

I am able to make requests to an nginx container from the same host without trouble.

**Comment by thisgeek** [comment]
Hunch: upstream issue with the php images?

**Comment by wglambert** [comment]
The `fpm` variant doesn't have a webserver, if you switch to `wordpress:latest` or `wordpress:apache` then it uses apache.

https://github.com/docker-library/docs/blob/master/php/README.md#phpversion-fpm

**Comment by thisgeek** [comment]
Fair enough. I seem to remember it working back when 4.8.1 was latest or near latest.
