### ISSUE TITLE
Can't pull the image from AWS

### ISSUE THREAD

**Issue by lightsaber** [docker-library/wordpress#45]
From my AWS instance, when I run:
sudo docker pull wordpress:latest

I get:

downloads... downloads.. downloads
69387ad66963: Download complete
6e0782896a9b: Error downloading dependent layers
2015/01/21 02:14:20 Could not find repository on any of the indexed registries.

**Comment by evanderkoogh** [comment]
@lightsaber I just pulled the image successfully on a brand new ubuntu machine in the ireland datacenter. So it is not a AWS wide issues. If you are still experiencing the issue, please provide more information.

**Comment by yosifkit** [comment]
Closing old issue, if you feel this was closed in error please let us know.
