### ISSUE TITLE
wp cli runs out of memory

### ISSUE THREAD

**Issue by yangm97** [docker-library/wordpress#452]
```bash
wp package install aaemnnosttv/wp-cli-dotenv-command:^2.0
```
Results in

```
Installing package aaemnnosttv/wp-cli-dotenv-command (^2.0)
Updating /home/www-data/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
[29-Nov-2019 18:15:42 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 10485760 bytes) in phar:///usr/local/bin/wp/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php on line 588
Reverted composer.json.
WP-CLI ran out of memory. Please see https://bit.ly/wpclimem for further help.
```

**Comment by wglambert** [comment]
https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-allowed-memory-size-of-999999-bytes-exhausted-tried-to-allocate-99-bytes

Passing `php -d memory_limit=512M "$(which wp)" package install aaemnnosttv/wp-cli-dotenv-command:^2.0` installed successfully using the example compose file [here](https://github.com/docker-library/docs/tree/master/wordpress#-via-docker-stack-deploy-or-docker-compose) 

```console
$ docker-compose up -d  
Creating network "wordpress_default" with the default driver
Creating wordpress_db_1        ... done
Creating wordpress_wordpress_1 ... done

$ docker run -it --rm --volumes-from wordpress_wordpress_1 --network container:wordpress_wordpress_1 wordpress:cli sh

/var/www/html $ php -d memory_limit=512M "$(which wp)" package install aaemnnosttv/wp-cli-dotenv-command:^2.0
Installing package aaemnnosttv/wp-cli-dotenv-command (^2.0)
Updating /home/www-data/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.023 seconds
Analyzed 1489 packages to resolve dependencies
Analyzed 46034 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: aaemnnosttv/wp-cli-dotenv-command:v2.0.0
 - Installing aaemnnosttv/wp-cli-dotenv-command (v2.0.0)
Writing lock file
Generating autoload files
---
Success: Package installed.
```

For a permanent solution you could change the `memory_limit` value in the php.ini https://github.com/docker-library/docs/blob/master/php/README.md#configuration

**Comment by yangm97** [comment]
I wonder if there's any objection to raising the memory limit on the base image, feels like this is a change everyone would need to do.

**Comment by tianon** [comment]
I think it's something specific to what this particular plugin is trying to do, so I'm not really keen on increasing the limit unilaterally for all users of the image (unless we can find some documentation from either WordPress or WP-CLI stating that the limit should definitely be higher).

**Comment by yangm97** [comment]
Ideally we would control a container's memory usage using docker itself, for instance by using `--memory` flag on `docker run`, so instead of statically changing the limit from 256MB to 512MB we probably want to disable the php limit altogether (`memory_limit=-1`).

Although @wglambert method certainly does work, it is convoluted, not something I personally would remember by heart. And I might be "unlucky" but almost every (if not all) `composer install` I've run in the last couple of days has gone beyond the 256MB limit.

**Comment by wglambert** [comment]
There isn't a `php.ini` loaded by default so you can have a customized one with an appropriate `memory_limit` value
```console
$ docker-compose up -d                                                                                                                        
Creating network "wordpress_default" with the default driver                                                                                                                
Creating wordpress_db_1        ... done
Creating wordpress_wordpress_1 ... done

$ docker exec -it wordpress_wordpress_1 bash

root@7d085eeef766:/var/www/html# php --ini
Configuration File (php.ini) Path: /usr/local/etc/php                                                                                                                       
Loaded Configuration File:         (none)                                                                                                                                   
Scan for additional .ini files in: /usr/local/etc/php/conf.d                                                                                                                
Additional .ini files parsed:      /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
/usr/local/etc/php/conf.d/docker-php-ext-exif.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-imagick.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini,
/usr/local/etc/php/conf.d/error-logging.ini,
/usr/local/etc/php/conf.d/opcache-recommended.ini

root@7d085eeef766:/var/www/html# php -i | grep memory_limit            
memory_limit => 128M => 128M

root@19490600e3b9:/var/www/html# sed -ie 's/128M/512M/g' /usr/local/etc/php/php.ini-production

root@19490600e3b9:/var/www/html# mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

root@19490600e3b9:/var/www/html# php -i | grep memory_limit
memory_limit => 512M => 512M
```

Going to close since it's up to the user to pick a `php.ini` to use and modify any values

**Comment by yangm97** [comment]
> Going to close since it's up to the user to pick a php.ini to use and modify any values

The whole point of this issue is to discuss whether this is true or not. 

If I remember correctly, library images are supposed to "just work" not require random commands to be useful, which is why they sometimes become bloated and always have an `entrypoint.sh`.

**Comment by wglambert** [comment]
https://github.com/php/php-src/blob/1d69bf187fdd4e1ec78d8bb06c3dbce3ab6b5d53/php.ini-production#L72-L74
>PHP comes packaged with two INI files. One that is recommended to be used in production environments and one that is recommended to be used in development environments.

https://docs.docker.com/docker-hub/official_images/
>The Docker Official Images are a curated set of Docker repositories hosted on Docker Hub. They are designed to:
>- Provide essential base OS repositories (for example, ubuntu, centos) that serve as the starting point for the majority of users.

https://github.com/docker-library/official-images/#what-do-you-mean-by-official
>we strive to create images that are true to the upstream project's vision for how their project is intended to be consumed, occasionally adding additional behavior to make them more friendly to use within Docker / containerization in general.

If upstream by default gives users a choice of `.ini` files to use then we implement that in the image. The official-images are designed as a base-image to build off of that reflects how the upstream developer intends for their software to be consumed.

Given that `WP-CLI ran out of memory` is in the common issues of the [wp-cli handbook](https://make.wordpress.org/cli/handbook/common-issues) this really isn't an issue with the way we package the software in the image so we're not going to make modifications to work around common issues. This is the normal experience of using the software outside of a container environment.

**Comment by jeffgoh** [comment]
I know this issue is closed - but at last in WP2.7.1 in docker, setting WP_MEMORY_LIMIT higher than 128M (256M? 512M?) in wp-config.php helped me get past some memory issues in sites with enough plugins to break "wp user list"
