### ISSUE TITLE
5.3.2 is out - please update?

### ISSUE THREAD

**Issue by nicwise** [docker-library/wordpress#456]
Subject says it all - bump version please?

**Comment by yosifkit** [comment]
https://github.com/docker-library/wordpress/commit/0df5de06a4f43f2790dfc3be92554a7e229115d9

https://github.com/docker-library/wordpress#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

https://github.com/docker-library/official-images/pull/7174 So, images will be built soon (see also https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what).

**Comment by nicwise** [comment]
Thank you <3
