### ISSUE TITLE
Edit MPM of apache for multicore processing

### ISSUE THREAD

**Issue by zipvault** [docker-library/wordpress#457]
When doing an AB Request stress test i notice by default on docker with raspberry it only uses the 1st core primarily? Across the docker swarm.

I think i need to add mpm= “event” to the apache config inside the wordpress docker image?

![Uploading 662045D5-0D98-4266-80C2-0D9720E1D649.jpeg…]()

**Comment by wglambert** [comment]
There's a PR open for adding `mpm_event` support, which requires ZTS thread safety to be enabled https://github.com/docker-library/php/pull/753

The `php:apache` variant uses prefork as recommended by upstream https://www.php.net/manual/en/install.unix.apache2.php
>Warning We do not recommend using a threaded MPM in production with Apache 2. Use the prefork MPM, which is the default MPM with Apache 2.0 and 2.2. For information on why, read the related FAQ entry on using [Apache2 with a threaded MPM](https://secure.php.net/manual/en/faq.installation.php#faq.installation.apache2)

Other relevant discussion https://github.com/docker-library/php/issues/742
