### ISSUE TITLE
problem accessing home page

### ISSUE THREAD

**Issue by JessPinkman** [docker-library/wordpress#458]
Hello,

I am starting to use docker (docker toolbox on win 10 home) for wordpress, using docker-compose, 

while yesterday it was working flawlessly, today i ran into an issue for project A.

If i try to access my http://192.168.99.100:8000, it redirects to http://192.168.99.100:5000 with a connection failure. but if i try to access any other page, such as http://192.168.99.100:8000/wp-admin, it works.

wordpress settings point to http://192.168.99.100:8000 for both site address and wordpress address

here is my docker-compose

```json
version : '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:5.3.2-php7.4-apache
        volumes:
            - ./app:/var/www/html
        ports:
            - "8000:80"
        restart: unless-stopped
        environment:
            WORDPRESS_DB_HOST: "db:3306"
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DEBUG: 1

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MY_SQL_ROOT_PASSWORD: root
        ports:
            - "8001:80"
volumes:
    db_data: {}

```
I have another project with similar setup, could they conflict ? project B doesn't have this problem.
i tried to stop all containers from container B when working on project A, but issue still exists.

here is project B, only ports for wordpress and phpmyadmin are changed

```json

version : '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:5.3.2-php7.4-apache
        volumes:
            - ./app:/var/www/html
        ports:
            - "8080:80"
        restart: unless-stopped
        environment:
            WORDPRESS_DB_HOST: "db:3306"
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DEBUG: 1

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MY_SQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
volumes:
    db_data: {}
```
I think problem appeared after i created project B

**Comment by wglambert** [comment]
Your ports for the different projects don't conflict so it shouldn't be an issue. This does seem `docker-toolbox` specific, have you tried it on [Docker Desktop](https://docs.docker.com/docker-for-windows/install/)? 


It's recommended to upgrade to Docker Desktop if possible
https://docs.docker.com/toolbox/overview/
>Docker Toolbox is for older Mac and Windows systems that do not meet the requirements of Docker Desktop for Mac and Docker Desktop for Windows. We recommend updating to the newer applications, if possible.

**Comment by JessPinkman** [comment]
> It's recommended to upgrade to Docker Desktop if possible
> https://docs.docker.com/toolbox/overview/

Unfortunately, Docker Desktop is not available on windows 10 home. I'll eventually switch to linux when I can. thanks anyway. In the meantime, I am using other ports, which seems to work.
