### ISSUE TITLE
minimal alpine images with nginx + apache

### ISSUE THREAD

**Issue by bukowa** [docker-library/wordpress#462]
Hello, could it be a scope of this project to provide minimal `alpine` images for both `apache` and `nginx` ? I imagine versions focused on minimal `disk` and `ram` usage.

**Comment by yosifkit** [comment]
For apache in alpine see https://github.com/docker-library/php/pull/801 and specifically https://github.com/docker-library/php/pull/801#issuecomment-499261939.

For nginx that would have to be nginx plus php-fpm, which we instead recommend as two separate containers (see https://github.com/docker-library/php/pull/821#issuecomment-488382316). Here is an example of doing just that by libre.sh: https://lab.libreho.st/libre.sh/docker/wordpress
