### ISSUE TITLE
Allow entrypoint executing custom commands

### ISSUE THREAD

**Issue by bukowa** [docker-library/wordpress#463]
How can we pass custom scripts to execute after `docker-entrypoint.sh` is done?

* Something that should work
```Dockerfile
FROM wordpress:php7.4-fpm-alpine
COPY entrypoint.sh /usr/local/bin/
CMD ["entrypoint.sh", "php-fpm"]
````
* This is blocking

https://github.com/docker-library/wordpress/blob/0df5de06a4f43f2790dfc3be92554a7e229115d9/php7.4/fpm-alpine/docker-entrypoint.sh#L26

https://github.com/docker-library/wordpress/blob/0df5de06a4f43f2790dfc3be92554a7e229115d9/php7.4/fpm-alpine/docker-entrypoint.sh#L290

Is there a solution i am missing? If not, can we improve `docker-entrypoint.sh`?

**Comment by yosifkit** [comment]
Duplicate #242
