### ISSUE TITLE
AWS ECS and Sigwinch

### ISSUE THREAD

**Issue by CarlosUvaSilva** [docker-library/wordpress#476]
I'm trying to dockerize my wordpress install, everything is configured on AWS' side and the container works for a couple of seconds (I get the "install wordpress" screen) but then it stops and restarts the container.

In my logs I have `[mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully` error. 

If I run my docker image on my localhost it doesn't break, only when deployed to AWS.
Can anyone help me please?

**Comment by wglambert** [comment]
Same issue on Amazon EC2 https://github.com/docker-library/php/issues/892#issuecomment-531310247

>So given that you're running the service in the foreground when encountering this issue then unfortunately we've accurately reproduced the expected behavior from upstream https://bz.apache.org/bugzilla/show_bug.cgi?id=50669
>>You are correct that SIGWINCH is used to signal a windows size change to the applications running on a terminal. Due to the lack of other signal numbers and given the fact that httpd normally runs detached from a terminal the SIGWINCH signal was chosen to instruct httpd to do a graceful shutdown. So this works as designed.

You'll probably have to do the workaround here https://github.com/docker-library/php/issues/892#issuecomment-531335345
To change the CMD to use the shell form which will run it in a subshell and won't proxy signals.
https://docs.docker.com/engine/reference/builder/#cmd

**Comment by CarlosUvaSilva** [comment]
Dockerfile:
```
FROM wordpress:latest

COPY entrypoint-child.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint-child.sh
ENTRYPOINT ["entrypoint-child.sh"]
CMD ["apache2-foreground"]
```

entrypoint:
```
set -euo pipefail

echo "Adding permissions"
chown -R www-data:www-data /var/www/html/wp-content &
find /var/www/html/wp-content -type d -exec chmod 0755 {} \; &
find /var/www/html/wp-content -type f -exec chmod 644 {} \; &
echo "Permissions added"

exec docker-entrypoint.sh "$@"
```

How do I turn this into that ?

**Comment by wglambert** [comment]
Actually in that thread I linked https://github.com/docker-library/php/issues/892#issuecomment-531410330 the issue was a misconfiguration with the AWS loadbalancer, so there might not even be an issue with AWS and SIGWINCH
>if an application load balancer's health check fails it kills the ECS tasks.

**Comment by wglambert** [comment]
Were you able to resolve the issue?

**Comment by CarlosUvaSilva** [comment]
I haven't had the time to test this. I'll close the issue and opened it later if needed. 
Thank you for the help
