### ISSUE TITLE
wordpress 5.4

### ISSUE THREAD

**Issue by xgs0921** [docker-library/wordpress#479]

**Comment by wglambert** [comment]
https://github.com/docker-library/wordpress/commit/bf85cc7bf33afbbfadd86ba79b3d8ad325289057
https://github.com/docker-library/wordpress#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by yosifkit** [comment]
Soon. https://github.com/docker-library/official-images/pull/7726
