### ISSUE TITLE
PHP extension intl - Polylang Plugin - PHP fatal error call to undefined function idn_to_ascii()

### ISSUE THREAD

**Issue by schroedingerdb** [docker-library/wordpress#481]
Wordpress image: wordpress:5.4.0-php7.2-fpm
Polylang Plugin version: 2.7.0.1

I get a PHP fatal by using the polylang plugin because of the missing php module php7-intl.
Is it possible to add the intl module to the docker container?

```
2020/04/08 10:26:07 [error] 6#6: *44 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function idn_to_ascii() in /var/www/html/wp-content/plugins/polylang/include/links-domain.php:87
Stack trace:
#0 /var/www/html/wp-content/plugins/polylang/include/links-domain.php(22): PLL_Links_Domain->get_hosts()
#1 /var/www/html/wp-content/plugins/polylang/include/model.php(564): PLL_Links_Domain->__construct(Object(PLL_Model))
#2 /var/www/html/wp-content/plugins/polylang/include/class-polylang.php(238): PLL_Model->get_links_model()
#3 /var/www/html/wp-includes/class-wp-hook.php(287): Polylang->init('')
#4 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /var/www/html/wp-settings.php(409): do_action('plugins_loaded')
#7 /var/www/html/wp-config.php(91): require_once('/var/www/html/w...')
#8 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...')
#9 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')" while reading response header from upstream, client: 95.90.241.251, server: mysite, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mysite"
```

**Comment by schroedingerdb** [comment]
quick hotfix

`
git clone https://github.com/docker-library/wordpress.git
cd wordpress/php7.2/fpm/


        docker-php-ext-install -j "$(nproc)" \
                bcmath \
                exif \
                gd \
                mysqli \
                opcache \
                zip \
                intl \


docker build . -t hotfix-wordpress-php7.2 --network host
`

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/wordpress#adding-additional-libraries--extensions
>This image does not provide any additional PHP extensions or other libraries, even if they are required by popular plugins

So doing `docker-php-ext-install intl` is the proper way of resolving this issue. I don't think there'd be a great benefit to installing it in the base image, as even then you'd still need 6 other extensions which would vary per person.

**Comment by schroedingerdb** [comment]
Yes, you are right. There is no way to install more extensions to the wordpress docker image.

But great news from the polylang plugin. They fixed that issue.
https://github.com/polylang/polylang
```
== Changelog ==

= 2.7.1 (2020-04-09) =

* Pro: Fix untranslated post types filtered by the parameter in the REST API #493
* Fix fatal error when the function idn_to_ascii is not available
* Fix PHP warning warning when a 3rd party plugin declares options not stored in DB in wpml-config.xml #492
* Fix fatal error when a 3rd party plugin declares options stored as objects in wpml-config.xml #494
```

**Comment by schroedingerdb** [comment]
So, yes I can confirm that the polylang version 2.7.1 fixed that issue.

**Comment by tianon** [comment]
> There is no way to install more extensions to the wordpress docker image. I mean no other way than to work this git repo and create a own custom image.

This isn't completely accurate -- you don't have to do anything with this Git repository to add extensions to your `wordpress` image (although building your own custom image is necessary); building a simple `Dockerfile` like the following is sufficient:

```dockerfile
FROM wordpress:php7.2-fpm
RUN apt-get update && apt-get install -y --no-install-recommends libicu-dev && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install intl
```
