### ISSUE TITLE
Use safer checksum such as sha256 or blake2 instead of sha1

### ISSUE THREAD

**Issue by emanuelb** [docker-library/wordpress#494]
sha1 is not safe anymore:
https://shattered.io/
https://sha-mbles.github.io/
which is used as checksum for downloaded files at:
https://github.com/docker-library/wordpress/blob/8215003254de4bf0a8ddd717c3c393e778b872ce/php7.4/apache/Dockerfile#L98
https://github.com/docker-library/wordpress/blob/8215003254de4bf0a8ddd717c3c393e778b872ce/php7.4/apache/Dockerfile#L102

fix: use sha256sum (sha256) or b2sum (blacke2) commands instead.

**Comment by J0WI** [comment]
WordPress itself does only provide SHA1 and MD5: https://wordpress.org/download/releases/

**Comment by tianon** [comment]
Indeed - if upstream starts providing better checksums, we will happily switch to use them! :disappointed: 

Closing for now as there's not really anything actionable for us here.
