### ISSUE TITLE
Don't add WP_DEBUG=TRUE if WORDPRESS_DEBUG is set to FALSE

### ISSUE THREAD

**Issue by dbjpanda** [docker-library/wordpress#496]
I have a .env.example inside my docker-compose project. For simplicity, when onboarding a team member, I just ask to rename it to .env, change the debug value if you are developer, and `docker-compose up`.  

If you are a designer you don't need to change that value. Just keep its value as it is. i.e By default I have the env variable set to FALSE. But even if it is set to false it adds `WP_DEBUG=true`. 

So please don't check with an empty variable. **Rather it should be checked if it is set to true or not** 
https://github.com/docker-library/wordpress/blob/8215003254de4bf0a8ddd717c3c393e778b872ce/docker-entrypoint.sh#L231

**Comment by yosifkit** [comment]
> -e WORDPRESS_DEBUG=1 (defaults to disabled, **non-empty value** will enable WP_DEBUG in wp-config.php)
>
> [Docker Hub docs](https://github.com/docker-library/docs/tree/c541d218ffdbb15f11e696b45e6b49070cb8e381/wordpress#how-to-use-this-image)

For simplicity of our bash scripts across many official-images, we don't look for "truthy" values and instead just use the fact of it being filled/set to turn it on and unset/empty to turn if off.

**Comment by dbjpanda** [comment]
@yosifkit Thanks for a quick response. 
Okay, I understand that. But here you are populating a PHP variable. A PHP variable is empty doesn't mean it is false. Contains some value does not mean it is true always. 

Though it is okay for those who spin the container directly. But doesn't fit with Docker-compose or .env file.

**Comment by tianon** [comment]
> But here you are populating a PHP variable.

I think this is the crux of the disagreement here -- our `WORDPRESS_DEBUG` environment variable is not populating `WP_DEBUG`, but rather toggling whether or not we set it (so that in a default Wordpress install, it is not explicitly set/touched by our script at all).

Frankly, I'd love to deprecate it entirely in favor of the newer and much more flexible `WORDPRESS_CONFIG_EXTRA`, which could be set to something clever like the following to accomplish what you're looking for:

```yaml
        WORDPRESS_CONFIG_EXTRA: |
          define('WP_DEBUG', boolval(getenv('WP_DEBUG')));
```

**Comment by dbjpanda** [comment]
>Frankly, I'd love to deprecate it entirely in favor of the newer and much more flexible WORDPRESS_CONFIG_EXTRA, which could be set to something clever like the following to accomplish what you're looking for:

@tianon I agree with your point completely. `WORDPRESS_DEBUG` should be removed. @yosifkit  please let us know if you are willing to merge a PR.

Thanks

**Comment by rfrenayworldstream** [comment]
Hi,

I agree that setting this value with any value should enable WP_DEBUG according the documentation. However unsetting this variable will not turn off debugging again.

The following change would allow us to turn off debugging.
```
if [ "$WORDPRESS_DEBUG" ]; then
        set_config 'WP_DEBUG' 1 boolean
else
        set_config 'WP_DEBUG' 0 boolean
fi
```
