### ISSUE TITLE
Update the README of hub.docker.com for production settings

### ISSUE THREAD

**Issue by lucastercas** [docker-library/wordpress#498]
Usually, in production is not normally used bind-mounts, like it is suggested on the readme, on the `Include pre-installed themes / plugins` section, it it better to build a custom image, and just pull it to use in production, without any bind-mount.

However, if it is done like it is said on the readme, there will be permission issues on the directories, as they will be owned by root:
```Dockerfile
FROM wordpress:5.4.1-apache
COPY --chown=www-data:www-data ./my_theme /var/www/html/wordpress/wp-content/themes/my_theme
```

So it is better to `COPY` the files to `/usr/src/wordpress`, like so:
```Dockerfile
FROM wordpress:5.4.1-apache
COPY --chown=www-data:www-data ./my_theme /usr/src/wordpress/wp-content/themes/my_theme
```

This way, there will be no permission issues, as the `docker-entrypoint.sh` will copy then with the correct permissions.

**Comment by tianon** [comment]
It will copy them the first time, but as noted in #542, there are some caveats; the main caveat is that it won't perform updates to the pre-installed plugin (so those will need to be installed out-of-band anyhow), so I'm hesitant to document this more explicitly lest users actually rely on it without realizing/noticing that their plugins/themes then do not update. :confused:
