### ISSUE TITLE
Cannot mkdir: Permission denied when tar -xzf wordpress.tar.gz -C /usr/src/

### ISSUE THREAD

**Issue by blackavg** [docker-library/wordpress#502]
The command tar -xzf wordpress.tar.gz -C /usr/src/ gets an "cannot mkdir: Permission denied" when running on ubuntu, since /usr/src/ is typical allowed to root

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

If you're bind mounting a volume make sure your permissions are appropriate for the user in the container

**Comment by blackavg** [comment]
Thanks wglambert .. Actually it was that, some kind of permissions issue using NFS for persistent volumes.
