### ISSUE TITLE
Text Editor

### ISSUE THREAD

**Issue by howardjacobson** [docker-library/wordpress#512]
I suggest that some simple text editor be included in the image. Modifying config files for testing or experimentation is too hard, unless I am missing an easy way (and happy to learn it). Thanks.

**Comment by wglambert** [comment]
You can just `apt update && apt install` whatever editor you want. 

Typically a Dockerfile would be made for customization of the image
```dockerfile
FROM wordpress:5.4.2-php7.2-apache

RUN apt update && apt install -y --no-install-recommends vim && \
rm -rf /var/lib/apt/lists/*
```

Another way would be to mount the files/folders into the container from the host, then editing on the host would be instantly reflected in the container
https://docs.docker.com/storage/bind-mounts/
