### ISSUE TITLE
The uploaded file exceeds the upload_max_filesize directive in php.ini.

### ISSUE THREAD

**Issue by TheBoneJarmer** [docker-library/wordpress#519]
Hi guys

I tried uploading a theme zip file but I couldn't because I hit a file upload size limit.. Any idea what I can do about this? I mean, normally I would modify php.ini and restart the httpd service but I can't as it is all part of the container.. Sigh. Any help would be greatly appreciated!

With kind regards,
TheBoneJarmer

**Comment by wglambert** [comment]
https://github.com/docker-library/wordpress/issues/375#issuecomment-463303796

**Comment by TheBoneJarmer** [comment]
Thanks for the reply! While I don't like the solution I will apply it anyway since it will solve my problem. Although I do like to ask if there are any plans on the roadmap to modify these upload size values permanently? 

I mean, if such a trivial thing needs to be hacked into the container using a custom ini file I would not consider that user-friendly and practical. Especially if the only way one could learn about this is by browsing through the issues here.

**Comment by yosifkit** [comment]
> we lack an official recommendation from WordPress upstream on what an appropriate value for this setting should be (and the current value is the default coming directly from PHP upstream).
> \- https://github.com/docker-library/wordpress/issues/10#issuecomment-384076027

> the officially supported way to adjust this value in this image is the same as the way to do so on any PHP install, namely adjusting `php.ini` through any of the various methods PHP provides to do so 
> \- https://github.com/docker-library/wordpress/issues/375#issuecomment-465767259

I do admit we should link to the php image docs or add something to the wordpress image docs about where the `php.ini` should be placed.

**Comment by TheBoneJarmer** [comment]
I see, thanks! In that case would it be possible to add a section to the README in this repo as well as the page on Docker hub? Those were the first places I looked for a solution, others might as well do the same.
