### ISSUE TITLE
WP-CLI incorrectly probes for supported subcommands

### ISSUE THREAD

**Issue by aqueenan** [docker-library/wordpress#523]
`docker-entrypoint` uses `wp --path=/dev/null help "$1"` to check if `$1` is a valid sub-command.

That works for the default `wp-cli` commands, but fails for extensions because they weren't installed in `/dev/null`.

The test should be `wp help "$1"`.

As a workaround, use:
`sudo docker run -it --rm --volumes-from wordpress --network container:wordpress wordpress:cli wp ...`
instead of
`sudo docker run -it --rm --volumes-from wordpress --network container:wordpress wordpress:cli ...`
to invoke the sub-command.

**Comment by tianon** [comment]
There's some previous discussion around this in https://github.com/docker-library/wordpress/pull/387 :sweat_smile:

**Comment by tianon** [comment]
Looks like this was fixed via #387 :partying_face:
