### ISSUE TITLE
Image latest (5.5.1) don't seem to include wordpress version 5.5.1

### ISSUE THREAD

**Issue by ninkaninus** [docker-library/wordpress#527]
I have upgraded our wordpress page with the latest image, but our site til reports that the page is version 5.5 and not 5.5.1, and it request us to update it to 5.5.1.
the page can be seen here:
https://htx-lan.dk

The version.php file says 5.5

**Comment by ninkaninus** [comment]
ENV:
WORDPRESS_VERSION = 5.5.1

**Comment by ninkaninus** [comment]
Latest image tag for this deploy is:
wordpress:5.5.1-php7.4-apache

**Comment by wglambert** [comment]
`WORDPRESS_VERSION` and `WORDPRESS_SHA1` are variables used in the Dockerfile to download the specific version
https://github.com/docker-library/wordpress/blob/b1127748deb2db34e9b1306489e24eb49720454f/php7.4/apache/Dockerfile#L97-L101

If you go to your Dashboard->Updates it should be at the latest version `5.5.1` even if you're using the `5.5.0` image

Testing with `wordpress:5.5.0-php7.4-apache`
https://github.com/docker-library/repo-info/blob/9da6fcbfad8b1ed1d5d72c6eef1d035439d46268/repos/wordpress/remote/5.5.0-php7.4-apache.md

Dashboard shows it auto-updated to `5.5.1`
![image](https://user-images.githubusercontent.com/26428991/92136967-825faa00-edc1-11ea-944c-fb1c432b58eb.png)

But php info keeps the variables set by the old Dockerfile
```console
root@ab514ef48180:/var/www/html# php -i | grep -i wordpress
WORDPRESS_VERSION => 5.5
WORDPRESS_SHA1 => 03fe1a139b3cd987cc588ba95fab2460cba2a89e
WORDPRESS_DB_HOST => db
WORDPRESS_DB_PASSWORD => examplepass
WORDPRESS_DB_USER => exampleuser
WORDPRESS_DB_NAME => exampledb
$_SERVER['WORDPRESS_VERSION'] => 5.5
$_SERVER['WORDPRESS_SHA1'] => 03fe1a139b3cd987cc588ba95fab2460cba2a89e
$_SERVER['WORDPRESS_DB_HOST'] => db
$_SERVER['WORDPRESS_DB_PASSWORD'] => examplepass
$_SERVER['WORDPRESS_DB_USER'] => exampleuser
$_SERVER['WORDPRESS_DB_NAME'] => exampledb
$_ENV['WORDPRESS_VERSION'] => 5.5
$_ENV['WORDPRESS_SHA1'] => 03fe1a139b3cd987cc588ba95fab2460cba2a89e
$_ENV['WORDPRESS_DB_HOST'] => db
$_ENV['WORDPRESS_DB_PASSWORD'] => examplepass
$_ENV['WORDPRESS_DB_USER'] => exampleuser
$_ENV['WORDPRESS_DB_NAME'] => exampledb
```

**Comment by ninkaninus** [comment]
Okay, i see that because i have mounted the wordpress folder to the host it won't enable auto update of wordpress, as some files have been modified and now have another owner.
fixed it like this:
sudo chmod -R www-data:www-data wordpress/

After that i was able to update wordpress from the website

@wglambert Thanks, it was not the solution, but it got me thinking
