### ISSUE TITLE
Support for AWS Elastic Beanstalk Environment Variables

### ISSUE THREAD

**Issue by mrjackdavis** [docker-library/wordpress#53]
In the [AWS blog post for ElasticBeanstalk with docker](https://aws.amazon.com/blogs/aws/aws-elastic-beanstalk-for-docker/) Jeff Barr explains several environment variables are exposed:

- `RDS_DB_NAME`
- `RDS_USERNAME`
- `RDS_PASSWORD`
- `RDS_HOSTNAME`

I know it's a long shot, but support for these would be great. Otherwise I'll end up making my own image

**Comment by tianon** [comment]
I definitely wouldn't feel good about supporting those specific variables directly (given that they're specific to _just_ Elastic Beanstalk), but if we fix #54 in a nice way it should be reasonably easy to build an image based on this one that just puts those where the main `ENTRYPOINT` script is expecting them to be. :+1:

**Comment by mrjackdavis** [comment]
Agreed. I'll close this in preference of #54
