### ISSUE TITLE
entrypoint MySQL connection try and SSL

### ISSUE THREAD

**Issue by jfcoz** [docker-library/wordpress#530]
MySQL SSL connection

When using WORDPRESS_CONFIG_EXTRA ( https://github.com/docker-library/wordpress/pull/142 ) to force MySQL SSL connection (because the server require this) via : 

```
define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);
```

The MySQL connection try in entrypoint will not use this setting and slow down the startup by 30 seconds : https://github.com/docker-library/wordpress/blob/b1127748deb2db34e9b1306489e24eb49720454f/php7.4/apache/docker-entrypoint.sh#L266-L277

During this time the container will loop on this kind of errors : 
```
MySQL Connection Error: (9002) SSL connection is required. Please specify SSL options and retry.
```

**Comment by wglambert** [comment]
Related to https://github.com/docker-library/wordpress/issues/264 and https://github.com/docker-library/wordpress/issues/299#issuecomment-412201734
>I think we should consider updating our documentation to make it clear that if you need SSL for your MySQL connection, you should not set the environment variables we provide and should instead modify wp-config.php

**Comment by jfcoz** [comment]
Do you think the connection test could include the wp-config to use strictly the same settings ?

**Comment by tianon** [comment]
We wanted to do so, and tried, but because `wp-config.php` isn't strictly a configuration file and ends with `require_once ABSPATH . 'wp-settings.php';`, it ends up not being something we can include directly. :disappointed:

**Comment by tianon** [comment]
This is fixed by https://github.com/docker-library/wordpress/pull/557, and should be available for testing under the `beta` tags on Docker Hub soon!
