### ISSUE TITLE
Using external databases

### ISSUE THREAD

**Issue by mrjackdavis** [docker-library/wordpress#54]
I've been trying to connect this image to a non-docker mysql server for the better part of a day. I was able to do it with 3.9, however anything above that doesn't seem to work. There's no documentation either, which has made life hell.

It's be great if we could:

- Document the procedure of connecting to an external mysql database and
- Look into why it doesn't work on versions after 3.9

**Comment by md5** [comment]
[This change](https://github.com/docker-library/wordpress/commit/9aae24350b9c4ede3d5db9cdac1ba88c3202fe98) basically made it impossible to use an external database. Prior to that, it was possible to use `MYSQL_PORT_3306_TCP` to refer to an external database (mimicking the environment variable set by `--link some-mysql:mysql`).

**Comment by tianon** [comment]
I'd be +1 on adding some logic to cleanly check for `mysql` in `/etc/hosts` and fall back to using `MYSQL_PORT_3306_TCP` like we used to if it's not set!

**Comment by tianon** [comment]
(I'm also +1 on documenting what that script does better!)

**Comment by mrjackdavis** [comment]
I'm in the process of deploying a docker website to production now, using amazon RDS for a database. I'll document the process a bit and then see if I can make the improvements @tianon mentioned.

**Comment by yosifkit** [comment]
@mrjackdavis, https://github.com/docker-library/wordpress/pull/55 and https://github.com/docker-library/docs/pull/152 (both should be available later today).

**Comment by kevallakhani** [comment]
I have an AWS RDS db and trying to connect it to wordpress on docker but I am unable to do that. This is what my dockerfile looks like:
```
FROM wordpress:latest

ADD wp-content /var/www/html/wp-content/

ENV WORDPRESS_DB_NAME=''
ENV WORDPRESS_DB_USER=''
ENV WORDPRESS_DB_PASSWORD=''
ENV WORDPRESS_DB_HOST='HOST_NAME:PORT_NUMBER'
ENV WORDPRESS_DB_CHARSET=''
ENV WORDPRESS_AUTH_KEY=''
ENV WORDPRESS_SECURE_AUTH_KEY=''
ENV WORDPRESS_LOGGED_IN_KEY=''
ENV WORDPRESS_NONCE_KEY=''
ENV WORDPRESS_AUTH_SALT=''
ENV WORDPRESS_SECURE_AUTH_SALT=''
ENV WORDPRESS_LOGGED_IN_SALT=''
ENV WORDPRESS_NONCE_SALT=''
```

I have custom theme code in wp-content placed in the same directory as dockerfile. I can create a docker image using `docker build .` in the parent directory but when I do `docker run -p 8080:80 IMAGE_NAME`. It gives mysql 2002 connection refused error.

Any help will be appreciated. Thanks.
