### ISSUE TITLE
Support for PHP8 ?

### ISSUE THREAD

**Issue by haszari** [docker-library/wordpress#540]
Is it possible to add PHP8 support to this image so it can be used for testing/developing PHP8 compatibility of WordPress plugins and themes?

https://wiki.php.net/todo/php80

https://make.wordpress.org/core/2020/10/06/call-for-testing-php-8-0/

I use a docker environment based on this image and it would be great if I could build a variation of my dev env with PHP8 installed. 

Let me know I can help 😄

**Comment by haszari** [comment]
I see that the [php](https://github.com/docker-library/php) image has 8.0-rc support.

https://github.com/docker-library/php/commit/7ef129842e2620a30b45a1d9c003b1f290b0453d

**Comment by tianon** [comment]
We only publish the officially released WordPress version, which is currently 5.5, and https://make.wordpress.org/core/2020/10/06/call-for-testing-php-8-0/ seems to be asking for folks to test the upcoming 5.6 on PHP 8.0, which I think makes more sense for us to wait for.

**Comment by spacedmonkey** [comment]
WordPress 5.6 and PHP 8.0 are now officially out. WP 5.6 officially supports PHP 8. I think it is time to add add a PHP 8 image 

https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/

**Comment by tianon** [comment]
Great catch, thanks for the poke! :heart:

(#551 :partying_face:)
