### ISSUE TITLE
A smart way to use the CLI to replace the `WORDPRESS_CONFIG_EXTRA` variable

### ISSUE THREAD

**Issue by kamihicouki** [docker-library/wordpress#544]
Hi everyone, nice to meet you all.
I've been looking at the documents and discussions in the following order and have come up with a better alternative, so I'll post it.

1. https://hub.docker.com/_/wordpress/
2. https://github.com/docker-library/wordpress/pull/142
3. https://github.com/docker-library/wordpress/blob/5c669502bdab4179f33b309d452881e1e79f2875/docker-entrypoint.sh#L184-L188

* https://github.com/docker-library/wordpress/issues/484
* https://github.com/docker-library/wordpress/issues/496

---

I feel that the [Command line interface for WordPress | WP-CLI](https://wp-cli.org/) project is the best way to accurately, reliably, and quickly rewrite the values of variables in wp-config.php.

And it is fortunately available as a [wordpress - Docker Hub](https://hub.docker.com/_/wordpress/) official image.

MySQL is an essential part of WordPress.
Likewise, considering that WP-CLI is essential for a flexible WordPress/wp-config.php configuration, how about the following?
I think the idempotence of the configuration will be preserved.

``` docker-compose.yml
---
version: "2.4"
services:
  wp-init:
    image: wordpress:cli
    restart: on-failure
    environment:
      - WP_CONFIG_DB_CHARSET=utf8mb4
      - WP_CONFIG_DB_HOST=db
      - WP_CONFIG_TABLE_PREFIX=wp_
    # ... other WP_CONFIG_* variables or env_file load files/variables.
    volumes:
      - wordpress:/var/www/html
      - ./wp-config.sh:/wp-config.sh:ro
    working_dir: /var/www/html
    user: root
    command: sh /wp-config.sh
```

``` wp-config.sh
#!/bin/sh

printenv | sed 's/^WP_CONFIG_//;t;d' | sed 's/=/ /' | while read LINE; do wp --allow-root config set $LINE; done
```

This is just part of my idea of how to do it.
What are your thoughts on this?
Have a great day.

**Comment by tianon** [comment]
I think this is interesting, but I'm not sure what you're proposing as a change for this repository?

Frankly, we'd love to completely deprecate our environment variables in favor of proper upstream-supported `wp-config.php` usage (but that's difficult to accomplish, given it's been in wide use for so long).
