### ISSUE TITLE
Image Not Updated For 5.6.40

### ISSUE THREAD

**Issue by XedinUnknown** [docker-library/wordpress#546]
5.6.40 is the latest patch version of PHP. However, when using the `php5.6` tag (specifically the `php5.6-apache` variant) the version of PHP inside the container appears to be 5.6.39. This causes problems when for example using WP CLI inside, as it checks with Composer what the requirements are. In my case, the min required version of PHP in my `composer.json` is PHP 5.6.40, because we want to support the latest patch version only. This fails WP installation using WP CLI with the following error:

> Your Composer dependencies require a PHP version ">= 5.6.40". You are running 5.6.39.

I know that 5.6 is EOL, but WordPress seems to still support PHP 5.6, so it would make sense to maintain the latest patch version of that in the image for the time being. Could you kindly update please? 🙏

**Comment by tianon** [comment]
As you've noted, PHP 5.6 is EOL, and is not receiving any official updates from the PHP community (security, bugfix, or otherwise), so I think it would be a pretty unfortunate misrepresentation of "supported" for us to continue to publish those. :confused: :disappointed:

I imagine WordPress still supports it for the use cases of stable distributions (who may not be off PHP 5.6 yet but still need supported and secure WordPress) and shared hosting (where the PHP version is typically less easily controlled by the user).

**Comment by XedinUnknown** [comment]
I'm not sure why my interpretation of "supported" would be wrong. WP says they support it [here][1].

[1]: https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php

**Comment by yosifkit** [comment]
> WordPress does work with PHP 5.6.20+. **Versions prior to PHP 7.2 are not recommended because it doesn’t have support of any kind**, and only use PHP 7.2.x if you have the latest version, since it only has security support.
>
> (emphasis added) https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php

**Comment by XedinUnknown** [comment]
By "it doesn’t have support of any kind", they mean support by PHP, not by them.

Either way, here's what's confusing. There must be some minimal requirements for the software. When I asked for the minimal PHP requirement, [I was pointed to that line about PHP 5.6.20+][1]. So I guess, that's the minimal requirement. If the minimal requirement is supported (duh), then there must be IMHO a way for people to use the official image at that minimal requirement. Alternatively, if it is not supported, it should not be a minimal requirement.

[1]: https://twitter.com/Rarst/status/1348581743444566017
