### ISSUE TITLE
Missing 5.5.2- and 5.5.3- tags on docker hub

### ISSUE THREAD

**Issue by korridor** [docker-library/wordpress#547]
I am not sure if this is the right place to report this, but Wordpress released `5.5.2` and `5.5.3` a few days ago (https://wordpress.org/download/releases/), but I cannot find any `5.5.2-` or `5.5.3-` tags on docker hub. (https://hub.docker.com/_/wordpress) It seams like the `latest` tag was updated though.

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/26689068/97810059-7aad6c00-1c71-11eb-979d-1373ed7a9a95.png">

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/26689068/97810115-ce1fba00-1c71-11eb-989a-1ebbaa3288b9.png">

**Comment by wglambert** [comment]
https://github.com/docker-library/wordpress#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

https://github.com/docker-library/wordpress/commit/5125491823651bcd691faf415d836f911fea09cd

The update hasn't been pushed to Github yet, a PR will be up shortly https://github.com/docker-library/official-images/labels/library%2Fwordpress

**Comment by korridor** [comment]
Thanks for the information! The 5.5.3 tags were in the DockerHub shortly after.
