### ISSUE TITLE
Create a Helm Chart for this container

### ISSUE THREAD

**Issue by eherot** [docker-library/wordpress#548]
Fairly self explanatory. [Helm Charts](https://helm.sh/docs/topics/charts/) make it easier to deploy containers on Kubernetes. There is already one for the Bitnami Wordpress container and it is very handy but for various reasons I prefer to use this one.

**Comment by wglambert** [comment]
We have no affiliation to any Helm Charts, they're their own program/organization
https://github.com/helm/charts#owning-and-maintaining-a-chart

While we understand that many users deploy using Helm Charts, we unfortunately do not have the bandwidth or interest in maintaining one.  However, this would be a great community project!

**Comment by eherot** [comment]
I'm actually working on one right now for the company that I'm doing this install for. If there's enough extra bandwidth in this process I will try to upstream it!

**Comment by tianon** [comment]
To be clear, we don't want it maintained here as it will suffer permanent bitrot (we will not maintain or update it over time), and that would be doing our community a disservice, I think.

**Comment by eherot** [comment]
I suppose that is a bit of a philosophical question. For me (and a lot of other folks with Kubernetes as the infrastructure management platform), "does it have a helm chart" is quickly becoming the deciding factor when choosing an application. At the same time, locally maintained Helm charts have become a lot more common (With Helm pushing people to do more self-hosting of chart repositories).

**Comment by tianon** [comment]
Closing, as a helm chart is not something we are comfortable with / going to maintain here.  Sorry! :heart:

**Comment by eherot** [comment]
It's ok. I can only wish that all of my feature request rejections were so friendly. 😁
