### ISSUE TITLE
recommended way for installing apk packages

### ISSUE THREAD

**Issue by zanona** [docker-library/wordpress#549]
Hi,
I would like to perform some tests from `worpress:cli` which require some additional dependencies such as jq.
Unfortunately I cannot run `apk add jq` as `www-data`, so I was wondering what would be the advised way of installing these extra dependencies while using the same image.

Thanks.

**Comment by wglambert** [comment]
You could run it as root 
```console
$ docker run -it --rm --user root wordpress:cli ash
/var/www/html # apk add --no-cache jq
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing jq (1.6-r1)
Executing busybox-1.31.1-r19.trigger
OK: 58 MiB in 59 packages
```

**Comment by zanona** [comment]
@wglambert thanks for the suggestions. That works nicely locally but whenever I need to run on CI (using drone.io at the moment), I'm afraid I can't run as root unfortunately.

**Comment by wglambert** [comment]
You could make a Dockerfile that temporarily changes to root and then back again to www-data after installing the packages
```console
$ docker build -t wordpress:test - << EOF
> FROM wordpress:cli
> USER root
> RUN apk add --no-cache jq
> USER www-data
> EOF
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM wordpress:cli
 ---> 58f91ceba42b
Step 2/4 : USER root
 ---> Running in 4b9ae0cdbc68
Removing intermediate container 4b9ae0cdbc68
 ---> 1ca0c091a3e7
Step 3/4 : RUN apk add --no-cache jq
 ---> Running in 6f31da070e1c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing jq (1.6-r1)
Executing busybox-1.31.1-r19.trigger
OK: 58 MiB in 59 packages
Removing intermediate container 6f31da070e1c
 ---> cbe26b776c9a
Step 4/4 : USER www-data
 ---> Running in 3abe20977507
Removing intermediate container 3abe20977507
 ---> be8cd9692492
Successfully built be8cd9692492
Successfully tagged wordpress:test

$ docker run -it --rm wordpress:test ash
/var/www/html $ whoami
www-data

/var/www/html $ which jq
/usr/bin/jq
```

**Comment by zanona** [comment]
Sounds great! Thanks a lot for the example.

I wasn't sure if this was the only way at the moment. I will create my own image for performing those tests then. 

May I also ask if there's any particular reason for running as www-data?

**Comment by wglambert** [comment]
Sorry for the late reply, web servers typically run as the `www-data` user by default as it's good security in a non-container environment.
https://askubuntu.com/questions/873839/what-is-the-www-data-user

You can run as any user you want though https://github.com/docker-library/docs/tree/master/wordpress#running-as-an-arbitrary-user

Closing since this seems resolved
