### ISSUE TITLE
Wasted space due to PHP archive in /usr/src

### ISSUE THREAD

**Issue by weleoka** [docker-library/wordpress#563]
Looking at the image after starting and entering:
( from image: wordpress:5.6.0-fpm-alpine wordpress@sha256:9f70cb4f0bf188b11bdb239e92e738157a15039892ad63c18a78e8a0cf188488 )
```
bash-5.1# ls -lh /usr/src
total 10M    
drwxrwxr-x   16 root     root        4.0K Jan  5 10:45 php-7.4.14
-rw-r--r--    1 root     root        9.8M Jan 16 00:13 php.tar.xz
-rw-r--r--    1 root     root         833 Jan 16 00:13 php.tar.xz.asc
drwxr-xr-x    5 www-data www-data    4.0K Jan 16 02:50 wordpress
```

Possibly could remove `php.tar.xz` from image. The current image size is: 
```
$ docker image ls
. . .
wordpress-docker_wordpress2         latest              6dab5d715c9b        10 hours ago        248MB
```

**Comment by tianon** [comment]
Unfortunately, we can't remove it; see docker-library/php#488, docker-library/php#886, docker-library/php#1043
