### ISSUE TITLE
Opening Plugins/Themes "Add New" menu causes an issue with wordpress:5.6.0-php8.0-fpm-alpine

### ISSUE THREAD

**Issue by roman-wedemeier** [docker-library/wordpress#564]
Trying to setup a docker-compose wordpress service with mysql and nginx, using fpm and alpine. So far everything works great. Thank you very much by the way.
But when i click on "Add New" button in either Plugins menu or Themes menu, the following error message appears: "An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums."
I am new to Wordpress and nginx, so i thought, that i misconfigured something. To investigate the problem i changed the used image from "wordpress:5.6.0-php8.0-fpm-alpine" to "wordpress:5.6.0-php8.0-fpm" as there is Buster with bash inside, which is more familiar to me. Unfortunately, with the Buster image, the error disapeared and i can search the Plugins/Themes. I cannot see any further error-logs. Neither in wordpress, in nginx or in chrome console.

I would be grateful for any help.

Please tell me, if you need any more information. If needed i can give access to the gitlab repo with the files needed to reproduce the error.

Kind regards

**Comment by wglambert** [comment]
Hmm, no descriptive errors makes it hard to troubleshoot. If it's Alpine only it might be some sort of incompatibility with `musl` https://github.com/docker-library/docs/tree/master/php#phpversion-alpine
>The main caveat to note is that it does use [musl libc](https://musl.libc.org) instead of [glibc and friends](https://www.etalabs.net/compare_libcs.html), so certain software might run into issues depending on the depth of their libc requirements.

**Comment by yosifkit** [comment]
Are you mounting a local directory for WordPress?  Have you checked permissions? Maybe run as a different user? (https://github.com/docker-library/docs/tree/fbb3975628a650e4fcb1d3aa2ff4157b2513bffa/wordpress#running-as-an-arbitrary-user)

The Alpine-based image runs as a different user than the Debian-based one:
```console
$ docker pull wordpress:fpm
fpm: Pulling from library/wordpress
a076a628af6f: Pull complete 
02bab8795938: Pull complete 
657d9d2c68b9: Pull complete 
f47b5ee58e91: Pull complete 
dc152f065fb4: Pull complete 
641e98b3500c: Pull complete 
cca1f6a2664d: Pull complete 
93ba0890a07e: Pull complete 
b57ca04a5232: Pull complete 
a67418864aed: Pull complete 
453869c6d2e8: Pull complete 
502164c8c8a6: Pull complete 
4e5ff08c0ef7: Pull complete 
897972b6b4fd: Pull complete 
63cd1075b8a7: Pull complete 
cf8d4eaeafa9: Pull complete 
Digest: sha256:5a2a3af57f712c3609348d8b52789963a22dc665f1dfcbdf04a1b115839635c7
Status: Downloaded newer image for wordpress:fpm
docker.io/library/wordpress:fpm
$ docker run -it --rm wordpress:fpm grep www-data /etc/passwd
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
$ docker pull wordpress:fpm-alpine
fpm-alpine: Pulling from library/wordpress
596ba82af5aa: Pull complete 
af74f285bb27: Pull complete 
2ab8440e5667: Pull complete 
64889fa545ec: Pull complete 
1574f57dd747: Pull complete 
9eb0b6a13f93: Pull complete 
fc6edb18b173: Pull complete 
5bf63a6c9649: Pull complete 
ec352a4611cb: Pull complete 
682a80dc7ae1: Pull complete 
69dd49c871fd: Pull complete 
b5c6fd9c728f: Pull complete 
4d5ae4968d45: Pull complete 
c9fec89f4245: Pull complete 
7fc7f1f31960: Pull complete 
e3d151434e9a: Pull complete 
Digest: sha256:262bbd8a2c822b9e2e83e47de92a3fdfffe515fc4805c6a455396405bc53a64c
Status: Downloaded newer image for wordpress:fpm-alpine
docker.io/library/wordpress:fpm-alpine
$ docker run -it --rm wordpress:fpm-alpine grep www-data /etc/passwd
www-data:x:82:82:Linux User,,,:/home/www-data:/sbin/nologin
```

**Comment by wglambert** [comment]
Were you able to resolve this?
