### ISSUE TITLE
When I create a wordpress container I can't add folders/files in themes/plugins

### ISSUE THREAD

**Issue by bckelley** [docker-library/wordpress#568]
When I run the container with volume to the hosts user directory from the containers /var/www/html directory and list the permissions they're set to www-data:www-data which doesn't allow users to edit files or folders.

Is this even possible? How would I go about implementing something like this?

**Comment by bckelley** [comment]
so i just tried changing permissions listed out the folder and it's full of question marks! Useless!

**Comment by tianon** [comment]
I understand you're frustrated and have likely spent a lot of time trying to get this working, but taking that anger out on the open source maintainers who are trying to help you doesn't really motivate us to continue trying.  Please adjust your tone if you'd like to continue collaborating here.

**Comment by bckelley** [comment]
**For anyone in the future that may have this issue I had to fix it with this:**

`sudo chown -R $(id -u) www`
