### ISSUE TITLE
Problem with wp-config.php file

### ISSUE THREAD

**Issue by kasztof** [docker-library/wordpress#573]
Hi, 
we were using wp-config-sample.php file to keep some project specific variables e.g.

`define( 'SFTP_PATH', dirname( __FILE__ ) . '/sftp' ); `

Everything was working fine, however today when the project was rebuilt, I got an error in the logs, that one of our custom variables defined in wp-config-sample.php is undefined. Additionally at the start of the container there is this message:

> No 'wp-config.php' found in /var/www/html, but 'WORDPRESS_...' variables supplied; copying '/usr/src/wordpress/wp-config-docker.php' (WORDPRESS_AUTH_KEY WORDPRESS_AUTH_SALT WORDPRESS_CONFIG_EXTRA WORDPRESS_DB_HOST WORDPRESS_DB_NAME WORDPRESS_DB_PASSWORD WORDPRESS_DB_USER WORDPRESS_LOGGED_IN_KEY WORDPRESS_LOGGED_IN_SALT WORDPRESS_NONCE_KEY WORDPRESS_NONCE_SALT WORDPRESS_SECURE_AUTH_KEY WORDPRESS_SECURE_AUTH_SALT)

I just discovered that there was PR merged few days ago, introducing wp-docker-config.php. I checked the repo, and https://hub.docker.com/_/wordpress/ but I couldn't find any helpful documentation on this problem. Will I still be able to use the previous setup with wp-config-sample.php, or do I need to switch to wp-docker-config.php? If so, how can I define custom variables?

**Comment by swissspidy** [comment]
Could you just use `WORDPRESS_CONFIG_EXTRA` for that?

**Comment by tianon** [comment]
Indeed, `WORDPRESS_CONFIG_EXTRA` is the appropriate solution for additional configuration (or modifying the installed copy of `wp-config.php` directly, if you prefer).

**Comment by matzeeable** [comment]
Hey @swissspidy and @tianon !

I just stumbled over this, and we are using [`wp config set`](https://developer.wordpress.org/cli/commands/config/set/) in our Docker environment alot. Now, after our images got updated to the latest version, we can no longer use configuration set at runtime:

```
Error: Could not process the 'wp-config.php' transformation.
Reason: Unable to locate placement anchor.
```

I just tried a workaround and if I add `/* That's all, stop editing! Happy blogging. */` to the following line it works as expected: https://github.com/docker-library/wordpress/blob/1d90641dc2075168fe59df2f02502df068cc5531/wp-config-docker.php#L112

**Comment by tianon** [comment]
Yep, sounds like you're running into what caused https://github.com/WordPress/WordPress/commit/cbcd3ffef303d4beb83910bd2b5aa4ba58948dc0 (which we've applied in https://github.com/docker-library/wordpress/commit/1d90641dc2075168fe59df2f02502df068cc5531 but not quite published yet).

Given it's breaking WP-CLI, I've opened https://github.com/docker-library/official-images/pull/10227 to get that comment change pushed out.
