### ISSUE TITLE
504 gateway timeout when upload/delete plugins

### ISSUE THREAD

**Issue by yongzhang** [docker-library/wordpress#579]
image version: 5.7.0-php7.4
Container was deployed inside k8s, behind traefik ingress.

Issue:
When I upload a plugin zip file and install, the browser will show 504 gateway timeout after a while,
but after that, if I go back to the plugin list page and refresh the page, I can find the plugin was installed.
Then I delete the plugin, it will stuck at "deleting", but after refreshing the page, plugin disappeared.
I don't understand what's happening here, please help. Thanks.

**Comment by wglambert** [comment]
Is there anything in the `kubectl logs`?
