### ISSUE TITLE
Wordpress instance doesn't have permission to update wp-config.php

### ISSUE THREAD

**Issue by trongthanh** [docker-library/wordpress#586]
I'm building a custom docker image from `wordpress:latest` and recently, my newly deployed Wordpress site could not update its `wp-config.php`. (Usually it is required by plugins, such as wp-super-cache). Checking the file permission of `wp-config.php` in the container, I saw that it is owned by `root`, while the rest of the folder is own by `www-data`.

The first logs from the container has this note regarding wp-config.php:

```
No 'wp-config.php' found in /var/www/html/, but 'WORDPRESS_...' variables supplied; copying 'wp-config-docker.php' (WORDPRESS_CONFIG_EXTRA WORDPRESS_DB_HOST WORDPRESS_DB_NAME WORDPRESS_DB_PASSWORD WORDPRESS_DB_USER)
```

This issue didn't happen before, and my best guess is that `wp-config.php` getting wrong permission when being generated from wp-config-docker.php.

Edit:

My current workaround is in my custom `entrypoint.sh`, I'm copying `wp-config-docker.php` to `wp-config.php`, before executing the image's main entry point .sh file:

```
# other customization and set up...

# copy wp-config early here to avoid permission issue
cp -f /usr/src/wordpress/wp-config-docker.php /usr/src/wordpress/wp-config.php

# Execute the Wordpress Docker entrypoint
docker-entrypoint.sh apache2-foreground
```

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by yosifkit** [comment]
Ah, it looks like we need to switch to the "$user" for writing to the file: 

https://github.com/docker-library/wordpress/blob/0f81a039c67da94bee5c8c89573efd9d829f4e6b/docker-entrypoint.sh#L76-L84
