### ISSUE TITLE
Fatal error: getenv_docker redeclare with wordpress+wpcli compose setup

### ISSUE THREAD

**Issue by GoldenMickey** [docker-library/wordpress#588]
Hello,
First of all, thank you guys for your work. Those docker images are lit.

I have a setup to automate wordpress custom installations using docker-compose with wordpress and wpcli containers. It builded fine since a few days ago. When deploying to my production environment, it now breaks on the following error :

`Fatal error: Cannot redeclare getenv_docker() (previously declared in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code:26) in /var/www/html/wp-config.php on line 27`

However, I can still build on my staging environment because it still uses older images of the containers. The breakup happening after flushing and rebuilding images makes me think recent updates on your guys end might be the cause.

Build context:
- wordpress image: wordpress:php7.4-fpm-alpine
- wpcli image: wordpress:cli-php7.4
- a local directory is mounted as a shared volume on /var/www/html between the wordpress and wpcli containers
- the wordpress installation is handled by wpcli using `wp core install`
- the wordpress installation is wiped and reinstalled on each new run

I noticed the wp-config.php generated on my staging environment (with the older images) doesn't have the `getenv_docker` function declaration while the new one does.

Do you think it is a legit issue or might it come from my setup?

**Comment by GoldenMickey** [comment]
For anyone also stuck with this, for now I'm fixing the version of my wordpress dockerfile using the digest of the image from my staging environment:

`FROM wordpress:php7.4-fpm-alpine@sha256:438a4786042e0419bb52e2ec1906f266eaeeacc4a8d4b06afc63dfc0c89d4d00`

**Comment by yosifkit** [comment]
It looks like we need to improve the `getenv_docker` function to check for itself before definition.

I'd note that it seem strange to run `wp core install` on an already initialized database, but I guess it is idempotent enough.

**Comment by itkhansunny** [comment]
is it fixed?

**Comment by tianon** [comment]
The issue described here was fixed in the PR that closed this issue (#590), yes.
