### ISSUE TITLE
$_SERVER[ 'HTTP_HOST' ] returns "wordpress"

### ISSUE THREAD

**Issue by markorosic** [docker-library/wordpress#59]
Hi,

Yesterday I've been trying to setup WPML and found that it is "broken" and couldn't finish the setup. It turned out that the plugin relies on $_SERVER[ 'HTTP_HOST' ] and in my case instead of 192.168.59.103 it returns "wordpress" which breaks the functionality.

Is there a way other than hardcoding it in wp-config.php to pass the IP, or there is some other solution. I'm using fig.

Thanks,
Marko

**Comment by md5** [comment]
The `HTTP_HOST` variable is set by PHP based on the incoming `Host` header.

What's the actual error you received? Debugging this may not be something that anyone can help you with easily since WPML appears to be proprietary software and the source code is not readily available for review.

**Comment by markorosic** [comment]
There is no error that I noticed except the whole plugin is broken as it is referencing non existing files... here are the lines that are causing the issue in sitepress.php:

Line 19:

    define( 'ICL_PLUGIN_URL', filter_include_url( rtrim( plugin_dir_url( __FILE__ ), DIRECTORY_SEPARATOR ) ) );

Line 42:

    function filter_include_url( $result ) {
    	$http_host_parts = explode( ':', $_SERVER[ 'HTTP_HOST' ] );
    	unset( $http_host_parts[ 1 ] );
    	$http_host_without_port = implode( $http_host_parts );
    	$path                   = str_replace( parse_url( $result, PHP_URL_HOST ), $http_host_without_port, $result );
    	return $path;
    }

ICL_PLUGIN_URL is widely used and instead of boot2docker IP it is getting http://wordpress/wp-content/...

**Comment by md5** [comment]
Where is `PHP_URL_HOST` set? That's not set by Wordpress itself as far as I can tell.

**Comment by markorosic** [comment]
This is irrelevant for the issue as far as I can see. Regardless of the plugin if I echo $_SERVER[ 'HTTP_HOST' ] on the index.php I get "wordpress" instead of IP.

**Comment by md5** [comment]
Alrighty then... Perhaps someone else might be interested in helping you.

**Comment by markorosic** [comment]
Thanks for the help anyway :)

**Comment by markorosic** [comment]
If anyone stumbles upon this problem, this little hack did it for me. Add the following line to wp-config.php:
	$_SERVER[ ‘HTTP_HOST’ ] = explode(‘/‘, $_ENV[‘WORDPRESS_URL’])[2];
