### ISSUE TITLE
wrong permissions of wp-config.php after copy-routine in docker-entrypoint.sh

### ISSUE THREAD

**Issue by juliusczar** [docker-library/wordpress#591]
hi guys,

thanks for your awesome work.
i've encountered a little bug and would like to mention it here:

**problem**:
the part of docker-entrypoint.sh which is copying the wp-config-docker.php to wp-config.php (https://github.com/docker-library/wordpress/blob/f5389a9a0cb963b3cd7f99484308428a14920790/docker-entrypoint.sh#L71) creates the wp-config.php with user/group root:root and the php process cannot read it.

**tested environment**:
wordpress:5.7-php7.4-fpm-alpine

**debug**:
if i start the image with explicit user 82:82, the docker-entrypoint.sh gets executed as www-data and the resulting wp-config.php is created as www-data:www-data, php can access it and everything is working fine

**maybe-solution**:
i think it would be great to extend the check in line 88 (https://github.com/docker-library/wordpress/blob/f5389a9a0cb963b3cd7f99484308428a14920790/docker-entrypoint.sh#L88) a bit to fix the permissons of the created wp-config.php file if the image is executed as root (which of course should be avoided at best, but which is the standard behaviour today, if iam not wrong)

i would love to contribute a clean fix and a PR at best, unfortunately my time is extremely short at the moment and i don't want to deliver a half-baked solution

thanks in advance!

**Comment by wglambert** [comment]
Duplicate of https://github.com/docker-library/wordpress/issues/586

[The fix](https://github.com/docker-library/wordpress/pull/587) was was pushed to Docker Hub yesterday https://github.com/docker-library/official-images/pull/9833

**Comment by juliusczar** [comment]
crap, should have looked better!
thanks!

**Comment by juliusczar** [comment]
just wanna leave this here (for others with the same problem):

if you are using the wp-cli docker image - with the new getenv_docker function - one had to make sure the wp-cli container also gets passed the environment variables, otherwise its parses the wp-config.php and falls back to the defaults because the wp-cli container doesnt have the environment variables.
