### ISSUE TITLE
Nginx + PHP-FPM

### ISSUE THREAD

**Issue by sammcj** [docker-library/wordpress#60]
It would make sense to move this to running on Nginx + PHP-FPM as not only would it be faster, scale better but also result in a smaller Docker image.

**Comment by md5** [comment]
This was discussed in https://github.com/docker-library/php/issues/54

The approach discussed there was having a `wordpress:fpm` image and a separate image based on `nginx` that fronted it.

I cut a branch over at https://github.com/md5/docker-wordpress/tree/add-fpm-variant that would add a `wordpress:fpm` image variant, but never got it into PR-ready shape. See [this gist](https://gist.github.com/md5/d9206eacb5a0ff5d6be0) for an example Nginx setup that could front the `wordpress:fpm` container.

**Comment by md5** [comment]
I've updated my branch to be closer to PR-ready: https://github.com/md5/docker-wordpress/compare/add-fpm-variant

I think the only remaining thing is to get the `generate-stackbrew-library.sh` script generating the correct file for the `official-images` repo. The last remaining bit is to get the script to output the non-suffixed tags like "4.1.0" for the "apache" variant and to output a "latest" tag. Perhaps @tianon will have a minute to get to that before I do.

**Comment by md5** [comment]
I opened a PR at #61. See here for the whitespace-ignoring diff: https://github.com/docker-library/wordpress/pull/61/files?w=1
