### ISSUE TITLE
Owner of /var/www/html keeps getting reset to 1001

### ISSUE THREAD

**Issue by siddjain** [docker-library/wordpress#605]
When I create my container I make `www-data` the owner of `/var/www/html` and everything inside it but it keeps getting reset to `1001` after sometime. I haven't been able to figure out who is doing this. Has anyone experienced this and know the solution?

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by siddjain** [comment]
found the culprit. It was `docker cp`. I was restoring the site from a backup and running `docker cp`. Understandably the container does not know the user and group and so sets it to:

```
-rw-r--r--    1 48081    101              1 May  1  2020 wp-debug-test.log
```

as example. you can close the ticket.
