### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by danvy** [docker-library/wordpress#607]
Hi,
Is there any particular reason to not support WebP out of the box ?

**Comment by tianon** [comment]
It's not supported by WordPress upstream, AFAIK:

- https://core.trac.wordpress.org/ticket/35725
- https://core.trac.wordpress.org/ticket/35726
- https://core.trac.wordpress.org/ticket/43023

**Comment by davidkryzaniak** [comment]
I think it's pretty safe to close this one. WebP will be natively supported by WP very soon: https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/

**Comment by tianon** [comment]
That's great news! :smile: :+1:
