### ISSUE TITLE
Update to latest upstream config to include reverted change in WordPress trunk

### ISSUE THREAD

**Issue by oskosk** [docker-library/wordpress#610]
Some days ago a change was introduced in WordPress trunk on a comment in the sample config file which could potentially break automation processes that relied on matching that comment. No WordPress release has come out yet and [that change has been reverted 4 days ago](https://github.com/WordPress/WordPress/commit/cbcd3ffef303d4beb83910bd2b5aa4ba58948dc0), so the problem won't be there in official releases.

**But** some of the images built here as `latest` have been built 5 days ago including https://github.com/docker-library/wordpress/commit/16151c9fb776b1b83fd9275eac48278890824620#diff-9c0b10d9c6ed5948e9d256a9d509c03163e8526ce9acb925f9c4a9fcce6f8117, before the revert was merged. Thus containing the wrong comment:  e.g. https://github.com/docker-library/wordpress/blob/1d90641dc2075168fe59df2f02502df068cc5531/latest/php7.4/fpm-alpine/wp-config-docker.php#L112

cc @tianon 

AFAIK the current sate of `:cli` has the ability to break some script runs relying on the aforementioned comment

Thanks in advance!

**Comment by tianon** [comment]
See https://github.com/docker-library/wordpress/issues/573#issuecomment-847238980:

> Yep, sounds like you're running into what caused [WordPress/WordPress@cbcd3ff](https://github.com/WordPress/WordPress/commit/cbcd3ffef303d4beb83910bd2b5aa4ba58948dc0) (which we've applied in [1d90641](https://github.com/docker-library/wordpress/commit/1d90641dc2075168fe59df2f02502df068cc5531) but not quite published yet).
> 
> Given it's breaking WP-CLI, I've opened [docker-library/official-images#10227](https://github.com/docker-library/official-images/pull/10227) to get that comment change pushed out.

That's merged now, and fixed builds are in-queue or in-progress.

**Comment by oskosk** [comment]
Thank you!
