### ISSUE TITLE
Play with Docker (PWD) Sample on https://hub.docker.com/_/wordpress info page is not helpful. 

### ISSUE THREAD

**Issue by zipzit** [docker-library/wordpress#614]
I'm having a particularly difficult time getting my docker compose site setup.  I know, great idea, I'll study up on the details right from the [source at Docker Hub. ](https://hub.docker.com/_/wordpress)   Decent write up, makes a whole lot of sense.  

Right there at the bottom is exactly what I'm looking for, a docker compose setup for integrating a mysql database with the Wordpress docker container.  Awesome.   And there is even a Play With Docker (PWD) push button link to do a rapid test.  

Push the button (actually right click open in new tab) ... things look right.  I see a popup that indicates the containers are being downloaded, etc.. but at the end of the period, total fail.   Anybody else have this issue?  

Session stack builder Popup
```
We are building your stack. This might take a while.
Swarm initialized:....   
Pulling wordpress  ... done,    
Pulling db ... done   
Ignoring unsupported options: restart
```
Your session is ready!
I'm using Chrome on Windows 10.  I've also tried Microsoft Edge.  Essentially same results.  Nothing to see?  I would assume I would have been able to see the Wordpress startup screen, in the browser somehow, somewhere with an instruction set on how to get there if not immediately intuitive.  

Am I doing this correctly?  My suspicion is that there is something funky going on with wp-config-docker.php and wp-config.php both in the sample and in my project, using `image:   wordpress:latest`  Anybody else been here?  

Please test yourself.  
1) go to https://hub.docker.com/_/wordpress
2) scroll down to the light blue button "Try in PWD". Push the button.
3) You will see a popup box that prompts you to Login to Docker. Provide your credentials.
4) Let the system run until you get "Your session is ready!"
5) Navigate to http://swarm-ip:8080,  http://localhost:8080, or http://host-ip:8080

Total fail for me.  Am I even doing this right?    many thanks...

**Comment by wglambert** [comment]
Yeah that's odd, unfortunately we don't have any control over or involvement with that particular feature on Dockerhub, as a workaround you can do it manually by going to https://labs.play-with-docker.com and pasting a `docker-compose.yml` to bring up.

When I first tried it I encountered the same issue you did, on the second time it actually worked for me though and looked like this
![06_01_21 @1_06_50](https://user-images.githubusercontent.com/26428991/120383988-6e0df680-c2da-11eb-9c8b-c0d2b4696c3e.png)

I wasn't able to close the popup normally but refreshing the page made it go away, then I could click the `8080` button and got a new tab with the WordPress install
![06_01_21 @1_08_04](https://user-images.githubusercontent.com/26428991/120384087-91d13c80-c2da-11eb-84b3-a6003aea21a7.png)

**Comment by zipzit** [comment]
pasting a docker-compose.yml to bring up.?  I opened up the sandbox in the browser, but I have absolutely no clue as to how to add my .env and .yml files to that workspace.   I can get the command line SSH to work, but not much beyond that.  `nano` is a fail.  Are you using some old skool command line FTP to push your docker-compose file to the sandbox?  I see a button for "editor" but that doesn't seem to do much.    I'd like to understand that..    I'm guessing I can search youtube and find something.

In the meantime, I realize I can just use the code located at https://raw.githubusercontent.com/docker-library/docs/456252a739783650c79bd1f6a7a19101fbecfc65/wordpress/stack.yml, and bring that into my own terminal shell /docker command line environment.  And that works just fine right out of the box.  I'm at a total loss to understand why my code fails, but that sample works, so I'll nibble in my updates one line at a time and see what causes the hiccups.  (My code includes other alpine static servers, adminer graphic user interface to the database and jwilder/nginx-proxy to manage the sites on a single  server.)

thank you for the response above.  That gives me hope.

**Comment by wglambert** [comment]
Well the easiest way is to just ctrl+c the `stack.yml` to your clipboard and paste it in the play-with-docker instance with `vi docker-compose.yml` and shift+insert (paste) basically

**Comment by zipzit** [comment]
"vi" eech, blech, ugh, oooof.  Now you are talking religion.  True believer stuff.  Yowza. You rock!  I'm not worthy.  Nano is my buddy.

**Comment by zipzit** [comment]
And with that in mind, the sample code at  https://raw.githubusercontent.com/docker-library/docs/456252a739783650c79bd1f6a7a19101fbecfc65/wordpress/stack.yml works well.  Well enough to close this issue as "the root cause for this issue is related to Play With Docker, and that tooling is out of this repo's control..." .  Everybody okay with that?
