### ISSUE TITLE
Add XDebug to the image

### ISSUE THREAD

**Issue by progonkpa** [docker-library/wordpress#629]
I'm missing XDebug in these great images.
Surely, nobody cares about the extra 211Kb which is the size of XDebug.
Yet, every PHP developer wants to be able to debug.

I propose to add it to the Dockerfile with one env var for the version number and another as a a toggle to switch XDebug on or off. That would be great.

True, It's no big effort for us to extend the Dockerfile as this is how I solve it now.
It's just more sloppy.
Kind regards.

**Comment by tianon** [comment]
I would argue that most production users *don't* want XDebug in their production images -- along that line, it's pretty trivial to add after the fact, but it's impossible to actually remove.

**Comment by progonkpa** [comment]
@tianon I think indeed it's likely many don't want xdebug in production.

Therefor I'd do something like
if [ ${XDEBUG:-0}  ]; then run pecl install ...

**Comment by yosifkit** [comment]
> add it to the Dockerfile with one env var for the version number and another as a a toggle to switch XDebug on or off.
> extend the Dockerfile as this is how I solve it now.

It sounds like you are editing one of the WordPress Dockerfiles when it should be quicker to use a separate one with a `docker build -pull -t custom-wp .`:

```dockerfile
# pick a version
FROM wordpress:x.x
# install your php extensions
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug
```

If using an alpine-based image, then you'd likely need to install (and remove) any build dependencies in the single `RUN` line.

**Comment by progonkpa** [comment]
@yosifkit I'd argue `docker build --build-arg XDEBUG ...` for a development box is quicker than your proposition, while in production a regular `docker build` call which would skip the XDebug stuff.

I don't understand what you said about alpine-based single `RUN` line.
One cannot have two `RUN apk add` lines in an alpine Dockerfile?

**Comment by tianon** [comment]
It's faster for you to completely rebuild the entire `wordpress` image from scratch and then install XDebug than it is for you to `docker pull wordpress` and only install XDebug? :grimacing:

**Comment by progonkpa** [comment]
I think I get your point now. I had an error in my thinking.
I figured when you pull, you pull the Dockerfile and it builds on your machine but that's incorrect.
You pull a prebuild container. It's only downloading, no building.
In that case, you're totally right and this issue is a nothing burger.
