### ISSUE TITLE
Word press is not using default environment variables in docker container

### ISSUE THREAD

**Issue by deekshith-elear** [docker-library/wordpress#631]
Hi,
I'm using `WORDPRESS_DB_HOST` to provide my database host name as a environmental variable to my wordpress docker container. In My oldversion of docker image which is an year old it is able to work properly. now I want to migrate to 5.8 and getting database connection error. If I hardcode data of host it is working. else it is not fetching data.

Can anyone help  me to fix this issue?

**Comment by wglambert** [comment]
What do the `docker logs` show for the error?
