### ISSUE TITLE
Tried the wordpress image in 2 environments and am getting an error

### ISSUE THREAD

**Issue by crania** [docker-library/wordpress#66]
Here is the output from the docker logs:

Complete! WordPress has been successfully copied to /var/www/html
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
[Thu Mar 12 20:44:12.294365 2015] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.6 configured -- resuming normal operations
[Thu Mar 12 20:44:12.294449 2015] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

When I try and reach the container I get nothing back.  I'm guessing the server isn't serving on the correct IP for public traffic - what is the correct method to modify this? 

Appreciate the help.

**Comment by tianon** [comment]
Gonna need a little more information about how you're running the container. :smile:  Are you using boot2docker?  Are you mapping the ports publicly (`-p 80:80`)?

**Comment by crania** [comment]
Sure - I'm setting the MySQL environment variables and running -p 80:80

First environment was on boot2docker while the second was Docker running on an EC2 instance (Container Services) at AWS.  Docker ps shows the process running - that is the only log I get on startup.

**Comment by crania** [comment]
Please close this issue.  I had a bad security group defined and some other issue on boot2docker.  I think I made 2 mistakes somewhere along the line and concluded they were related which they were not.

Appreciate your time!!
