### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by phillip-elm** [docker-library/wordpress#665]
PHP 8.1 was officially released on Nov 25, 2021.

**Comment by tianon** [comment]
Depends on https://github.com/docker-library/php/pull/1227 :see_no_evil:

**Comment by phillip-elm** [comment]
@tianon ah, right. Looks like it has been merged since then and is now available.

**Comment by phillip-elm** [comment]
@tianon - thanks for doing that so fast!

I notice that PHP 8.1 isn't listed in the docker library yet. Does it normally take a day or so for the official repositories to update?

**Comment by tianon** [comment]
You probably want to read through https://github.com/docker-library/wordpress#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet to get a sense of the full process.

That will eventually lead you to https://github.com/docker-library/official-images/pull/11437 which is what gets it into the source-of-truth after which we're "just" waiting for the official build servers to crank out the builds (which might take a bit given there was an updated Debian image yesterday so the queue is pretty full).

**Comment by phillip-elm** [comment]
@tianon Oh my days it's highlighted on the readme 😳 Sorry I missed that and thanks for explaining. 

Looks like it's available now too.
