### ISSUE TITLE
Run apache with UID 1000

### ISSUE THREAD

**Issue by k0377** [docker-library/wordpress#67]
During development I mount /var/www/html to my host. I dont have permissions in there to change/add/delete files.

**Comment by md5** [comment]
I have an old branch of the `php:apache` base image where I tested running Apache as a different user, but I never opened a PR for it: https://github.com/docker-library/php/compare/master...md5:apache-run-user

That functionality could be used as the basis form switching the UID of the `wordpress:apache` image if it were to be merged.

**Comment by k0377** [comment]
Dont get me wrong, but how is this image usable without changing the default apache user? I dont know how others do edit their themes, configs while they develop on their own machine. Do I have to add myself to the group www-data and then chmod 775? But what about new created files in there, do they get the same 775 permissions? I just struggle with development, I just need to edit my files. Thanks for your help!

**Comment by k0377** [comment]
I'm already a member of group www-data but still cant create new files in there. =(

**Comment by k0377** [comment]
@md5 Thanks, I also set umask 002 in /etc/apache2/envvars. This seems to do the job at least for me!

**Comment by md5** [comment]
@k0377 I'm surprised that `/etc/apache2/envvars` has an effect. See this issue: https://github.com/docker-library/php/issues/97

**Comment by k0377** [comment]
@md5 of course, i replaced apache2 with apache2ctl.

**Comment by NerdsvilleCEO** [comment]
I'm confused as to what the solution was for this? When I change the UID (even after sed -i 's/exec apache2/exec apache2ctl/' /usr/local/bin/apache2-foreground) it has trouble binding to port 80
