### ISSUE TITLE
Environment variable for activating SCRIPT_DEBUG

### ISSUE THREAD

**Issue by glaand** [docker-library/wordpress#672]
Hello, is there a Env variable for activating SCRIPT DEBUG?

As i see, at the moment there is only one for WP_DEBUG which is WORDPRESS_DEBUG

Would be nice to have one for SCRIPT_DEBUG.

Best regards

**Comment by tianon** [comment]
I would suggest using `WORDPRESS_CONFIG_EXTRA` (which can be set to a block of arbitrary PHP code to get included in `wp-config.php`).
