### ISSUE TITLE
Update Apache version to 2.4.52

### ISSUE THREAD

**Issue by pourya-fathi** [docker-library/wordpress#676]
New vulnerability found on Apache:
https://httpd.apache.org/security/vulnerabilities_24.html
Please update the WordPress image Apache server

**Comment by wglambert** [comment]
Duplicate of https://github.com/docker-library/wordpress/issues/673 & https://github.com/docker-library/php/issues/1241

>Neither of these seem particularly relevant for the configuration in our image either -- one is only applicable if we have `ProxyRequests on` (which we do not, as far as I know) and the other only affects `mod_lua` (which we don't have/enable in the image).
