### ISSUE TITLE
Include mcrypt library

### ISSUE THREAD

**Issue by suchja** [docker-library/wordpress#68]
I'm not sure whether this is for the wordpress image or its parent image, but some of the wordpress plugins do require `mcrypt`. So what is the basic process of adding such libraries? Obviously I could create a personal image, but I would prefer to stay with the official image. On the other hand side I guess with all kinds of different libraries the images will get too large. Is there any definition what goes inside the official images and what stays out?
Thanks!

**Comment by md5** [comment]
The documentation on how to install more extensions is here: https://github.com/docker-library/docs/blob/master/php/README.md#how-to-install-more-php-extensions

It would be nice if this documentation as referred to from the `wordpress` documentation.

**Comment by yosifkit** [comment]
It seems reasonable to me for the WordPress image to have this php plugin enabled and ready to use.  Any thoughts @tianon?

**Comment by md5** [comment]
If you're going to add `mcrypt`, I think there are probably a few more extensions that should be added. I looked around for an official list and couldn't find one, but a number of posts on StackExchange and elsewhere referred to `iconv`, `mbstring`, `pspell`, and others.

Here are a couple of the links I looked at:

* http://wordpress.stackexchange.com/questions/42098/what-are-php-extensions-and-libraries-wp-needs-and-or-uses
* http://serverfault.com/questions/550520/which-php-modules-are-required-to-install-wordpress

**Comment by tianon** [comment]
I think trying to cater to "most" plugins is going to be a wild goose chase, personally.  I'm very much +1 to documenting this better though, especially referring to the existing PHP documentation.

Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with extra PHP extensions included (without bloating this image too much).

**Comment by tianon** [comment]
Unless, of course, we find an official "recommended" list from upstream. :+1:

**Comment by suchja** [comment]
@tianon, just to ensure that I understand you correctly. Unless we find an official list of recommended extensions, you propose to keep the image as it is and improve the documentation on how to extend it? That would mean anybody who needs `mcrypt` will use this official image as basis and creates a derived image which can be stored locally or in a personal DockerHub repository.
This is fine with me, because it fulfils one of my requirements which is to have a slim image. I'll have look whether I can get an official list of recommended extensions. Maybe we could have an extension branch/tag so anybody can choose whether size or functionality is more important.

**Comment by tianon** [comment]
Yeah, that's where my feeling is currently, but good arguments sway me easily. :+1:

In this case, since we don't have a clear set of extensions that are definitely required for plugins in general (or even recommended), I'm definitely much more supportive of erring on the side of caution.  Adding them later will be trivial, but culling the list back later will cause user pain (since things that were "just working" before now require more work on their part).

**Comment by md5** [comment]
I'll just note that some of the things in the links I referenced were for core WordPress functionality, not just to support what plugins *might* do.

**Comment by tianon** [comment]
If we're missing anything for core WordPress functionality, then by all
means, ++++ let's add it in! :+1:

Is "mcrypt" one of those that core WordPress uses?

**Comment by md5** [comment]
That looks like a negatory: https://github.com/WordPress/WordPress/search?utf8=%E2%9C%93&q=mcrypt

**Comment by k0377** [comment]
Include mbstring as well and all the other common modules. I dont know why you dont include those packages by default. Does it have any advantages over apache-php image? Just another image like "yeah we are on the docker train now"...

**Comment by suchja** [comment]
The supportive people on the WordPress Support Forum also state that nothing more than PHP and Mysql is needed. See the [list of requirements](https://wordpress.org/about/requirements/). Everything else is project specific. So I guess we stay with the current version.

@tianon what do you think about a branch/tag on top of latest with the requested extensions? In that branch we could add those extensions, which were previously requested here via an Issue. Not sure what kind of maintenance nightmare it might cause, but we might have a chance to fullfill both requirements.

Anyway, Do we need to enhance the documentation in docker-library/docs/WordPress?

**Comment by yosifkit** [comment]
Yes, docs would be nice :wink:.  I am not opposed to a "fat" version (name needs improvement), @tianon?

**Comment by suchja** [comment]
Will prepare an image with extensions mentioned here already and send you a pull request. Then you can make up your minds whether it is what you expect or not.

**Comment by tianon** [comment]
Yeah, I'm tentatively OK with a "fat" version if we can come up with a good
name for it.  My concern is around where we draw the line, because we don't
have a clear point at which a module is obviously common or not-common.
