### ISSUE TITLE
"latest" image doesn't contain WordPress 5.9

### ISSUE THREAD

**Issue by alvinjohnsonso** [docker-library/wordpress#686]
Checked out the build steps of the `latest` tag and found that the version is still set for `5.8.3`

https://hub.docker.com/layers/wordpress/library/wordpress/latest/images/sha256-f369848447128cd3fe7a5690f16175acf1de0a60575d83d058d887a23d97e2b8?context=explore

**Comment by yosifkit** [comment]
The most recent rebuild was because of the Debian bump (https://github.com/docker-library/official-images/pull/11739). Some architectures of the 5.9 release images have yet to build since the build queue has been full doing rebuilds.

**Comment by tianon** [comment]
See also https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what (which describes the full lifecycle).

**Comment by alvinjohnsonso** [comment]
Ahh alright. Thank you @yosifkit @tianon!
