### ISSUE TITLE
ERROR: no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by STV11C** [docker-library/wordpress#687]
Hi, I am trying to Pull latest Wordpress using **image: wordpress:5.9.0** but getting the following error:

ERROR: for wordpress  no matching manifest for linux/amd64 in the manifest list entries
ERROR: no matching manifest for linux/amd64 in the manifest list entries

Any help would be appreciated. Thanks!

**Comment by corentingiraud** [comment]
Same issue here. Might be a build problem as the README indicates:
![image](https://user-images.githubusercontent.com/29222996/151352845-4ebf3791-b195-4932-aa33-67fd267215e3.png)

**Comment by jasperroel** [comment]
Builds seem to be "stuck": https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/wordpress/

![image](https://user-images.githubusercontent.com/1370303/151382235-1f73f943-a0ba-4969-8833-a8393b7d6b3d.png)

**Comment by yosifkit** [comment]
Fortunately the job is not stuck; it is waiting for worker since the queue for some architectures is still quite full due to rebuilding all the images `FROM debian` after the Debian rebuild (https://github.com/docker-library/official-images/pull/11739).

**Comment by tianon** [comment]
See also https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what (which describes the full lifecycle).

**Comment by jasperroel** [comment]
They've all gone through and the images are available - thanks for explaining and linking to the relevant places @yosifkit and @tianon!
