### ISSUE TITLE
Adding php extension intl to existing WP updated containers

### ISSUE THREAD

**Issue by Danie10** [docker-library/wordpress#690]
I see issues were logged and closed for adding intl to the default container image. But many of us already run the WP updates from existing containers, which means we are not pulling a new container image. So after the recent WP update, the Site Health warning shows 'The optional module, intl, is not installed, or has been disabled'.

After lots of struggling I managed to get 'docker-php-ext-install intl' to execute (it had kept complaining about the 'icu-uc' dependency). So I needed to run `apt install libicu-dev` inside the container.

I restarted the container, and it seems to now be happy, as the Site Health is no longer showing a warning for the intl extension.

Hope this helps anyone else and saves them the two hours I spent trying to figure it out.  If there is a better way, then maybe someone else can share that (not sure if pulling a new image would break our existing WP updated containers - even if they have their recommended external volumes mapped for data persistence).

**Comment by yosifkit** [comment]
If you are saving the entire `/var/www/html/` directory persistently in a Docker volume or host mount (and letting WP update itself), then pulling the new image and reusing that volume/mount will just give you any updated PHP + modules. It will not change anything in you already installed WordPress.

"Initialization" of `/var/www/html` is skipped if WordPress looks to already be there:

https://github.com/docker-library/wordpress/blob/1b7873367ec93d971105aa21a54185d889bbbee3/latest/php8.0/apache/docker-entrypoint.sh#L28

**Comment by Danie10** [comment]
Thanks, @yosifkit yes maybe I must try that then (after doing backup etc) as I see my external volume mount maps from /var/www/html.
