### ISSUE TITLE
Module 'intl' not installed makes site-health check complain

### ISSUE THREAD

**Issue by The-Judge** [docker-library/wordpress#695]
Wordpress lists the PHP extension 'intl' as one of it's recommended PHP modules at https://make.wordpress.org/hosting/handbook/server-environment/#php-extensions .

Wordpress' site health check lists it as a suggested improvement when it is missing, too.

Hence, the official Wordpress Docker Image seems to not have it available:

```
# docker-compose exec wordpress php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
imagick
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
...
```

Please add it to the official Wordpress Docker Image, to prevent a vanilla out-of-the-box Wordpress instance complaining about missing PHP modules.

This has been reported (and fixed?) in some issues already: 
#685
#688
#693
But somehow, it seems to get lost ... 🙀

**Comment by wglambert** [comment]
I don't get any issues with the site health on 5.9.2. Are you using an older version?
Can you show your docker logs, maybe there's some error in there but `intl` shows up for me under `php -m`

![image](https://user-images.githubusercontent.com/26428991/158442008-e4464041-7ed9-45c5-9809-9a9e2cd68898.png)



```
$ docker exec wordpress_wordpress_1 php -i | grep -i intl
/usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
intl
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

Using the `docker-compose.yml` from the docs https://github.com/docker-library/docs/tree/master/wordpress#-via-docker-stack-deploy-or-docker-compose

**Comment by tianon** [comment]
Indeed, see #688 where this was added, and is definitely enabled:

```console
$ docker run --rm --pull always wordpress php -m | grep intl
latest: Pulling from library/wordpress
Digest: sha256:32ccb8b70014a961c317cbeae7857c4040be7b3748219e451fae9a0e60c51010
Status: Image is up to date for wordpress:latest
intl
```
