### ISSUE TITLE
Proxy subdirectory to wordpress:fpm

### ISSUE THREAD

**Issue by joelchen** [docker-library/wordpress#70]
Hi,

I am having trouble with Nginx configuration to proxy a sub-directory to my wordpress:fpm container in Docker on CoreOS. I have combined information from [Nginx's website][1] as well as [gist][2] by @md5 to come up with the following without success:
```
upstream wordpress {
        server 172.17.42.1:3001;
}

server {
        listen 80;
        server_name sub.domain.com;
        root /var/www/html;
        index index.php;

        location /subdirectory {
                proxy_pass http://wordpress;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_set_header Host $host;
                try_files $uri $uri/ /subdirectory/index.php?$args;
        }

        rewrite /wp-admin$ $scheme://$host$uri/ permanent;

        location ~ [^/]\.php(/|$) {
                fastcgi_split_path_info ^(/subdirectory)(/.*)$;
                if (!-f $document_root$fastcgi_script_name) {
                        return 404;
                }
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
                #fastcgi_pass fpm:9000;
                fastcgi_index index.php;
        }
}
```
I had to comment fastcgi_pass fpm:9000; to prevent Nginx from crashing. I am running my container as such:
```
docker run --name="wordpress" --restart="always" --link mariadb:mysql -e WORDPRESS_DB_NAME=wpdb -p 3001:80 -d wordpress:fpm
```
Nginx container performing the proxy for all my sub-directories is run as follows:
```
docker run --name="nginx" -v /home/core/custom.conf:/etc/nginx/conf.d/custom.conf:ro -p 80:80 nginx:latest
```
Thank you.

Warmest Regards,
Joel

[1]: http://wiki.nginx.org/WordPress
[2]: https://gist.github.com/md5/d9206eacb5a0ff5d6be0

**Comment by md5** [comment]
I believe you need to use `--link wordpress:fpm` in the `docker run` command and uncomment the "`fastcgi_pass fpm:9000;`" line you commented out. Not sure if that will fix your problems or not, but the Nginx container needs to know how to connect to port 9000 on the `wordpress:fpm` container. Using `--link` is one option for doing this.

**Comment by md5** [comment]
Also, that `/subdirectory` stuff should be pointing at `fpm:80` in that case, not `172.17.42.1:3001`. It looks like "172.17.42.1" is the internal address of your Wordpress container, but you're using the externally mapped port to connect to it. You can use the internally exposed port 80 instead.

**Comment by joelchen** [comment]
Hi @md5,

How do I point /subdirectory to fpm:80 in the configurations?

172.17.42.1 is Docker's IP, and that is how I proxy inbound connections from the Internet to my other containers running other services. As Docker randomly assigns private IP addresses to containers, I could not use each container's private IP unless I can find a way to auto-synchronize the private IP addresses with Nginx whenever the containers restart, which will possibly have new private IP addresses.

Thank you.

Warmest Regards,
Joel

**Comment by md5** [comment]
What are you actually trying achieve with the `/subdirectory` thing?

In general, I'm just confused by what you're trying to do. You might want to have a look at https://github.com/jwilder/nginx-proxy though.

**Comment by md5** [comment]
To be clear, `jwilder/nginx-proxy` would not talk to `wordpress:fpm` directly, but it sounds like you're trying to make this Nginx config do double duty (as far as I can understand what your ultimate goal is).

**Comment by joelchen** [comment]
I'm trying to make http://sub.domain.com/subdirectory1 point to wordpress1 container, http://sub.domain.com/subdirectory2 point to wordpress2 container, and so on.

I would like to try and get it work with pure Nginx configurations, before exploring jwilder/nginx-proxy.

**Comment by md5** [comment]
In order to get the right IP addresses into your Nginx config, you'll need to either generate the config with the IP addresses like `nginx-proxy` does (using https://github.com/jwilder/docker-gen), link both containers to your Nginx container as `wordpress1` and `wordpress2` and use the `/etc/hosts` mechanism provided by Docker to resolve the names, or use a DNS-based mechanism to resolve the IP address (e.g. Consul or https://github.com/tianon/rawdns).

**Comment by md5** [comment]
I'll also add that `jwilder/nginx-proxy` doesn't yet sending different paths to different backends, though I have a long-open branch that might eventually be used to implement that feature.

**Comment by joelchen** [comment]
Thanks for sharing these information @md5.

To achieve what I want sounds difficult, as compared to when I could proxy_pass successfully with 172.17.42.1 on another [WordPress container][1], albeit I had to set Home (Site Address) to http://sub.domain.com/subdirectory, set Site URL (WordPress Address) to http://<static IP>:3001, and open port 3001 publicly.

Therefore I wonder what is making things difficult in this WordPress container. However, I could be using 172.17.42.1 the wrong way, perhaps abusing it for all my containers.

Is [this][2] the long-open branch you are referring to? As I was using a HHVM WordPress container that comes bundled with SQLite previously, I would also like to know whether there are plans to have an official wordpress:hhvm variant.

Thank you for your contributions.

Warmest Regards,
Joel

[1]: https://github.com/dorwardv/nginx_hhvm_wordpress_sqlite
[2]: https://github.com/md5/nginx-proxy

**Comment by md5** [comment]
The branch is here: https://github.com/md5/nginx-proxy/tree/multiple-paths

I definitely think that what you're doing with 172.17.42.1 is not a recommended way to do things. I also don't think that what you're trying to achieve is too difficult. It's just that you either have to do some work to let the IP discovery happen via DNS in some way, you have to statically provide it via `--link`, or you have to rewrite the conf file when the IPs change.

As for a `wordpress:hhvm` variant, this is the first time I've seen one mentioned. There isn't an official `hhvm` image to base it on, so that would have to be a first step.

**Comment by md5** [comment]
It actually looks like creating a tight `hhvm` image would be really easy: https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Debian-8

**Comment by md5** [comment]
I had a few minutes free while waiting for something else, so I whipped this up: https://gist.github.com/md5/3b8cef5bc53ac0b54f69

**Comment by joelchen** [comment]
Nice work @md5! Hope this upcoming variant will be able to achieve what I want with or without https://github.com/md5/nginx-proxy/tree/multiple-paths.

**Comment by tianon** [comment]
Guessing you got this figured out by now. :smile:
