### ISSUE TITLE
Change of IP addresses on the container causes a problem

### ISSUE THREAD

**Issue by gourao** [docker-library/wordpress#72]
When I stop and restart my wordpress container, it gets a new IP.  When I access the service at the new IP, the page is malformed because it has hardcoded refs to the old IP.

Am I doing something wrong or is this image reliant on non-changing IPs?

**Comment by yosifkit** [comment]
Wordpress uses however you access it the first time to determine what "host" it is, whether that be an ip address or a dns name.

If you are hosting this for "the world" then I would suggest forwarding the port to the host and pointing a dns entry at the host, or possibly a setup with an nginx proxy in front.

If you are just accessing it locally, then a tool I have found useful is [rawdns](https://github.com/tianon/rawdns).  This allows you to run a dns server that can give you the container called `my-wp` at the dns of `my-wp.docker` (with fancy things like `mysql.my-wp.docker` for linked containers).  You can just use the docs there, but there is a great blog post on setting it up by [psftw](https://psftw.com/2015/01/31/docker_aware_dns_and_transparent_apt_caching.html); it includes setting up an apt cache, but that could be skipped if you don't want it.

**Comment by gourao** [comment]
@yosifkit thanks.

**Comment by pierreozoux** [comment]
@gourao if it solved your issue, please consider closing it.

Thanks!
