### ISSUE TITLE
How long until the docker hub image is updated?

### ISSUE THREAD

**Issue by voldemortensen** [docker-library/wordpress#76]
My pull request was merged 2 days ago, but https://registry.hub.docker.com/_/wordpress/ is still showing the previous version.

**Comment by yosifkit** [comment]
Sorry for the delay.  It will be ready once this PR merges and builds: https://github.com/docker-library/official-images/pull/693

**Comment by voldemortensen** [comment]
Ah. Thanks. I'll just keep an eye on this an that. 4.2.1 was a security release and I'm eager to get it deployed.
