### ISSUE TITLE
When will 6.1 be available on Dockerhub?

### ISSUE THREAD

**Issue by joeldeteves** [docker-library/wordpress#768]
I see `latest` has already been updated but the changes don't appear on the Dockerhub, which still shows latest tag from 7 days ago and beta-rc6 under the 6.1 tag.

When should we expect to be able to update to 6.1 release?

**Comment by tianon** [comment]
https://github.com/docker-library/wordpress#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet :eyes:

(I've just opened https://github.com/docker-library/official-images/pull/13461)

**Comment by joeldeteves** [comment]
Thank you!
