### ISSUE TITLE
wordpress:fpm-alpine still points to PHP 7.4

### ISSUE THREAD

**Issue by timdream** [docker-library/wordpress#774]
`docker pull wordpress:fpm-alpine` pulls the same image as `wordpress:php7.4-fpm-alpine`. See https://hub.docker.com/_/wordpress/tags?page=1&name=fpm-alpine.

PHP 7.4 reaches EOL as of yesterday.

**Comment by tianon** [comment]
:weary:

The justification for 7.4 still being the default was https://make.wordpress.org/hosting/handbook/server-environment/#php (support for PHP 8+ is still "beta"), but I guess we have to revisit that now. :disappointed:
