### ISSUE TITLE
uid & gid not even considered by container

### ISSUE THREAD

**Issue by MightyMirko** [docker-library/wordpress#776]
Hello Dudes and Dudettes,

i do have an issue. The container is working really well, but it is not accepting my UID and GID given in docker-compose.yml.

Root is 0, and www-data is still 33.. 
What is best-practice here? 

    wordpress:
        image: wordpress:latest
        container_name: wordpress_matosin1
        volumes:
          - /opt/docker/myd.eu/wordpress_cv/wp_data:/var/www/html
          - ./wp_data/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
        restart: always
        environment:
          - PUID=1000
          - PGID=1000
          - ....

**Comment by MightyMirko** [comment]
This is one of the issues following   

   root@c802120a8b39:/var/www/html# wp media regenerate
    Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress installation exists under.
    
    If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.
    
    If you'd like to continue as root, please run this again, adding this flag:  --allow-root
    
    If you'd like to run it as the user that this site is under, you can run the following to become the respective user:
    
        sudo -u USER -i -- wp <command>

**Comment by zimnyd** [comment]
If you run docker exec, you will allways be a root user. As a example I run the folowing command to be different user: 
`docker exec -it --user=www-data your_image ypour_command`

**Comment by yosifkit** [comment]
This image doesn't do anything with `PUID` or `PGID`. See the ["Running as an arbitrary user" section](https://github.com/docker-library/docs/blob/323360066f17644ed4d6394b0ee14cec8d8c5cb6/wordpress/README.md#running-as-an-arbitrary-user) of the Docker Hub description.

**Comment by bbrendon** [comment]
Does anyone know of a wordpress Docker image that supports `PUID` and `PGID` ?

**Comment by bbrendon** [comment]
try
```
  wordpress:
    #image: wordpress:latest
    image: wordpress:5.9.3-apache
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - 4080:80
    #restart: always
    user: "1006:1006"
```
