### ISSUE TITLE
How to change to www-data?

### ISSUE THREAD

**Issue by siddjain** [docker-library/wordpress#779]
Hello we are using wordpress docker image. Thanks for this image first of all. We can login to a running container using:

```
docker exec -it container-name /bin/bash
```

This logs the user as `root`. From here how can we change the user to `www-data`? We tried:

```
su www-data
```

but it says:

```
This account is not available
```

Thanks for your help.

**Comment by siddjain** [comment]
I found the fix for this:

```
su www-data -s /bin/bash
```

The reason for error is because in the `/etc/passwd` file, the user `www-data`'s shell is set to `/sbin/nologin`

**Comment by zimnyd** [comment]
Try this: docker exec -it --user=www-data container-name /bin/bash
