### ISSUE TITLE
Lots of PHP warnings since 6.1.1 version

### ISSUE THREAD

**Issue by leolivier** [docker-library/wordpress#790]
Hi
Since I moveď to version 6.1.1 on arm64, I get the following four lines in the logs on each access:
```
[Thu Jan 05 18:40:56.587382 2023] [php:warn] [pid 20] [client 127.0.0.1:34880] PHP Warning:  Array to string conversion in /var/www/html/wp-config.php(122) : eval()'d code on line 1

[Thu Jan 05 18:40:56.587470 2023] [php:warn] [pid 20] [client 127.0.0.1:34880] PHP Warning:  Undefined variable $Array in /var/www/html/wp-config.php(122) : eval()'d code on line 1

[Thu Jan 05 18:40:56.587515 2023] [php:warn] [pid 20] [client 127.0.0.1:34880] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/wp-config.php(122) : eval()'d code on line 1

[Thu Jan 05 18:40:56.587971 2023] [php:warn] [pid 20] [client 127.0.0.1:34880] PHP Warning:  Array to string conversion in /var/www/html/wp-config.php(122) : eval()'d code on line 1

```
When I try to see what is on line 122 on that file, it's a blank line and nothing special around...
```


/** Database hostname */

define( 'DB_HOST', getenv_docker('WORDPRESS_DB_HOST', 'mysql') );



/** Database charset to use in creating database tables. */
<<<<< line 122 is here >>>>
define( 'DB_CHARSET', getenv_docker('WORDPRESS_DB_CHARSET', 'utf8') );



/** The database collate type. Don't change this if in doubt. */

define( 'DB_COLLATE', getenv_docker('WORDPRESS_DB_COLLATE', '') );
```

**Comment by tianon** [comment]
Are you setting `WORDPRESS_EXTRA_CONFIG`?

**Comment by leolivier** [comment]
Yes, in my .env file I have:
```
WORDPRESS_CONFIG_EXTRA=$$_SERVER['REMOTE_ADDR'] = $$_SERVER['HTTP_CF_CONNECTING_IP'];
```
but I didn't change that for years (I even had forgotten it)

**Comment by tianon** [comment]
I would guess that PHP version updates have changed how your `$$` there works and that's probably what's causing the warnings (that's the only `eval` in `wp-config.php` that I'm aware of).

**Comment by leolivier** [comment]
Thanks @tianon I will investigate in that direction

**Comment by leolivier** [comment]
I commented the line in my .env file and the warning disappeared. 
I don't even remember why I did set that, only a comment saying that it had to forward the cloudflare IP (I'm using Cloudflare as a proxy)

**Comment by leolivier** [comment]
For those who have the same issue, it looks like double $ syntax is now passed 'as is' to the eval so we now should use in .env:
`WORDPRESS_CONFIG_EXTRA=$_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_CF_CONNECTING_IP'];`instead of `WORDPRESS_CONFIG_EXTRA=$$_SERVER['REMOTE_ADDR'] = $$_SERVER['HTTP_CF_CONNECTING_IP'];`
Honestly, I don't really understand where the issue is coming from: docker? wordpress entrypoint? (it's not linked to PHP)

**Comment by yosifkit** [comment]
Perhaps the `docker-compose` `.env` file handling has changed? So that if you set it in `.env` file, then the single `$` is correct, but if it is set directly in the `compose.yml` file, then the double `$` is needed so that `docker-compose` yaml interpolation ends up with a single `$` after evaluation.
