### ISSUE TITLE
php-gb missing 

### ISSUE THREAD

**Issue by soichih** [docker-library/wordpress#80]
I am using the current latest wordpress container, and when I try to crop image inside Media library, I get an error message

"There has been an error cropping your image".

Is it reported here 
> http://terminaltwister.com/there-has-been-an-error-cropping-your-image-solution-to-wordpress-error/

that you need to install php-gd.

**Comment by soichih** [comment]
I've tried adding php5-gd but that didn't help.


```
FROM wordpress
RUN apt-get update
RUN apt-get -y install php5-gd
```

So.. maybe something else needs to happen.

**Comment by tianon** [comment]
We do install `gd` (https://github.com/docker-library/wordpress/blob/939fefa77f68928d19750760023af7dfe48828c8/apache/Dockerfile#L7-L8), so I'm thinking there must be something else missing.  The error message sounds like it was very vague, so I wonder if there was anything better in the logs to help us narrow down what's missing?

**Comment by soichih** [comment]
The only log I see via "docker logs -f" is this.

172.17.42.1 - - [16/May/2015:13:45:04 +0000] "POST /wp-admin/admin-ajax.php HTTP/1.0" 200 831 "http://soichi7.ppa.iu.edu/wp-admin/customize.php?return=%2Fwp-admin%2F" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36"

logs inside /var/log/apache2 in the container are all empty also.

-rw-r----- 1   33   33    0 Apr 30 04:34 access.log
-rw-r----- 1   33   33    0 Apr 30 04:34 error.log
-rw-r----- 1   33   33    0 Apr 30 04:34 other_vhosts_access.log

Is there way to turn on some debug log?

**Comment by pierreozoux** [comment]
@soichih did you find an answer to your question? If yes, please consider closing this issue.

Thanks!

**Comment by mkrupczak3** [comment]
Hmmmmmmmmmm.
@tianon @pierreozoux 

Any chance on reopening this? I'm having the same issue. Not sure what else it could be. Did running those install commands inside the container fix it?

Using wordpress:5.2.3-php7.1-fpm with an Nginx proxy and Cache

https://stackoverflow.com/questions/24043991/image-crop-editor-not-working#33771117

**Comment by tianon** [comment]
@mkrupczak3 I'd recommend opening a new issue with detailed reproduction steps from a vanilla fresh WordPress install so we can reliably reproduce the issue and thus debug/fix it more appropriately.
