### ISSUE TITLE
Adding wordpress Dockerfile for power architecture ( ppc64le ) for Rhel 7.1 /Ubuntu 14.10 platform

### ISSUE THREAD

**Issue by amitkumarghatwal** [docker-library/wordpress#81]
Hi All,

I have successfully created/tested dockerfile for wordpress on power architecture(ppc64le) - on Ubuntu 14.10 (using single container approach using supervisor - reference : https://github.com/how2dock/docbook/tree/master/ch01/supervisor) /Rhel 7.1 ( Using two container approach - Apache/mysql ) . 

Could you please let me know the steps of contributing the dockerfile (not the docker container ) for wordpress on ppc64le architecture at  this location .?

Regards,
Amit

**Comment by yosifkit** [comment]
It would be awesome to have multiple architectures for the official images. Unfortunately docker, the Docker Hub, and the Official Images program only officially support amd64 images, but hopefully this will change in the near future.

**Comment by amitkumarghatwal** [comment]
Hi @yosifkit ,

I would like to contribute wordpress dockerfile for power architecture by adding (_ppc64le) suffix in the file name.

Request you to please comment on the above suggestion for uploading dockerfiles for power architecture.

Regards,
Amit

**Comment by tianon** [comment]
Please see https://hub.docker.com/r/ppc64le/wordpress/ :+1: :smile:

(https://github.com/docker-library/official-images#architectures-other-than-amd64)
