### ISSUE TITLE
Where is wordpress:6.2 ?

### ISSUE THREAD

**Issue by champsupertramp** [docker-library/wordpress#814]
Hi,

WordPress 6.2 has been released. Is the image with tag official 6.2 already pushed to the docker registry?

I tried:
`wordpress:6.2-php8.1-apache` 

It says 
`Error response from daemon: manifest for wordpress:6.2-php8.1-apache not found: manifest unknown: manifest unknown`

**Comment by yosifkit** [comment]
See the readme section: [See a change merged here that doesn't show up on Docker Hub yet?](https://github.com/docker-library/wordpress/tree/5f5172057791d1deb1919fdd1c5c45e7daae3362#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet). So after https://github.com/docker-library/official-images/pull/14372 merges and the images get built.
