### ISSUE TITLE
healthchecks not possible without fcgi package

### ISSUE THREAD

**Issue by kale1d0code** [docker-library/wordpress#815]
fcgi package should be installed in fpm image variants
without it, it isn't possible to check the health of the php-fpm process

**Comment by tianon** [comment]
Running FPM doesn't require the fcgi package, so it isn't included by default (if we include it by default, then even users who don't need it have to take the storage/bandwidth hit of it being included).  I would recommend that users who require it write themselves a short `Dockerfile` that builds an image `FROM` this one which installs it.
