### ISSUE TITLE
[wordpress:6.2-php7.4-apache] manifest not found

### ISSUE THREAD

**Issue by justlevine** [docker-library/wordpress#816]
Getting the following error in my CI, when trying to use WP 6.2 + PHP 7.4:

`manifest for wordpress:6.2-php7.4-apache not found: manifest unknown: manifest unknown`

And indeed, the [latest PHP 7.4 images that were pushed](https://hub.docker.com/_/wordpress/tags?page=1&name=php7.4) are from 5 months ago, with the release of 6.1.

**Comment by yosifkit** [comment]
PHP 7.4 images had to be dropped in https://github.com/docker-library/wordpress/pull/775 once 7.4 reached end of life. They are no longer updated (and thus did not get a WordPress 6.2 image).

**Comment by yosifkit** [comment]
Unfortunately, PHP versions are only supported for 3 years from release (https://www.php.net/supported-versions.php). PHP 7.4 reached end of life in November 2022; we will not be bringing it back.  It looks like 8.1 is recommended (and not even 8.0) for WordPress 6.3 for hosting companies: https://make.wordpress.org/hosting/handbook/server-environment/#php.

**Comment by justlevine** [comment]
@yosifkit while that indeed may be true, the latest WordPress 6.3 still *officially* supports PHP 7.0+, so it seems a bit counterintuitive that new images with the latest compatible WordPress versions dont get created for EOL PHP versions. Especially when such a big use case for these docker images is matrix testing.

Perhaps this policy can be reevaluated?

**Comment by tianon** [comment]
Unfortunately, that's out of scope for the images we maintain and we will not be maintaining images based on EOL PHP versions.  If a project wanted to support the full matrix of supported things, it would want to _also_ support all the actively maintained branches of WordPress, of which there are _many_ (honestly, I think this is one of the most impressive things about the entire WordPress project, from the perspective of a fellow "open source software maintainer"): https://wordpress.org/download/releases/ -- you can go back as far as the 4.1.x series and still see active security releases.
