### ISSUE TITLE
PHP extension sockets is required

### ISSUE THREAD

**Issue by draganmudric** [docker-library/wordpress#817]
Hi all,

I am running the latest 6.2 version of wordpress in aws ecs. There is a plugin that I use to ship logs to the syslog server called WP Activity Log. Since upgrading to version 6.2 I am not able to create a connection to my syslog server with the following error:

`PHP extension sockets is required`

Any idea what has been changed and how to resolve it?

**Comment by tianon** [comment]
I would guess it's probably the "refactored core" mentioned in https://wpactivitylog.com/support/kb/plugin-changelog/, although I can't find an explicit reference to what that means/entails.

However, generally we only include the PHP extensions required for the core WordPress functionality, so we will not be including `sockets` unless/until WordPress itself requires it in core.

To resolve this, you'll need to build your own image `FROM` this one which includes the `sockets` extension (see "Adding additional libraries / extensions" on https://hub.docker.com/_/wordpress).

**Comment by draganmudric** [comment]
Thank you so much for pointing me to the right direction @tianon .

I resolved it by adding this to my Dockerfile:


```
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions sockets
```
