### ISSUE TITLE
WordPress v6.2.2 Not available

### ISSUE THREAD

**Issue by Dudi1896** [docker-library/wordpress#825]
Docker's official image for wordpress only goes up to version 6.2.1. When I set the image manually to 6.2.2, I get an error. When I set it to latest I get 6.2.1. Is there a way to work around this by using composer.json to install this for docker or do we just have to wait until docker releases an official v6.2.2

`version: '3.8'

services:
  composer:
    image: composer
    command: update
    volumes:
      - ./wordpress:/app

  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8183:80"

  wordpress:
    depends_on:
      - mysql
      - composer
    image: wordpress:6.2.2
    ports:
      - "8020:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_AUTO_UPDATE_CORE: "true"
      WORDPRESS_AUTO_UPDATE_PLUGINS: "true"
      WORDPRESS_AUTO_UPDATE_THEMES: "true"
    volumes:
      - ./wordpress:/var/www/html:rw

volumes:
  mysql_data: {}
`

**Comment by yosifkit** [comment]
>Is there a way to work around this by using composer.json to install this for docker or do we just have to wait until docker releases an official v6.2.2

There is no composer used in the image. One way to get it faster is to clone this repo and build the image. Another way is to just run the old version and let WP update itself.

https://github.com/docker-library/wordpress/tree/6fa05d9ba94e7cb48a53ff90878cc6fc777f7986#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

The [version bump](https://github.com/docker-library/wordpress/commit/6fa05d9ba94e7cb48a53ff90878cc6fc777f7986) was only automatically committed to this repo during this past weekend. There will be a PR to update it `docker-library/official-images` shortly.

**Comment by Dudi1896** [comment]
awesome, thanks!
