### ISSUE TITLE
Unable to Find Explanation for Persistence of WordPress Code in /var/www/html When Mounted from Host Machine in Docker Container

### ISSUE THREAD

**Issue by cikiChe** [docker-library/wordpress#845]
I want to know why WordPress code can be placed inside /var/www/html and why this directory is not overwritten when mounted from the host machine. I couldn't find an answer through Google or GPT, and I also studied the Dockerfile but couldn't find any relevant copy instructions.

**Comment by yosifkit** [comment]
On startup (assuming it looks like it doesn't already contain WordPress), the pristine WordPress copy from the image (`/usr/src/wordpress`), is copied to `/var/www/html` via the entrypoint script: 

https://github.com/docker-library/wordpress/blob/940a0d35951a0917622c35acc92b38b1db3c730f/docker-entrypoint.sh#L28-L68

**Comment by cikiChe** [comment]
Thank you. I'll try setting a breakpoint when I get back tonight.
