### ISSUE TITLE
PHP 8.1 version causes critical errors in WordPress Site Health 

### ISSUE THREAD

**Issue by edwinbradford** [docker-library/wordpress#848]
The Docker WordPress version tagged `wordpress:6.3.1-php8.1` causes critical errors in the WordPress Site Health screen, changing to `wordpress:6.3.1-php8.0` resolves the issue.

I forked [this five year old project](https://github.com/ronamosa/docker-wordpress-nginx-ssl-mysql) and resurrected it [here](https://github.com/edwinbradford/wnsm).

Initially the Site Health tests passed without critical errors until I changed the Docker WordPress version in Docker Compose from `wordpress:latest` to `wordpress:6.3.1-php8.1` which is the same version I was using in another project that was reporting the same errors. On changing the Docker WordPress version to `wordpress:6.3.1-php8.0` the errors magically disappeared.

I now realise `wordpress:latest` is not `php 8.1` but `php:8.0`.

You should be able to reproduce the error by cloning my forked repository and changing the WordPress version as described. I assume this is a problem with WordPress and PHP and nothing to do with the Official Docker WordPress project in which case you can close this issue however it's taken me three weeks to find the cause so hopefully reporting it will help others.

I don't know if it's relevant but both my projects are running a reverse proxy, Apache in one and Nginx in the one I linked to.

**Comment by tianon** [comment]
Do you have a list of _which_ critical errors were listed?  For context, our "default" PHP version is chosen based on:

- https://wordpress.org/about/requirements/
- https://make.wordpress.org/hosting/handbook/server-environment/#php
- https://wordpress.org/support/update-php/#before-you-update-your-php-version
- https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/

**Comment by edwinbradford** [comment]
Sorry, I reported the issue three months ago when I was using Docker every day but I'm on another project now. I assume the easiest solution is for you to clone the repos I linked to and the errors should be reproducible and listed on the Site Health screen.

**Comment by tianon** [comment]
I deployed an instance using https://github.com/docker-library/docs/blob/09d36ce2b087af4dc1f1127de1f42f256af11bb3/wordpress/stack.yml, but updating `image: wordpress` explicitly to `image: wordpress:php8.3` to increase my chances of issues, and everything in Site Health is something I'd expect to see, so I think WordPress upstream must've fixed this while I was out on extended leave: :sweat_smile: :heart:

![image](https://github.com/docker-library/wordpress/assets/161631/5519c924-2c05-4dc9-b7c4-54c9d726b5c9)
