### ISSUE TITLE
Wordpress and Mysql Failure 

### ISSUE THREAD

**Issue by hughbrien** [docker-library/wordpress#85]
Try to run a container with 

docker run --name mysql -e MYSQL_ROOT_PASSWORD=vetslist -d mysql:5.7

docker run  --name wordpress  -e WORDPRESS_DB_PASSWORD=vetslist -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_HOST=localhost -e WORDPRESS_DB_NAME=wordpress  --link mysql:mysql-server -p 8080:80 -d wordpress 

Keeps failing with 
osxlthbrien:VetsList hbrien$ docker logs wordpress
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html

Warning: mysqli::mysqli(): (HY000/2002): No such file or directory in - on line 10

MySQL Connection Error: (2002) No such file or directory

Warning: mysqli::mysqli(): (HY000/2002): No such file or directory in - on line 10

MySQL Connection Error: (2002) No such file or directory

Warning: mysqli::mysqli(): (HY000/2002): No such file or directory in - on line 10

MySQL Connection Error: (2002) No such file or directory

**Comment by tianon** [comment]
I think instead of `--link mysql:mysql-server`, you meant `--link mysql:mysql`.

**Comment by pierreozoux** [comment]
@hughbrien did it solve your issue? If yes, please close it.

Thanks!
