### ISSUE TITLE
WordPress asking for FTP credentials to install plugins

### ISSUE THREAD

**Issue by lmartins** [docker-library/wordpress#86]
Hi, I've finally managed to get WordPress working and mapped to a host folder, however now when I try to install a theme or plugin WordPress asks me for FTP credentials. Im guessing this is related to file permissions and wonder if you could help me sort this out.

Thanks.

**Comment by yosifkit** [comment]
That is definitely a permission issue.  You'll need to make sure that the Wordpress container has write access to the mapped host folder or at least the `wp-content` folder inside that.

**Comment by lmartins** [comment]
Thanks @yosifkit 
I am now running a different container which uses nginx and runs as root and since this is for local development only that did the trick for me. 
Im closing this for now, if anyone having the same issue, you can find a blog post here:
http://goldsounds.com/archives/2015/04/06/quick-and-easy-wordpress-development-using-docker/

Thanks.
