### ISSUE TITLE
Unable to run on CoreOS (exec: -p: invalid option)

### ISSUE THREAD

**Issue by martijnve** [docker-library/wordpress#87]
When i run docker on CoreOS (stable) like this:
docker run --name myWp \
-e WORDPRESS_DB_HOST=... \
-e WORDPRESS_DB_NAME=... \
-e WORDPRESS_DB_USER=... \
-e WORDPRESS_DB_PASSWORD=... \
-d wordpress -p 8080:80

I get the following output from docker logs:
WordPress not found in /var/www/html - copying now...
WARNING: /var/www/html is not empty - press Ctrl+C now if this is an error!
+ ls -A
index.html
+ sleep 10
Complete! WordPress has been successfully copied to /var/www/html
/entrypoint.sh: line 145: exec: -p: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]

I did the test on a new CoreOS stable installation.

cat /etc/os-release:
NAME=CoreOS
ID=coreos
VERSION=681.2.0
VERSION_ID=681.2.0
BUILD_ID=
PRETTY_NAME="CoreOS 681.2.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**Comment by yosifkit** [comment]
`s/wordpress -p 8080:80/-p 8080:80 wordpress/`: the `-p` option needs to be on the docker run, not in the args to the container.

**Comment by pierreozoux** [comment]
@martijnve did it solve the issue? If yes, please close it! Thanks
