### ISSUE TITLE
Docker Compose documenation is out of date relative to Wordpress

### ISSUE THREAD

**Issue by vielmetti** [docker-library/wordpress#88]
The documentation you get from Docker Compose on how to run under Wordpress is not up to date relative to the official Wordpress install from the library.

See https://github.com/docker/compose/issues/1685 which is the issue against the Compose documentation.

**Comment by Moghedrin** [comment]
While I agree that this is an issue, it is not an issue with the library image, nor the documentation specifically for that image. As such, the issue opened at [docker/compose#1685](https://github.com/docker/compose/issues/1685) is sufficient and doesn't need to be duplicated here.
