### ISSUE TITLE
ftps doesn't work starting from php 8

### ISSUE THREAD

**Issue by wc-matteo** [docker-library/wordpress#883]
# php 7

```docker
FROM wordpress:6-php7.4

# Install necessary packages for FTP and SSL support
RUN apt-get update && \
    apt-get install -y libssl-dev && \
    docker-php-ext-install ftp
```

![image](https://github.com/docker-library/wordpress/assets/10562635/0b1dd316-6b2c-4127-8efc-eb3bdb702fbf)

# php 8

```docker
FROM wordpress:6-php8.3

# Install necessary packages for FTP and SSL support
RUN apt-get update && \
    apt-get install -y libssl-dev && \
    docker-php-ext-install ftp
```

![image](https://github.com/docker-library/wordpress/assets/10562635/fd2eadc9-88d5-4778-ae00-7ce7745b13d4)

phpinfo shows **ftps support** `disabled` and ` php -r 'var_dump(function_exists("ftp_ssl_connect"));'` returns `bool(false)`

**Comment by tianon** [comment]
See https://github.com/docker-library/php/issues/1488
