### ISSUE TITLE
The 6.5 tags are not on Docker Hub

### ISSUE THREAD

**Issue by gcarre** [docker-library/wordpress#891]
Although they are listed on https://hub.docker.com/_/wordpress, the 6.5 tags have not been pushed.

<img width="807" alt="image" src="https://github.com/docker-library/wordpress/assets/1388584/c80103e9-1d35-479e-8dc9-ab4fa0792dd8">

```
~ docker pull wordpress:6.5.0-php8.1-apache
Error response from daemon: manifest for wordpress:6.5.0-php8.1-apache not found: manifest unknown: manifest unknown
```

**Comment by yosifkit** [comment]
They were only merged in: https://github.com/docker-library/official-images/pull/16528. It takes time for them to be built and pushed.
