### ISSUE TITLE
a c or assembly or webasm compiled wordptess please with a precommit compilation so php's drawbacks arent bothering people

### ISSUE THREAD

**Issue by lootnath** [docker-library/wordpress#896]
asm and webcache compiled wordpress server please

**Comment by tianon** [comment]
Sorry, I'm not sure exactly what you're looking for here?  Is there some documentation from WordPress upstream about what it is you're proposing we do?

**Comment by joemaller** [comment]
@tianon pretty sure that’s a bot account.

**Comment by yosifkit** [comment]
"looks like spam"

Note: we don't control the source of WordPress, so you'll have to ask upstream if you want them to completely rewrite it in another language. 🤦😆 (you'll have better luck just using a different product)
