### ISSUE TITLE
Unable to change Apache port

### ISSUE THREAD

**Issue by vchav73** [docker-library/wordpress#90]
I need to run the Apache server in the Wordpress container on something other than the default port of 80. Is there a way to change this?

**Comment by md5** [comment]
No, there is no way to configure this unless you replace the default `apache2.conf` from the `php:apache` base image (cf. https://github.com/docker-library/php/blob/master/5.6/apache/apache2.conf#L19-L25)

If it were to be made possible, that likely be done in the `php:apache` image. In fact, there's a feature request for that change here: https://github.com/docker-library/php/issues/94

**Comment by vchav73** [comment]
Closing as this is an existing feature request.
