### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [docker-library/wordpress#922]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Wordpress application as shown [here](https://elest.io/open-source/wordpress). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Let me know and I will create the pull request

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/wordpress)

**Comment by mikedon** [comment]
hey @kaiwalyakoparkar - Thanks for reaching out. I'll send you an email to close the loop on the discussion.

**Comment by tianon** [comment]
I'll go ahead and close this now as Mike is following up out-of-band. :+1:
