### ISSUE TITLE
fpm version not working

### ISSUE THREAD

**Issue by marians** [docker-library/wordpress#94]
I just tried running wordpress locally. The `:apache` version is working, the `:fpm` version is not. The image hash I was testing is `dd9e5297815a`.

Here is how I set things up:

```
docker run -d --name wordpress-mysql -p 3306:3306 \
		-e MYSQL_ROOT_PASSWORD=rootpassword \
		-e MYSQL_DATABASE=wordpress \
		mysql:5.5
docker run --name wordpress --link wordpress-mysql:mysql --rm -ti \
		-p 9000:9000 \
		-e WORDPRESS_DB_USER=root \
		-e WORDPRESS_DB_PASSWORD=rootpassword \
		wordpress:fpm
```

Note that I used port 9000 since this is the one that is supposedly exposed by the php:5.6-fpm base image.

**Comment by md5** [comment]
See https://github.com/docker-library/wordpress/pull/92

I believe those changes got pushed to Docker Hub yesterday, but @tianon or @yosifkit can confirm.

**Comment by md5** [comment]
Actually, it looks like https://github.com/docker-library/official-images/pull/963 still needs to merge.

**Comment by marians** [comment]
So https://github.com/docker-library/official-images/pull/963 is merged now.

I pulled the latest `wordpress:fpm` image and got  the one with hash `8278552ea7f1`.

Still, I can't make it work. It starts. The wordpress container logs this:

```
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html
[13-Aug-2015 09:28:34] NOTICE: fpm is running, pid 1
[13-Aug-2015 09:28:34] NOTICE: ready to handle connections
```

But I can't get anything on port 9000.

`docker ps` shows this:

```
docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                    NAMES
ac822a94538a        wordpress:fpm       "/entrypoint.sh php-   23 seconds ago      Up 22 seconds       0.0.0.0:9000->9000/tcp   wordpress_wordpress_1   
3b63d3575b06        mysql:5.5           "/entrypoint.sh mysq   24 seconds ago      Up 24 seconds       3306/tcp                 wordpress_mysql_1
```

**Comment by md5** [comment]
How are you trying to “get something" on port 9000? You'll have to connect
to it with something that speaks the FastCGI protocol, not a browser.

**Comment by marians** [comment]
I guess that explains it. I accessed it via HTTP via the browser.

**Comment by md5** [comment]
FWIW, you can do something like I did in [this test](https://github.com/docker-library/official-images/tree/master/test/tests/php-fpm-hello-web) to test FastCGI directly, or you can set up an `nginx` proxy using a config like the one in this gist: https://gist.github.com/md5/d9206eacb5a0ff5d6be0
