### ISSUE TITLE
Automatic updates not working

### ISSUE THREAD

**Issue by RomkeVdMeulen** [docker-library/wordpress#95]
I've been trying to get [automatic background updates](https://codex.wordpress.org/Configuring_Automatic_Background_Updates) working on the blogs I run using this image, but so far no luck. Manually updating works fine, but no matter how I try to configure this, nothing happens. I've used plugins that work on other WP environments, I've set the relevant constants in my `wp-config.php`, but even after waiting days the updates are not applied.

Does anybody have any experience with this? Is this a known problem?

**Comment by md5** [comment]
My suspicion is that this feature uses cron and that the problem is that
there is no cron daemon running in the container. That page you linked to
isn't clear on how the “background" aspect of the feature is implemented.

**Comment by Romke-vd-Meulen** [comment]
That was my first thought as well, but aparently WP uses a pseudo-cron system that is triggered by visits, not Unix cronjobs.

**Comment by md5** [comment]
FWIW, I just did a `docker pull wordpress:4.2.3` and spun up an older version of the container. After going through the install screen and getting to `/wp-admin`, I saw that it had already updated itself to 4.2.4, so I think automatic updates are working at least in the simple case.

Did you mount your wordpress install from an external directory? If so, are you sure that the files are actually writable by the `www-data` user?

**Comment by Romke-vd-Meulen** [comment]
Interesting. In my case I'm mounting a host directory for the Wordpress install, so that might be influencing. Although if it's a rights problem, I wouldn't expect manual updates to work either.

I'll see if I can reproduce the problem in a minimal setup. I'll let you know.

**Comment by Romke-vd-Meulen** [comment]
I've started up a Wordpress container without volumes, enabled automatic updates and installed the [Background Updates Tester](https://wordpress.org/plugins/background-update-tester/) plugin, which reports:

```
Automatic background updates require a number of conditions to be met.
PASS: Your WordPress install can communicate with WordPress.org securely.
PASS: No version control systems were detected.
PASS: Your installation of WordPress doesn’t require FTP credentials to perform updates.
PASS: All of your WordPress files are writable.
```

I read [somewhere](https://wordpress.org/support/topic/automatic-background-updates) that background updates only run at 7am/7pm so I set the timezone to UTC+7 to make Wordpress think it's 7pm now.

But still, nothing. Neither themes, not plugins, not Wordpress core have been updated.

**Comment by yosifkit** [comment]
According to wordpress, the automatic updates are only for security fixes.  What version is it and what version is it expected to become?  I also don't think themes or plugins are automatically updated.

**Comment by Romke-vd-Meulen** [comment]
https://codex.wordpress.org/Configuring_Automatic_Background_Updates

Minor core-updates (1.0.X) are installed by default. Major core updates as well as theme and plugin updates can be enabled manually or by installing certain plugins, both of which I've tried.
