### ISSUE TITLE
Allow table_prefix to be set via ENV variables

### ISSUE THREAD

**Issue by peterkuiper** [docker-library/wordpress#96]
I would like to propose an enhancement to the official image. Currently, it is not possible to change the table_prefix via an ENV variable which makes it a bit harder to get an existing installation (depending on a non standard table prefix) working. It would be an easy change and I'm sure it would help certain setups greatly (including mine).

**Comment by lazyfrosch** [comment]
I think a PR will be welcome :)

**Comment by yosifkit** [comment]
Sounds reasonable to me.

**Comment by peterkuiper** [comment]
How about something like this?

diff --git a/apache/docker-entrypoint.sh b/apache/docker-entrypoint.sh
index 0e8aa1e..affca1e 100755
--- a/apache/docker-entrypoint.sh
+++ b/apache/docker-entrypoint.sh
@@ -88,6 +88,10 @@ EOPHP
 	set_config 'DB_PASSWORD' "$WORDPRESS_DB_PASSWORD"
 	set_config 'DB_NAME' "$WORDPRESS_DB_NAME"

+    if [ ! -z $WORDPRESS_TABLE_PREFIX ]; then
+        sed -ri 's/^(\$table_prefix)\s*=\s*.*$/\1 = \x27'"$WORDPRESS_TABLE_PREFIX"'\x27;/' wp-config.php
+    fi
+
 	# allow any of these "Authentication Unique Keys and Salts." to be specified via
 	# environment variables with a "WORDPRESS_" prefix (ie, "WORDPRESS_AUTH_KEY")
 	UNIQUES=(
